# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 18:11
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('ARTICULO', 'Artículo'), ('ACTA', 'Acta'), ('CARTA', 'Carta'), ('RESENA', 'Reseña'), ('OTRO', 'Otro')], max_length=16)),
                ('status', models.CharField(choices=[('PUBLICADO', 'Publicado'), ('EN_PRENSA', 'En prensa'), ('ACEPTADO', 'Aceptado'), ('ENVIADO', 'Enviado'), ('OTRO', 'Otro')], max_length=20)),
                ('solo_electronico', models.BooleanField(default=False)),
                ('nombre_abreviado_wos', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('fecha', models.DateField()),
                ('volumen', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('issn_impreso', models.CharField(blank=True, max_length=40, verbose_name='ISSN Impreso')),
                ('issn_online', models.CharField(blank=True, max_length=40, verbose_name='ISSN Online')),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
                ('id_doi', models.CharField(blank=True, max_length=100)),
                ('id_wos', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Artículos científicos',
                'verbose_name': 'Artículo científico',
                'ordering': ['fecha', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='CapituloLibroInvestigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Capítulos en libros',
                'verbose_name': 'Capítulo en libro',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='InformeTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('numero_paginas', models.PositiveIntegerField(default=1)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Informes técnicos de acceso público',
                'verbose_name': 'Informe técnico de acceso público',
                'ordering': ['fecha', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='MapaArbitrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('escala', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('PUBLICADO', 'Publicado'), ('EN_PRENSA', 'En prensa'), ('ACEPTADO', 'Aceptado'), ('ENVIADO', 'Enviado'), ('OTRO', 'Otro')], max_length=20)),
                ('fecha', models.DateField()),
                ('numero_edicion', models.PositiveIntegerField(default=1)),
                ('numero_paginas', models.PositiveIntegerField(default=1)),
                ('volumen', models.CharField(blank=True, max_length=255)),
                ('isbn', models.SlugField(blank=True, max_length=30)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Mapas arbitrados',
                'verbose_name': 'Mapa arbitrado',
                'ordering': ['fecha', 'titulo'],
            },
        ),
    ]
