# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 23:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapaarbitrado',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ciudad'),
        ),
        migrations.AddField(
            model_name='mapaarbitrado',
            name='coleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Coleccion'),
        ),
        migrations.AddField(
            model_name='mapaarbitrado',
            name='coordinadores',
            field=models.ManyToManyField(blank=True, related_name='mapa_arbitrado_coordinadores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapaarbitrado',
            name='editores',
            field=models.ManyToManyField(blank=True, related_name='mapa_arbitrado_editores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapaarbitrado',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Editorial'),
        ),
        migrations.AddField(
            model_name='mapaarbitrado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Estado'),
        ),
        migrations.AddField(
            model_name='mapaarbitrado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pais'),
        ),
        migrations.AddField(
            model_name='mapaarbitrado',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Proyecto'),
        ),
        migrations.AddField(
            model_name='mapaarbitrado',
            name='usuarios',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='mapa_arbitrado_autores', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
        migrations.AddField(
            model_name='informetecnico',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Proyecto'),
        ),
        migrations.AddField(
            model_name='informetecnico',
            name='usuarios',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='informe_tecnico_autores', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
        migrations.AddField(
            model_name='capitulolibroinvestigacion',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Libro'),
        ),
        migrations.AddField(
            model_name='capitulolibroinvestigacion',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Proyecto'),
        ),
        migrations.AddField(
            model_name='capitulolibroinvestigacion',
            name='usuarios',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='capitulo_libro_investigacion_autores', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
        migrations.AddField(
            model_name='articulocientifico',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='articulo_cientifico_alumnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulocientifico',
            name='indices',
            field=models.ManyToManyField(blank=True, related_name='articulo_cientifico_indices', to='nucleo.Indice'),
        ),
        migrations.AddField(
            model_name='articulocientifico',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Proyecto'),
        ),
        migrations.AddField(
            model_name='articulocientifico',
            name='revista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Revista'),
        ),
        migrations.AddField(
            model_name='articulocientifico',
            name='usuarios',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='articulo_cientifico_autores', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
    ]
