# Generated by Django 6.1.1 on 2026-09-26 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("investigacion", "0001_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apoyotecnico",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="articulocientifico",
            name="agradecimientos",
            field=models.ManyToManyField(
                blank=True,
                related_name="articulos_cientificos_agradecimiento",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="articulocientifico",
            name="alumnos",
            field=models.ManyToManyField(
                blank=True,
                related_name="articulos_cientificos_alumno",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="articulocientifico",
            name="revista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.revista"
            ),
        ),
        migrations.AddField(
            model_name="articulocientificoautor",
            name="articulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="investigacion.articulocientifico",
            ),
        ),
        migrations.AddField(
            model_name="articulocientificoautor",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="articulocientifico",
            name="autores",
            field=models.ManyToManyField(
                related_name="articulos_cientificos",
                through="investigacion.ArticuloCientificoAutor",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="capitulolibroinvestigacion",
            name="libro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.libro"
            ),
        ),
        migrations.AddField(
            model_name="capitulolibroinvestigacionautor",
            name="capitulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="investigacion.capitulolibroinvestigacion",
            ),
        ),
        migrations.AddField(
            model_name="capitulolibroinvestigacionautor",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="capitulolibroinvestigacion",
            name="autores",
            field=models.ManyToManyField(
                related_name="capitulos_investigacion",
                through="investigacion.CapituloLibroInvestigacionAutor",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="mapaarbitrado",
            name="agradecimientos",
            field=models.ManyToManyField(
                blank=True,
                related_name="mapas_arbitrados_agradecimiento",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="mapaarbitrado",
            name="pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.pais",
                verbose_name="país",
            ),
        ),
        migrations.AddField(
            model_name="mapaarbitradoautor",
            name="mapa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="investigacion.mapaarbitrado",
            ),
        ),
        migrations.AddField(
            model_name="mapaarbitradoautor",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="mapaarbitrado",
            name="autores",
            field=models.ManyToManyField(
                related_name="mapas_arbitrados",
                through="investigacion.MapaArbitradoAutor",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="proyectoinvestigacion",
            name="financiamiento_institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proyectos_financiados",
                to="nucleo.institucion",
                verbose_name="institución que financia o colabora",
            ),
        ),
        migrations.AddField(
            model_name="proyectoinvestigacion",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="proyectoinvestigacion",
            name="objetivos_ods",
            field=models.ManyToManyField(
                blank=True,
                to="investigacion.objetivodesarrollosostenible",
                verbose_name="objetivos de desarrollo sostenible",
            ),
        ),
        migrations.AddField(
            model_name="proyectoinvestigacion",
            name="participantes",
            field=models.ManyToManyField(
                blank=True, related_name="proyectos_participante", to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="mapaarbitrado",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="investigacion.proyectoinvestigacion",
            ),
        ),
        migrations.AddField(
            model_name="articulocientifico",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="investigacion.proyectoinvestigacion",
            ),
        ),
        migrations.AddField(
            model_name="apoyotecnico",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="investigacion.proyectoinvestigacion",
            ),
        ),
        migrations.AddField(
            model_name="proyectoresponsable",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="proyectoresponsable",
            name="proyecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="investigacion.proyectoinvestigacion",
            ),
        ),
        migrations.AddField(
            model_name="proyectoinvestigacion",
            name="responsables",
            field=models.ManyToManyField(
                related_name="proyectos_responsable",
                through="investigacion.ProyectoResponsable",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="publicaciontecnica",
            name="institucion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="publicaciontecnica",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="investigacion.proyectoinvestigacion",
            ),
        ),
        migrations.AddField(
            model_name="publicaciontecnicaautor",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="publicaciontecnicaautor",
            name="publicacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="investigacion.publicaciontecnica",
            ),
        ),
        migrations.AddField(
            model_name="publicaciontecnica",
            name="autores",
            field=models.ManyToManyField(
                related_name="publicaciones_tecnicas",
                through="investigacion.PublicacionTecnicaAutor",
                to="nucleo.persona",
            ),
        ),
        migrations.AddConstraint(
            model_name="articulocientificoautor",
            constraint=models.UniqueConstraint(
                fields=("articulo", "persona"), name="articulo_cientifico_autor_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="capitulolibroinvestigacionautor",
            constraint=models.UniqueConstraint(
                fields=("capitulo", "persona"),
                name="capitulo_investigacion_autor_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="capitulolibroinvestigacion",
            constraint=models.UniqueConstraint(
                fields=("titulo", "libro"), name="capitulo_investigacion_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="mapaarbitradoautor",
            constraint=models.UniqueConstraint(
                fields=("mapa", "persona"), name="mapa_autor_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="proyectoresponsable",
            constraint=models.UniqueConstraint(
                fields=("proyecto", "persona"), name="proyecto_responsable_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicaciontecnicaautor",
            constraint=models.UniqueConstraint(
                fields=("publicacion", "persona"),
                name="publicacion_tecnica_autor_unico",
            ),
        ),
    ]
