# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0002_auto_20171102_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulolibroinvestigacion',
            name='proyecto',
        ),
    ]
