# Generated by Django 2.0.2 on 2018-02-05 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0002_auto_20180204_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informetecnico',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='investigacion.ProyectoInvestigacion'),
            preserve_default=False,
        ),
    ]
