# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0002_auto_20171009_1652'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proyectoinvestigacion',
            unique_together=set([('financiamiento_conacyt', 'financiamiento_papiit')]),
        ),
    ]
