# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0002_auto_20170920_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulocientifico',
            name='id_doi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articulocientifico',
            name='id_wos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
