# Generated by Django 2.0.5 on 2018-05-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0002_auto_20180503_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulocientifico',
            name='indices',
        ),
        migrations.RemoveField(
            model_name='articulocientifico',
            name='tipo',
        ),
        migrations.AddField(
            model_name='articulocientifico',
            name='factor_impacto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
