# Generated by Django 6.1.1 on 2026-09-26 18:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigacion", "0002_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulocientifico",
            name="agradecimientos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Académicos de la entidad mencionados en los agradecimientos.",
                related_name="articulos_cientificos_agradecimiento",
                to="nucleo.persona",
            ),
        ),
        migrations.AlterField(
            model_name="articulocientifico",
            name="alumnos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Coautores que eran estudiantes al momento de publicar.",
                related_name="articulos_cientificos_alumno",
                to="nucleo.persona",
            ),
        ),
        migrations.AlterField(
            model_name="articulocientifico",
            name="factor_impacto",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Histórico capturado en el artículo. Si está vacío se usa el registrado en la revista para el año.",
                max_digits=6,
                null=True,
                verbose_name="factor de impacto",
            ),
        ),
        migrations.AlterField(
            model_name="articulocientifico",
            name="solo_electronico",
            field=models.BooleanField(
                default=False,
                help_text="El artículo solo se publicó en formato electrónico.",
                verbose_name="solo electrónico",
            ),
        ),
        migrations.AlterField(
            model_name="proyectoinvestigacion",
            name="es_permanente",
            field=models.BooleanField(
                default=False,
                help_text="Proyecto sin término previsto (p. ej. un observatorio o laboratorio).",
                verbose_name="es permanente",
            ),
        ),
        migrations.AlterField(
            model_name="proyectoinvestigacion",
            name="financiamiento_clave",
            field=models.CharField(
                blank=True,
                help_text="Obligatoria para proyectos CONAHCYT, PAPIIT y PAPIME.",
                max_length=30,
                verbose_name="clave del financiamiento",
            ),
        ),
        migrations.AlterField(
            model_name="proyectoinvestigacion",
            name="tematica_genero",
            field=models.BooleanField(
                default=False,
                help_text="El proyecto aborda la perspectiva o la temática de género.",
                verbose_name="temática de género",
            ),
        ),
        migrations.AlterField(
            model_name="publicaciontecnica",
            name="es_publico",
            field=models.BooleanField(
                default=False,
                help_text="Cualquier persona puede consultarla (p. ej. en un repositorio abierto).",
                verbose_name="es de acceso público",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalActividadApoyoTecnico",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=160)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INVESTIGACION", "Apoyo a la investigación"),
                            ("SERVICIO", "Apoyo a actividades de servicio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical actividad de apoyo técnico",
                "verbose_name_plural": "historical actividades de apoyo técnico",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalApoyoTecnico",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                (
                    "actividad_otra",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="otra actividad"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "actividad",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investigacion.actividadapoyotecnico",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investigacion.proyectoinvestigacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical apoyo técnico",
                "verbose_name_plural": "historical apoyos técnicos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalArticuloCientifico",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENVIADO", "Enviado"),
                            ("ACEPTADO", "Aceptado"),
                            ("EN_PRENSA", "En prensa"),
                            ("PUBLICADO", "Publicado"),
                        ],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("fecha_enviado", models.DateField(blank=True, null=True)),
                ("fecha_aceptado", models.DateField(blank=True, null=True)),
                (
                    "fecha_enprensa",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha en prensa"
                    ),
                ),
                ("fecha_publicado", models.DateField(blank=True, null=True)),
                (
                    "titulo",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="título"
                    ),
                ),
                ("volumen", models.CharField(blank=True, max_length=100)),
                (
                    "numero",
                    models.CharField(blank=True, max_length=100, verbose_name="número"),
                ),
                (
                    "pagina_inicio",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página inicial"
                    ),
                ),
                (
                    "pagina_fin",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página final"
                    ),
                ),
                (
                    "doi",
                    models.CharField(blank=True, max_length=100, verbose_name="DOI"),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "solo_electronico",
                    models.BooleanField(
                        default=False,
                        help_text="El artículo solo se publicó en formato electrónico.",
                        verbose_name="solo electrónico",
                    ),
                ),
                (
                    "factor_impacto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Histórico capturado en el artículo. Si está vacío se usa el registrado en la revista para el año.",
                        max_digits=6,
                        null=True,
                        verbose_name="factor de impacto",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investigacion.proyectoinvestigacion",
                    ),
                ),
                (
                    "revista",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.revista",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical artículo científico",
                "verbose_name_plural": "historical artículos científicos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalArticuloCientificoAutor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investigacion.articulocientifico",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical autor",
                "verbose_name_plural": "historical autores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCapituloLibroInvestigacion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="título")),
                (
                    "pagina_inicio",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página inicial"
                    ),
                ),
                (
                    "pagina_fin",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página final"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.libro",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical capítulo en libro de investigación",
                "verbose_name_plural": "historical capítulos en libros de investigación",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCapituloLibroInvestigacionAutor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "capitulo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investigacion.capitulolibroinvestigacion",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical autor",
                "verbose_name_plural": "historical autores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMapaArbitrado",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENVIADO", "Enviado"),
                            ("ACEPTADO", "Aceptado"),
                            ("EN_PRENSA", "En prensa"),
                            ("PUBLICADO", "Publicado"),
                        ],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("fecha_enviado", models.DateField(blank=True, null=True)),
                ("fecha_aceptado", models.DateField(blank=True, null=True)),
                (
                    "fecha_enprensa",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha en prensa"
                    ),
                ),
                ("fecha_publicado", models.DateField(blank=True, null=True)),
                (
                    "titulo",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="título"
                    ),
                ),
                (
                    "publicacion",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="publicación o editorial",
                    ),
                ),
                ("ciudad", models.CharField(blank=True, max_length=255)),
                (
                    "numero_paginas",
                    models.PositiveIntegerField(
                        default=1, verbose_name="número de páginas"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.pais",
                        verbose_name="país",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investigacion.proyectoinvestigacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical mapa arbitrado",
                "verbose_name_plural": "historical mapas arbitrados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMapaArbitradoAutor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investigacion.mapaarbitrado",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical autor",
                "verbose_name_plural": "historical autores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalObjetivoDesarrolloSostenible",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        db_index=True, verbose_name="número"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical objetivo de desarrollo sostenible",
                "verbose_name_plural": "historical objetivos de desarrollo sostenible",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProyectoInvestigacion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "es_permanente",
                    models.BooleanField(
                        default=False,
                        help_text="Proyecto sin término previsto (p. ej. un observatorio o laboratorio).",
                        verbose_name="es permanente",
                    ),
                ),
                (
                    "participantes_externos",
                    models.TextField(
                        blank=True,
                        help_text="Participantes que no están registrados como personas.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NUEVO", "Nuevo"),
                            ("EN_PROCESO", "En proceso"),
                            ("CONCLUIDO", "Concluido"),
                        ],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        choices=[
                            ("BASICO", "Ciencia básica"),
                            ("APLICADO", "Investigación aplicada"),
                            ("DESARROLLO_TECNOLOGICO", "Desarrollo tecnológico"),
                            ("INNOVACION", "Innovación"),
                            ("INVESTIGACION_FRONTERA", "Investigación de frontera"),
                        ],
                        max_length=30,
                        verbose_name="clasificación",
                    ),
                ),
                (
                    "organizacion",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("COLECTIVO", "Colectivo"),
                        ],
                        max_length=20,
                        verbose_name="organización",
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("DISCIPLINARIO", "Disciplinario"),
                            ("MULTIDISCIPLINARIO", "Multidisciplinario"),
                            ("INTERDISCIPLINARIO", "Interdisciplinario"),
                            ("TRANSDISCIPLINARIO", "Transdisciplinario"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tematica_genero",
                    models.BooleanField(
                        default=False,
                        help_text="El proyecto aborda la perspectiva o la temática de género.",
                        verbose_name="temática de género",
                    ),
                ),
                ("impacto_social", models.CharField(blank=True, max_length=255)),
                (
                    "financiamiento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONACYT", "CONAHCYT"),
                            ("PAPIIT", "DGAPA-PAPIIT"),
                            ("PAPIME", "DGAPA-PAPIME"),
                            ("EXTRAORDINARIOS", "Ingresos extraordinarios"),
                            (
                                "SIN_RECURSOS",
                                "Sin recursos propios (en colaboración con otras dependencias)",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "financiamiento_clave",
                    models.CharField(
                        blank=True,
                        help_text="Obligatoria para proyectos CONAHCYT, PAPIIT y PAPIME.",
                        max_length=30,
                        verbose_name="clave del financiamiento",
                    ),
                ),
                (
                    "financiamiento_convocatoria",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="convocatoria"
                    ),
                ),
                (
                    "num_alumnos_licenciatura",
                    models.PositiveIntegerField(
                        default=0, verbose_name="alumnos de licenciatura"
                    ),
                ),
                (
                    "num_alumnos_maestria",
                    models.PositiveIntegerField(
                        default=0, verbose_name="alumnos de maestría"
                    ),
                ),
                (
                    "num_alumnos_doctorado",
                    models.PositiveIntegerField(
                        default=0, verbose_name="alumnos de doctorado"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "financiamiento_institucion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.institucion",
                        verbose_name="institución que financia o colabora",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.institucion",
                        verbose_name="institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical proyecto de investigación",
                "verbose_name_plural": "historical proyectos de investigación",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProyectoResponsable",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.persona",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investigacion.proyectoinvestigacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical responsable",
                "verbose_name_plural": "historical responsables",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPublicacionTecnica",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENVIADO", "Enviado"),
                            ("ACEPTADO", "Aceptado"),
                            ("EN_PRENSA", "En prensa"),
                            ("PUBLICADO", "Publicado"),
                        ],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("fecha_enviado", models.DateField(blank=True, null=True)),
                ("fecha_aceptado", models.DateField(blank=True, null=True)),
                (
                    "fecha_enprensa",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha en prensa"
                    ),
                ),
                ("fecha_publicado", models.DateField(blank=True, null=True)),
                (
                    "titulo",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="título"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "DESARROLLO_TECNOLOGICO",
                                "Desarrollo tecnológico terminado",
                            ),
                            (
                                "PROGRAMA_COMPUTO",
                                "Programa de cómputo especializado documentado",
                            ),
                            (
                                "BASE_DATOS",
                                "Base de datos geográficos arbitrada por expertos para aplicaciones web",
                            ),
                            ("NORMA_PATENTE", "Norma o patente"),
                            (
                                "INFORME_TECNICO",
                                "Informe técnico final dirigido a tomadores de decisiones",
                            ),
                            (
                                "PLAN_MANEJO",
                                "Plan de manejo, ordenamiento o gestión territorial reconocido oficialmente",
                            ),
                            (
                                "CARTA_REVISTA",
                                "Carta en revista de prestigio internacional",
                            ),
                            ("TRADUCCION", "Traducción de libro o revisión técnica"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "es_publico",
                    models.BooleanField(
                        default=False,
                        help_text="Cualquier persona puede consultarla (p. ej. en un repositorio abierto).",
                        verbose_name="es de acceso público",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                ("cita", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investigacion.proyectoinvestigacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical publicación técnica",
                "verbose_name_plural": "historical publicaciones técnicas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPublicacionTecnicaAutor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.persona",
                    ),
                ),
                (
                    "publicacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investigacion.publicaciontecnica",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical autor",
                "verbose_name_plural": "historical autores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
