# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 01:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigacion', '0002_auto_20170925_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulolibroinvestigacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='capitulolibroinvestigacion',
            name='usuarios',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='capitulo_libro_investigacion_autores', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
    ]
