# Generated by Django 2.0.2 on 2018-02-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0003_auto_20180204_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='informetecnico',
            name='es_publico',
            field=models.BooleanField(default=False),
        ),
    ]
