# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0003_auto_20170922_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulocientifico',
            name='indices',
            field=models.ManyToManyField(blank=True, null=True, related_name='articulo_cientifico_indices', to='nucleo.Indice'),
        ),
        migrations.AlterField(
            model_name='articulocientifico',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articulocientifico',
            name='volumen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
