# Generated by Django 6.1.1 on 2026-09-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0005_paises_cities_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyotecnico',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalapoyotecnico',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalproyectoinvestigacion',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='proyectoinvestigacion',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
    ]
