# Generated by Django 6.1.1 on 2026-10-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0008_fechas_obligatorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproyectoinvestigacion',
            name='financiamiento_externo',
            field=models.CharField(blank=True, choices=[('FEDERAL', 'Gubernamental federal'), ('ESTATAL', 'Gubernamental estatal'), ('MUNICIPAL', 'Gubernamental municipal'), ('EXTRANJERO', 'Recursos del extranjero'), ('PRIVADO', 'Privado'), ('PRIVADO_NO_LUCRATIVO', 'Privado no lucrativo')], max_length=30),
        ),
        migrations.AddField(
            model_name='historicalproyectoinvestigacion',
            name='financiamiento_unam',
            field=models.CharField(blank=True, choices=[('CONCURSADO', 'Presupuesto concursado por la entidad'), ('FUERA', 'Gestionado fuera de la entidad'), ('AUTOGENERADOS', 'Recursos autogenerados (extraordinarios)')], max_length=20, verbose_name='financiamiento UNAM'),
        ),
        migrations.AddField(
            model_name='historicalproyectoinvestigacion',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('AGENTES_TOXICOS', 'Agentes tóxicos y procesos contaminantes'), ('AGUA', 'Agua'), ('CULTURA', 'Cultura'), ('EDUCACION', 'Educación'), ('ENERGIA', 'Energía y cambio climático'), ('SALUD', 'Salud'), ('SEGURIDAD', 'Seguridad humana'), ('SOCIOECOLOGICOS', 'Sistemas socioecológicos y sustentabilidad'), ('SOBERANIA_ALIMENTARIA', 'Soberanía alimentaria'), ('VIVIENDA', 'Vivienda')], max_length=30, verbose_name='prioridad estratégica nacional'),
        ),
        migrations.AddField(
            model_name='proyectoinvestigacion',
            name='financiamiento_externo',
            field=models.CharField(blank=True, choices=[('FEDERAL', 'Gubernamental federal'), ('ESTATAL', 'Gubernamental estatal'), ('MUNICIPAL', 'Gubernamental municipal'), ('EXTRANJERO', 'Recursos del extranjero'), ('PRIVADO', 'Privado'), ('PRIVADO_NO_LUCRATIVO', 'Privado no lucrativo')], max_length=30),
        ),
        migrations.AddField(
            model_name='proyectoinvestigacion',
            name='financiamiento_unam',
            field=models.CharField(blank=True, choices=[('CONCURSADO', 'Presupuesto concursado por la entidad'), ('FUERA', 'Gestionado fuera de la entidad'), ('AUTOGENERADOS', 'Recursos autogenerados (extraordinarios)')], max_length=20, verbose_name='financiamiento UNAM'),
        ),
        migrations.AddField(
            model_name='proyectoinvestigacion',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('AGENTES_TOXICOS', 'Agentes tóxicos y procesos contaminantes'), ('AGUA', 'Agua'), ('CULTURA', 'Cultura'), ('EDUCACION', 'Educación'), ('ENERGIA', 'Energía y cambio climático'), ('SALUD', 'Salud'), ('SEGURIDAD', 'Seguridad humana'), ('SOCIOECOLOGICOS', 'Sistemas socioecológicos y sustentabilidad'), ('SOBERANIA_ALIMENTARIA', 'Soberanía alimentaria'), ('VIVIENDA', 'Vivienda')], max_length=30, verbose_name='prioridad estratégica nacional'),
        ),
        migrations.AlterField(
            model_name='historicalproyectoinvestigacion',
            name='financiamiento',
            field=models.CharField(blank=True, choices=[('CONACYT', 'SECIHTI (antes CONAHCYT)'), ('PAPIIT', 'DGAPA-PAPIIT'), ('PAPIME', 'DGAPA-PAPIME'), ('EXTRAORDINARIOS', 'Ingresos extraordinarios'), ('SIN_RECURSOS', 'Sin recursos propios (en colaboración con otras dependencias)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpublicaciontecnica',
            name='tipo',
            field=models.CharField(choices=[('DESARROLLO_TECNOLOGICO', 'Desarrollo tecnológico terminado'), ('PROGRAMA_COMPUTO', 'Programa de cómputo especializado documentado'), ('BASE_DATOS', 'Base de datos geográficos arbitrada por expertos para aplicaciones web'), ('NORMA_PATENTE', 'Norma o patente'), ('INFORME_TECNICO', 'Informe técnico final dirigido a tomadores de decisiones'), ('PLAN_MANEJO', 'Plan de manejo, ordenamiento o gestión territorial reconocido oficialmente'), ('RESENA', 'Reseña'), ('CARTA_REVISTA', 'Carta en revista de prestigio internacional'), ('TRADUCCION', 'Traducción de libro o revisión técnica')], max_length=30),
        ),
        migrations.AlterField(
            model_name='proyectoinvestigacion',
            name='financiamiento',
            field=models.CharField(blank=True, choices=[('CONACYT', 'SECIHTI (antes CONAHCYT)'), ('PAPIIT', 'DGAPA-PAPIIT'), ('PAPIME', 'DGAPA-PAPIME'), ('EXTRAORDINARIOS', 'Ingresos extraordinarios'), ('SIN_RECURSOS', 'Sin recursos propios (en colaboración con otras dependencias)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='publicaciontecnica',
            name='tipo',
            field=models.CharField(choices=[('DESARROLLO_TECNOLOGICO', 'Desarrollo tecnológico terminado'), ('PROGRAMA_COMPUTO', 'Programa de cómputo especializado documentado'), ('BASE_DATOS', 'Base de datos geográficos arbitrada por expertos para aplicaciones web'), ('NORMA_PATENTE', 'Norma o patente'), ('INFORME_TECNICO', 'Informe técnico final dirigido a tomadores de decisiones'), ('PLAN_MANEJO', 'Plan de manejo, ordenamiento o gestión territorial reconocido oficialmente'), ('RESENA', 'Reseña'), ('CARTA_REVISTA', 'Carta en revista de prestigio internacional'), ('TRADUCCION', 'Traducción de libro o revisión técnica')], max_length=30),
        ),
    ]
