# Generated by Django 6.1.1 on 2026-10-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigacion", "0009_financiamiento_y_prioridad"),
        ("nucleo", "0037_capitulos_traspaso"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="capitulolibroinvestigacion",
            name="capitulo_investigacion_unico",
        ),
        migrations.RemoveField(
            model_name="historicalcapitulolibroinvestigacionautor",
            name="capitulo",
        ),
        migrations.RemoveConstraint(
            model_name="capitulolibroinvestigacionautor",
            name="capitulo_investigacion_autor_unico",
        ),
        migrations.RemoveField(
            model_name="historicalcapitulolibroinvestigacionautor",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalcapitulolibroinvestigacionautor",
            name="persona",
        ),
        migrations.RemoveField(
            model_name="capitulolibroinvestigacion",
            name="autores",
        ),
        migrations.RemoveField(
            model_name="capitulolibroinvestigacion",
            name="libro",
        ),
        migrations.RemoveField(
            model_name="capitulolibroinvestigacionautor",
            name="capitulo",
        ),
        migrations.RemoveField(
            model_name="capitulolibroinvestigacionautor",
            name="persona",
        ),
        migrations.DeleteModel(
            name="HistoricalCapituloLibroInvestigacion",
        ),
        migrations.DeleteModel(
            name="HistoricalCapituloLibroInvestigacionAutor",
        ),
        migrations.DeleteModel(
            name="CapituloLibroInvestigacion",
        ),
        migrations.DeleteModel(
            name="CapituloLibroInvestigacionAutor",
        ),
    ]
