# Generated by Django 2.0.6 on 2018-11-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0010_auto_20181105_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectoinvestigacion',
            name='institucion',
        ),
    ]
