# Generated by Django 6.1.1 on 2026-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovilidadAcademica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INVITACION", "Académico invitado"),
                            ("ESTANCIA", "Estancia académica"),
                            ("SABATICO", "Sabático"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "academico",
                    models.CharField(
                        max_length=255, verbose_name="académico invitado o anfitrión"
                    ),
                ),
                ("actividades", models.TextField()),
                (
                    "intercambio_unam",
                    models.BooleanField(default=False, verbose_name="intercambio UNAM"),
                ),
                (
                    "financiamiento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PROGRAMAS_UNAM", "Programas UNAM"),
                            ("POR_PROYECTO", "Por proyecto"),
                            ("PRESUPUESTO_OPERATIVO", "Presupuesto operativo"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "movilidad académica",
                "verbose_name_plural": "movilidad académica",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
