# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movilidad_academica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vinculacion', '0001_initial'),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='financiamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Financiamiento'),
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='proyectos_investigacion',
            field=models.ManyToManyField(blank=True, related_name='vinculacion_proyectos_investigacion', to='nucleo.Proyecto'),
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='redes_academicas',
            field=models.ManyToManyField(blank=True, related_name='vinculacion_redes_academicas', to='vinculacion.RedAcademica'),
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculacion_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='dependencia_procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='financiamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Financiamiento'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='invitado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitado',
            name='proyectos_investigacion',
            field=models.ManyToManyField(blank=True, related_name='invitado_proyectos_investigacion', to='nucleo.Proyecto'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='redes_academicas',
            field=models.ManyToManyField(blank=True, related_name='invitado_redes_academicas', to='vinculacion.RedAcademica'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitado_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='estanciacolaboracion',
            name='academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estanciacolaboracion',
            name='dependencia_visitada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='estanciacolaboracion',
            name='financiamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Financiamiento'),
        ),
        migrations.AddField(
            model_name='estanciacolaboracion',
            name='proyectos_investigacion',
            field=models.ManyToManyField(blank=True, related_name='estancia_colaboracion_investigacion', to='nucleo.Proyecto'),
        ),
        migrations.AddField(
            model_name='estanciacolaboracion',
            name='redes_academicas',
            field=models.ManyToManyField(blank=True, related_name='estancia_colaboracion_academicas', to='vinculacion.RedAcademica'),
        ),
        migrations.AddField(
            model_name='estanciacolaboracion',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estancia_tags', to='nucleo.Tag'),
        ),
    ]
