# Generated by Django 6.1.1 on 2026-09-26 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("investigacion", "0002_initial"),
        ("movilidad_academica", "0001_initial"),
        ("nucleo", "0001_initial"),
        ("vinculacion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movilidadacademica",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="movilidadacademica",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="investigacion.proyectoinvestigacion",
            ),
        ),
        migrations.AddField(
            model_name="movilidadacademica",
            name="redes_academicas",
            field=models.ManyToManyField(
                blank=True,
                to="vinculacion.redacademica",
                verbose_name="redes académicas",
            ),
        ),
        migrations.AddField(
            model_name="movilidadacademica",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movilidades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
