# Generated by Django 2.0.6 on 2018-11-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movilidad_academica', '0003_estanciamovilidad_invitadomovilidad_sabaticomovilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movilidadacademica',
            name='institucion',
        ),
    ]
