# Generated by Django 2.0.6 on 2018-12-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilidad_academica', '0005_movilidadacademica_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitadomovilidad',
            name='proyecto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
