# Generated by Django 6.1.1 on 2026-10-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilidad_academica', '0006_fechas_obligatorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovilidadacademica',
            name='visitante',
            field=models.BooleanField(default=False, help_text='Marca si la persona viene de otra institución a la entidad (no si es del personal).'),
        ),
        migrations.AddField(
            model_name='movilidadacademica',
            name='visitante',
            field=models.BooleanField(default=False, help_text='Marca si la persona viene de otra institución a la entidad (no si es del personal).'),
        ),
    ]
