# Generated by Django 6.1.1 on 2026-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CapacidadPotencialidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="capacidad o potencialidad"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
            ],
            options={
                "verbose_name": "capacidad o potencialidad",
                "verbose_name_plural": "capacidades y potencialidades",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ExperienciaProfesional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                ("cargo", models.CharField(max_length=254)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "experiencia profesional",
                "verbose_name_plural": "experiencias profesionales",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="LineaInvestigacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="línea de investigación"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
            ],
            options={
                "verbose_name": "línea de investigación",
                "verbose_name_plural": "líneas de investigación",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
