# Generated by Django 6.1.1 on 2026-09-26 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("experiencia_profesional", "0001_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="capacidadpotencialidad",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="capacidades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="experienciaprofesional",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="experienciaprofesional",
            name="nombramiento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.nombramiento",
            ),
        ),
        migrations.AddField(
            model_name="experienciaprofesional",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="experiencias",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lineainvestigacion",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="lineainvestigacion",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lineas_investigacion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="capacidadpotencialidad",
            constraint=models.UniqueConstraint(
                fields=("usuario", "nombre"), name="capacidad_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="lineainvestigacion",
            constraint=models.UniqueConstraint(
                fields=("usuario", "nombre"), name="linea_investigacion_unica"
            ),
        ),
    ]
