p_investigadores_asocA_tmp = round(p_investigadores_asocA_tmp / p_investigadores_count * 100, 2)
p_investigadores_asocB_tmp = round(p_investigadores_asocB_tmp / p_investigadores_count * 100, 2)
p_investigadores_asocB_tmp = round(p_investigadores_asocB_tmp / p_investigadores_count * 100, 2)
p_investigadores_asocA_tcp = round(p_investigadores_asocA_tcp / p_investigadores_count * 100, 2)
p_investigadores_asocB_tcp = round(p_investigadores_asocB_tcp / p_investigadores_count * 100, 2)
p_investigadores_asocC_tcp = round(p_investigadores_asocC_tcp / p_investigadores_count * 100, 2)

p_investigadores_titA_tmp = round(p_investigadores_titA_tmp / p_investigadores_count* 100, 2)
p_investigadores_titB_tmp = round(p_investigadores_titB_tmp / p_investigadores_count* 100, 2)
p_investigadores_titC_tmp = round(p_investigadores_titC_tmp / p_investigadores_count* 100, 2)
p_investigadores_titA_tcp = round(p_investigadores_titA_tcp / p_investigadores_count* 100, 2)
p_investigadores_titB_tcp = round(p_investigadores_titB_tcp / p_investigadores_count* 100, 2)
p_investigadores_titC_tcp = round(p_investigadores_titC_tcp / p_investigadores_count* 100, 2)

p_tecnicos_auxA_tmp = round(p_tecnicos_auxA_tmp / p_tecnicos_count * 100, 2)
p_tecnicos_auxB_tmp = round(p_tecnicos_auxB_tmp / p_tecnicos_count * 100, 2)
p_tecnicos_auxC_tmp = round(p_tecnicos_auxC_tmp / p_tecnicos_count * 100, 2)
p_tecnicos_auxA_tcp = round(p_tecnicos_auxA_tcp / p_tecnicos_count * 100, 2)
p_tecnicos_auxB_tcp = round(p_tecnicos_auxB_tcp / p_tecnicos_count * 100, 2)
p_tecnicos_auxC_tcp = round(p_tecnicos_auxC_tcp / p_tecnicos_count * 100, 2)

p_tecnicos_asocA_tmp = round(p_tecnicos_asocA_tmp / p_tecnicos_count * 100, 2)
p_tecnicos_asocB_tmp = round(p_tecnicos_asocB_tmp / p_tecnicos_count * 100, 2)
p_tecnicos_asocC_tmp = round(p_tecnicos_asocC_tmp / p_tecnicos_count * 100, 2)
p_tecnicos_asocA_tcp = round(p_tecnicos_asocA_tcp / p_tecnicos_count * 100, 2)
p_tecnicos_asocB_tcp = round(p_tecnicos_asocB_tcp / p_tecnicos_count * 100, 2)
p_tecnicos_asocC_tcp = round(p_tecnicos_asocC_tcp / p_tecnicos_count * 100, 2)

p_tecnicos_titA_tmp = round(p_tecnicos_titA_tmp / p_tecnicos_count * 100, 2)
p_tecnicos_titB_tmp = round(p_tecnicos_titB_tmp / p_tecnicos_count * 100, 2)
p_tecnicos_titC_tmp = round(p_tecnicos_titC_tmp / p_tecnicos_count * 100, 2)
p_tecnicos_titA_tcp = round(p_tecnicos_titA_tcp / p_tecnicos_count * 100, 2)
p_tecnicos_titB_tcp = round(p_tecnicos_titB_tcp / p_tecnicos_count * 100, 2)
p_tecnicos_titC_tcp = round(p_tecnicos_titC_tcp / p_tecnicos_count * 100, 2)


investigadores_asocA_tmp = round(investigadores_asocA_tmp / investigadores_count * 100, 2)
investigadores_asocB_tmp = round(investigadores_asocB_tmp / investigadores_count * 100, 2)
investigadores_asocC_tmp = round(investigadores_asocC_tmp / investigadores_count * 100, 2)
investigadores_asocA_tcp = round(investigadores_asocA_tcp / investigadores_count * 100, 2)
investigadores_asocB_tcp = round(investigadores_asocB_tcp / investigadores_count * 100, 2)
investigadores_asocC_tcp = round(investigadores_asocC_tcp / investigadores_count * 100, 2)

investigadores_titA_tmp = round(investigadores_titA_tmp / investigadores_count * 100, 2)
investigadores_titB_tmp = round(investigadores_titB_tmp / investigadores_count * 100, 2)
investigadores_titC_tmp = round(investigadores_titC_tmp / investigadores_count * 100, 2)
investigadores_titA_tcp = round(investigadores_titA_tcp / investigadores_count * 100, 2)
investigadores_titB_tcp = round(investigadores_titB_tcp / investigadores_count * 100, 2)
investigadores_titC_tcp = round(investigadores_titC_tcp / investigadores_count * 100, 2)

tecnicos_auxA_tmp = round(tecnicos_auxA_tmp / tecnicos_count * 100, 2)
tecnicos_auxB_tmp = round(tecnicos_auxB_tmp / tecnicos_count * 100, 2)
tecnicos_auxC_tmp = round(tecnicos_auxC_tmp / tecnicos_count * 100, 2)
tecnicos_auxA_tcp = round(tecnicos_auxA_tcp / tecnicos_count * 100, 2)
tecnicos_auxB_tcp = round(tecnicos_auxB_tcp / tecnicos_count * 100, 2)
tecnicos_auxC_tcp = round(tecnicos_auxC_tcp / tecnicos_count * 100, 2)

tecnicos_asocA_tmp = round(tecnicos_asocA_tmp / tecnicos_count * 100, 2)
tecnicos_asocB_tmp = round(tecnicos_asocB_tmp / tecnicos_count * 100, 2)
tecnicos_asocC_tmp = round(tecnicos_asocC_tmp / tecnicos_count * 100, 2)
tecnicos_asocA_tcp = round(tecnicos_asocA_tcp / tecnicos_count * 100, 2)
tecnicos_asocB_tcp = round(tecnicos_asocB_tcp / tecnicos_count * 100, 2)
tecnicos_asocC_tcp = round(tecnicos_asocC_tcp / tecnicos_count * 100, 2)

tecnicos_titA_tmp = round(tecnicos_titA_tmp / tecnicos_count * 100, 2)
tecnicos_titB_tmp = round(tecnicos_titB_tmp / tecnicos_count * 100, 2)
tecnicos_titC_tmp = round(tecnicos_titC_tmp / tecnicos_count * 100, 2)
tecnicos_titA_tcp = round(tecnicos_titA_tcp / tecnicos_count * 100, 2)
tecnicos_titB_tcp = round(tecnicos_titB_tcp / tecnicos_count * 100, 2)
tecnicos_titC_tcp = round(tecnicos_titC_tcp / tecnicos_count * 100, 2)
