p_investigadores_asocA_tm
p_investigadores_asocB_tm
p_investigadores_asocC_tm
p_investigadores_asocA_tc
p_investigadores_asocB_tc
p_investigadores_asocC_tc

p_investigadores_titA_tm
p_investigadores_titB_tm
p_investigadores_titC_tm
p_investigadores_titA_tc
p_investigadores_titB_tc
p_investigadores_titC_tc

p_tecnicos_auxA_tm
p_tecnicos_auxB_tm
p_tecnicos_auxC_tm
p_tecnicos_auxA_tc
p_tecnicos_auxB_tc
p_tecnicos_auxC_tc

p_tecnicos_asocA_tm
p_tecnicos_asocB_tm
p_tecnicos_asocC_tm
p_tecnicos_asocA_tc
p_tecnicos_asocB_tc
p_tecnicos_asocC_tc

p_tecnicos_titA_tm
p_tecnicos_titB_tm
p_tecnicos_titC_tm
p_tecnicos_titA_tc
p_tecnicos_titB_tc
p_tecnicos_titC_tc


investigadores_asocA_tm
investigadores_asocB_tm
investigadores_asocC_tm
investigadores_asocA_tc
investigadores_asocB_tc
investigadores_asocC_tc

investigadores_titA_tm
investigadores_titB_tm
investigadores_titC_tm
investigadores_titA_tc
investigadores_titB_tc
investigadores_titC_tc

tecnicos_auxA_tm
tecnicos_auxB_tm
tecnicos_auxC_tm
tecnicos_auxA_tc
tecnicos_auxB_tc
tecnicos_auxC_tc

tecnicos_asocA_tm
tecnicos_asocB_tm
tecnicos_asocC_tm
tecnicos_asocA_tc
tecnicos_asocB_tc
tecnicos_asocC_tc

tecnicos_titA_tm
tecnicos_titB_tm
tecnicos_titC_tm
tecnicos_titA_tc
tecnicos_titB_tc
tecnicos_titC_tc
