# Generated by Django 6.1.1 on 2026-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CursoEspecializacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=255, verbose_name="nombre del curso"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CURSO", "Curso"),
                            ("DIPLOMADO", "Diplomado"),
                            ("CERTIFICACION", "Certificación"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("horas", models.PositiveIntegerField(verbose_name="número de horas")),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("PRESENCIAL", "Presencial"),
                            ("EN_LINEA", "En línea"),
                            ("MIXTO", "Mixto"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "curso de especialización",
                "verbose_name_plural": "cursos de especialización",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Grado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("LICENCIATURA", "Licenciatura"),
                            ("MAESTRIA", "Maestría"),
                            ("DOCTORADO", "Doctorado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "titulo_obtenido",
                    models.CharField(max_length=255, verbose_name="título obtenido"),
                ),
                (
                    "titulo_tesis",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="título de la tesis"
                    ),
                ),
                (
                    "fecha_grado",
                    models.DateField(verbose_name="fecha de obtención del grado"),
                ),
                (
                    "distincion_obtenida",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="distinción obtenida"
                    ),
                ),
            ],
            options={
                "verbose_name": "grado académico",
                "verbose_name_plural": "grados académicos",
                "ordering": ["-fecha_grado"],
            },
        ),
        migrations.CreateModel(
            name="Postdoctorado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                (
                    "titulo_proyecto",
                    models.CharField(
                        max_length=255, verbose_name="título del proyecto"
                    ),
                ),
                (
                    "financiamiento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONACYT", "CONAHCYT"),
                            ("SRE", "SRE"),
                            ("DGAPA", "DGAPA"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "financiamiento_otro",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="otra entidad de financiamiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "postdoctorado",
                "verbose_name_plural": "postdoctorados",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
