# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 01:24
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoEspecializacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=255, verbose_name='Nombre del curso')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre_curso', unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('CURSO', 'Curso'), ('DIPLOMADO', 'Diplomado'), ('CERTIFICACION', 'Certificación'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de curso')),
                ('horas', models.PositiveIntegerField(verbose_name='Número de horas')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('EN_LINEA', 'En línea'), ('MIXTO', 'Mixto'), ('OTRO', 'Otro')], max_length=20)),
                ('area_conocimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.AreaConocimiento', verbose_name='Área de conocimiento')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia')),
                ('tags', models.ManyToManyField(blank=True, related_name='curso_especializacion_tags', to='nucleo.Tag')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_especializacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso de especialización',
                'ordering': ['fecha_inicio'],
                'verbose_name_plural': 'Cursos de especialización',
            },
        ),
        migrations.CreateModel(
            name='Doctorado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripición')),
                ('titulo_tesis', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo_tesis', unique=True)),
                ('tesis_url', models.URLField(blank=True)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio de doctorado')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de terminación de doctorado')),
                ('fecha_grado', models.DateField(blank=True, verbose_name='Fecha de obtención de grado de doctorado')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaDoctorado')),
                ('tags', models.ManyToManyField(blank=True, related_name='doctorado_tags', to='nucleo.Tag')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_grado', 'dependencia', 'titulo_tesis'],
            },
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripición')),
                ('titulo_tesis', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo_tesis', unique=True)),
                ('tesis_url', models.URLField(blank=True)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio de licenciatura')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de terminación de licenciatura')),
                ('fecha_grado', models.DateField(verbose_name='Fecha de obtención de grado licenciatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaLicenciatura')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia')),
                ('tags', models.ManyToManyField(blank=True, related_name='licenciatura_tags', to='nucleo.Tag')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenciaturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dependencia', 'carrera', 'titulo_tesis'],
            },
        ),
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripición')),
                ('titulo_tesis', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo_tesis', unique=True)),
                ('tesis_url', models.URLField(blank=True)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio de maestría')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de terminación de maestría')),
                ('fecha_grado', models.DateField(verbose_name='Fecha de obtención de grado de maestría')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaMaestria')),
                ('tags', models.ManyToManyField(blank=True, related_name='maestria_tags', to='nucleo.Tag')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maestrias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dependencia', 'programa', 'titulo_tesis'],
            },
        ),
        migrations.CreateModel(
            name='PostDoctorado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripición')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio de postdoctorado')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de terminación de postdoctorado')),
                ('area_conocimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postdoctorado_area_conocimiento', to='nucleo.AreaConocimiento', verbose_name='Área de conocimiento')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Proyecto')),
                ('tags', models.ManyToManyField(blank=True, related_name='post_doctorado_tags', to='nucleo.Tag')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postdoctorados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_fin', 'dependencia'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cursoespecializacion',
            unique_together=set([('nombre_curso', 'fecha_inicio', 'usuario')]),
        ),
    ]
