# Generated by Django 6.1.1 on 2026-09-26 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("formacion_academica", "0001_initial"),
        ("investigacion", "0001_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cursoespecializacion",
            name="institucion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="cursoespecializacion",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cursos_especializacion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grado",
            name="institucion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="grado",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postdoctorado",
            name="institucion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="postdoctorado",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="investigacion.proyectoinvestigacion",
            ),
        ),
        migrations.AddField(
            model_name="postdoctorado",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="postdoctorado",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="postdoctorados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="grado",
            constraint=models.UniqueConstraint(
                fields=("usuario", "nivel", "titulo_obtenido"), name="grado_unico"
            ),
        ),
    ]
