# Generated by Django 2.1.7 on 2019-02-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_academica', '0002_auto_20181213_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoespecializacion',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Dependencia'),
        ),
    ]
