# Generated by Django 2.0.6 on 2018-11-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_academica', '0003_auto_20181026_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorado',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='licenciatura',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='maestria',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='postdoctorado',
            name='institucion',
        ),
    ]
