# Generated by Django 6.1.1 on 2026-09-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_academica', '0003_historicalcursoespecializacion_historicalgrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoespecializacion',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalcursoespecializacion',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalpostdoctorado',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='postdoctorado',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
    ]
