# Generated by Django 2.1.7 on 2019-02-16 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20190216_1254'),
        ('formacion_academica', '0003_auto_20190216_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoespecializacion',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.InstitucionSimple'),
        ),
    ]
