# Generated by Django 2.0.6 on 2018-12-05 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0011_auto_20181205_1300'),
        ('formacion_academica', '0004_auto_20181112_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorado',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maestria',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postdoctorado',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
            preserve_default=False,
        ),
    ]
