# Generated by Django 6.1.1 on 2026-09-26 07:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaConocimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("LSBM", "Life Sciences and Biomedicine"),
                            ("PHYS", "Physical Sciences"),
                            ("TECH", "Technology"),
                            ("ARTH", "Arts and Humanities"),
                            ("SS", "Social Sciences"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=4,
                        verbose_name="categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "área de conocimiento",
                "verbose_name_plural": "áreas de conocimiento",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Indice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "índice",
                "verbose_name_plural": "índices",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Nombramiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("clave", models.CharField(max_length=20, unique=True)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=60, unique=True)),
                ("nombre_extendido", models.CharField(blank=True, max_length=200)),
                (
                    "codigo",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="código ISO"
                    ),
                ),
                (
                    "zona",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AMERICA_NORTE", "América del Norte"),
                            ("AMERICA_CENTRAL", "América Central"),
                            ("AMERICA_SUR", "América del Sur"),
                            ("ANTILLAS", "Antillas"),
                            ("EUROPA", "Europa"),
                            ("ASIA", "Asia"),
                            ("EURASIA", "Europa-Asia"),
                            ("AFRICA", "África"),
                            ("OCEANIA", "Oceanía"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "país",
                "verbose_name_plural": "países",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "tipo de evento",
                "verbose_name_plural": "tipos de evento",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INVESTIGADOR", "Investigador"),
                            ("TECNICO", "Técnico académico"),
                            ("POSTDOCTORADO", "Postdoctorado"),
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                    ),
                ),
                (
                    "grado",
                    models.CharField(
                        blank=True,
                        help_text="Por ejemplo: Dr., Mtra., Lic.",
                        max_length=20,
                        verbose_name="grado (abreviatura)",
                    ),
                ),
                ("semblanza", models.TextField(blank=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Femenino"), ("M", "Masculino"), ("O", "Otro")],
                        max_length=1,
                        verbose_name="género",
                    ),
                ),
                (
                    "rfc",
                    models.CharField(blank=True, max_length=13, verbose_name="RFC"),
                ),
                (
                    "curp",
                    models.CharField(blank=True, max_length=18, verbose_name="CURP"),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="dirección")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="teléfono"
                    ),
                ),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("url", models.URLField(blank=True, verbose_name="página web")),
                (
                    "sni",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("C", "Candidato"),
                            ("1", "Nivel I"),
                            ("2", "Nivel II"),
                            ("3", "Nivel III"),
                            ("E", "Emérito"),
                        ],
                        max_length=1,
                        verbose_name="nivel SNII",
                    ),
                ),
                (
                    "pride",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="nivel PRIDE",
                    ),
                ),
                (
                    "ingreso_unam",
                    models.DateField(
                        blank=True, null=True, verbose_name="ingreso a la UNAM"
                    ),
                ),
                (
                    "ingreso_entidad",
                    models.DateField(
                        blank=True, null=True, verbose_name="ingreso a la entidad"
                    ),
                ),
                (
                    "egreso_entidad",
                    models.DateField(
                        blank=True, null=True, verbose_name="egreso de la entidad"
                    ),
                ),
                (
                    "ultimo_contrato",
                    models.DateField(
                        blank=True, null=True, verbose_name="último contrato"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatares"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "pais_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nucleo.pais",
                        verbose_name="país de origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
                "ordering": ["first_name", "last_name"],
                "permissions": [
                    (
                        "ver_todo",
                        "Puede ver y editar los registros de todos los académicos",
                    )
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Beca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=200, unique=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Institucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                ("ciudad", models.CharField(blank=True, max_length=255)),
                (
                    "clasificacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACADEMICA", "Académica"),
                            ("FEDERAL", "Gubernamental federal"),
                            ("ESTATAL", "Gubernamental estatal"),
                            ("MUNICIPAL", "Gubernamental municipal"),
                            ("PRIVADA", "Sector privado"),
                            ("NO_LUCRATIVA", "Sector privado no lucrativo"),
                        ],
                        max_length=20,
                        verbose_name="clasificación",
                    ),
                ),
                (
                    "pertenece_unam",
                    models.BooleanField(
                        default=False, verbose_name="pertenece a la UNAM"
                    ),
                ),
                (
                    "subsistema_unam",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIFUSION_CULTURAL", "Subsistema de Difusión Cultural"),
                            ("ESTUDIOS_POSGRADO", "Subsistema de Estudios de Posgrado"),
                            ("HUMANIDADES", "Subsistema de Humanidades"),
                            (
                                "INVESTIGACION_CIENTIFICA",
                                "Subsistema de Investigación Científica",
                            ),
                            ("ESCUELAS", "Facultades y Escuelas"),
                            ("DESARROLLO_INSTITUCIONAL", "Desarrollo Institucional"),
                        ],
                        max_length=30,
                        verbose_name="subsistema UNAM",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nucleo.pais",
                        verbose_name="país",
                    ),
                ),
            ],
            options={
                "verbose_name": "institución",
                "verbose_name_plural": "instituciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Distincion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PREMIO", "Premio"),
                            ("DISTINCION", "Distinción"),
                            ("RECONOCIMIENTO", "Reconocimiento"),
                            ("MEDALLA", "Medalla"),
                            ("DIPLOMA", "Diploma"),
                            ("GUGGENHEIM", "Beca Guggenheim"),
                            ("HONORIS_CAUSA", "Doctorado Honoris Causa"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ambito",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOCAL", "Local"),
                            ("INSTITUCIONAL", "Institucional"),
                            ("REGIONAL", "Regional"),
                            ("NACIONAL", "Nacional"),
                            ("INTERNACIONAL", "Internacional"),
                        ],
                        max_length=20,
                        verbose_name="ámbito",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nucleo.institucion",
                        verbose_name="institución que la otorga",
                    ),
                ),
            ],
            options={
                "verbose_name": "distinción",
                "verbose_name_plural": "distinciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENVIADO", "Enviado"),
                            ("ACEPTADO", "Aceptado"),
                            ("EN_PRENSA", "En prensa"),
                            ("PUBLICADO", "Publicado"),
                        ],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("fecha_enviado", models.DateField(blank=True, null=True)),
                ("fecha_aceptado", models.DateField(blank=True, null=True)),
                (
                    "fecha_enprensa",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha en prensa"
                    ),
                ),
                ("fecha_publicado", models.DateField(blank=True, null=True)),
                (
                    "titulo",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="título"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INVESTIGACION", "Investigación"),
                            ("DIVULGACION", "Divulgación"),
                            ("DOCENCIA", "Docencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("editorial", models.CharField(blank=True, max_length=255)),
                ("ciudad", models.CharField(blank=True, max_length=255)),
                (
                    "coleccion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="colección"
                    ),
                ),
                ("volumen", models.CharField(blank=True, max_length=255)),
                (
                    "numero_edicion",
                    models.PositiveIntegerField(
                        default=1, verbose_name="número de edición"
                    ),
                ),
                (
                    "numero_paginas",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="número de páginas"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=30, verbose_name="ISBN"),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "arbitrado_pares",
                    models.BooleanField(
                        default=False, verbose_name="arbitrado por pares"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nucleo.pais",
                        verbose_name="país",
                    ),
                ),
            ],
            options={
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150)),
                ("apellidos", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        help_text="Cuenta del sistema asociada, si la persona es académica de la entidad.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persona",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["apellidos", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="LibroParticipante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("AUTOR", "Autor"),
                            ("EDITOR", "Editor"),
                            ("COORDINADOR", "Coordinador"),
                            ("COMPILADOR", "Compilador"),
                        ],
                        default="AUTOR",
                        max_length=20,
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nucleo.libro"
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="nucleo.persona"
                    ),
                ),
            ],
            options={
                "verbose_name": "participante",
                "verbose_name_plural": "participantes",
                "ordering": ["orden", "pk"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="libro",
            name="agradecimientos",
            field=models.ManyToManyField(
                blank=True, related_name="libros_agradecimientos", to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="libro",
            name="participantes",
            field=models.ManyToManyField(
                related_name="libros",
                through="nucleo.LibroParticipante",
                to="nucleo.persona",
            ),
        ),
        migrations.CreateModel(
            name="ProgramaAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("LICENCIATURA", "Licenciatura"),
                            ("MAESTRIA", "Maestría"),
                            ("DOCTORADO", "Doctorado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "area_conocimiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nucleo.areaconocimiento",
                        verbose_name="área de conocimiento",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "programa académico",
                "verbose_name_plural": "programas académicos",
                "ordering": ["nivel", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Revista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "nombre_abreviado",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="nombre abreviado (WoS)",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CIENTIFICA", "Científica"),
                            ("DIVULGACION", "Divulgación"),
                        ],
                        default="CIENTIFICA",
                        max_length=20,
                    ),
                ),
                (
                    "issn_impreso",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="ISSN impreso"
                    ),
                ),
                (
                    "issn_electronico",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="ISSN electrónico"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "indices",
                    models.ManyToManyField(
                        blank=True, to="nucleo.indice", verbose_name="índices"
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nucleo.pais",
                        verbose_name="país",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="fecha de término")),
                ("ciudad", models.CharField(blank=True, max_length=255)),
                (
                    "ambito",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOCAL", "Local"),
                            ("INSTITUCIONAL", "Institucional"),
                            ("REGIONAL", "Regional"),
                            ("NACIONAL", "Nacional"),
                            ("INTERNACIONAL", "Internacional"),
                        ],
                        max_length=20,
                        verbose_name="ámbito",
                    ),
                ),
                (
                    "numero_ponentes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="número de ponentes"
                    ),
                ),
                (
                    "numero_asistentes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="número de asistentes"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nucleo.pais",
                        verbose_name="país",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nucleo.tipoevento",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_inicio", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACADEMICO", "Académico"),
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("DIRECTIVO", "Directivo"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nombre", "tipo"), name="cargo_unico"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MedioDivulgacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PERIODICO", "Periódico"),
                            ("RADIO", "Radio"),
                            ("TV", "Televisión"),
                            ("INTERNET", "Internet"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("canal", models.CharField(blank=True, max_length=255)),
                ("ciudad", models.CharField(blank=True, max_length=255)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nucleo.pais",
                        verbose_name="país",
                    ),
                ),
            ],
            options={
                "verbose_name": "medio de divulgación",
                "verbose_name_plural": "medios de divulgación",
                "ordering": ["nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nombre", "canal"), name="medio_unico"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="institucion",
            constraint=models.UniqueConstraint(
                fields=("nombre", "pais", "ciudad"), name="institucion_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="libroparticipante",
            constraint=models.UniqueConstraint(
                fields=("libro", "persona", "rol"), name="libro_participante_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="programaacademico",
            constraint=models.UniqueConstraint(
                fields=("nombre", "nivel"), name="programa_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="evento",
            constraint=models.UniqueConstraint(
                fields=("nombre", "fecha_inicio"), name="evento_unico"
            ),
        ),
    ]
