# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='financiamiento_conacyt',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='financiamiento_papiit',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
