# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revista',
            options={'get_latest_by': ['nombre_revista'], 'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
