# Generated by Django 6.1.1 on 2026-09-26 18:36

import django.core.validators
import django.db.models.deletion
import nucleo.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("nucleo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmacionInforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("comentario", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "confirmación de informe",
                "verbose_name_plural": "confirmaciones de informe",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Evidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "archivo",
                    models.FileField(
                        help_text="PDF, imagen u hoja de cálculo; máximo 15 MB.",
                        max_length=255,
                        storage=nucleo.models.almacenamiento_evidencias,
                        upload_to=nucleo.models.ruta_evidencia,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "odt",
                                    "ods",
                                ]
                            ),
                            nucleo.models.validar_tamano_evidencia,
                        ],
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="descripción"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "evidencia",
                "verbose_name_plural": "evidencias",
                "ordering": ["creado"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAreaConocimiento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("LSBM", "Life Sciences and Biomedicine"),
                            ("PHYS", "Physical Sciences"),
                            ("TECH", "Technology"),
                            ("ARTH", "Arts and Humanities"),
                            ("SS", "Social Sciences"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=4,
                        verbose_name="categoría",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical área de conocimiento",
                "verbose_name_plural": "historical áreas de conocimiento",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAsignatura",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("actualizado", models.DateTimeField(blank=True, editable=False)),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical asignatura",
                "verbose_name_plural": "historical asignaturas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBeca",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("actualizado", models.DateTimeField(blank=True, editable=False)),
                ("nombre", models.CharField(db_index=True, max_length=200)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical beca",
                "verbose_name_plural": "historical becas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCargo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("actualizado", models.DateTimeField(blank=True, editable=False)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACADEMICO", "Académico"),
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("DIRECTIVO", "Directivo"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cargo",
                "verbose_name_plural": "historical cargos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalConfirmacionInforme",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("fecha", models.DateTimeField(blank=True, editable=False)),
                ("comentario", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical confirmación de informe",
                "verbose_name_plural": "historical confirmaciones de informe",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDistincion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("actualizado", models.DateTimeField(blank=True, editable=False)),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PREMIO", "Premio"),
                            ("DISTINCION", "Distinción"),
                            ("RECONOCIMIENTO", "Reconocimiento"),
                            ("MEDALLA", "Medalla"),
                            ("DIPLOMA", "Diploma"),
                            ("GUGGENHEIM", "Beca Guggenheim"),
                            ("HONORIS_CAUSA", "Doctorado Honoris Causa"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ambito",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOCAL", "Local"),
                            ("INSTITUCIONAL", "Institucional"),
                            ("REGIONAL", "Regional"),
                            ("NACIONAL", "Nacional"),
                            ("INTERNACIONAL", "Internacional"),
                        ],
                        max_length=20,
                        verbose_name="ámbito",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical distinción",
                "verbose_name_plural": "historical distinciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEvento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("actualizado", models.DateTimeField(blank=True, editable=False)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="fecha de término")),
                ("ciudad", models.CharField(blank=True, max_length=255)),
                (
                    "ambito",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOCAL", "Local"),
                            ("INSTITUCIONAL", "Institucional"),
                            ("REGIONAL", "Regional"),
                            ("NACIONAL", "Nacional"),
                            ("INTERNACIONAL", "Internacional"),
                        ],
                        editable=False,
                        help_text="Se calcula a partir del país.",
                        max_length=20,
                        verbose_name="ámbito",
                    ),
                ),
                (
                    "numero_ponentes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="número de ponentes"
                    ),
                ),
                (
                    "numero_asistentes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="número de asistentes"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical evento",
                "verbose_name_plural": "historical eventos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEvidencia",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "archivo",
                    models.TextField(
                        help_text="PDF, imagen u hoja de cálculo; máximo 15 MB.",
                        max_length=255,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "odt",
                                    "ods",
                                ]
                            ),
                            nucleo.models.validar_tamano_evidencia,
                        ],
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="descripción"
                    ),
                ),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical evidencia",
                "verbose_name_plural": "historical evidencias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalIndice",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical índice",
                "verbose_name_plural": "historical índices",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInstitucion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("actualizado", models.DateTimeField(blank=True, editable=False)),
                ("nombre", models.CharField(max_length=255)),
                ("ciudad", models.CharField(blank=True, max_length=255)),
                (
                    "clasificacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACADEMICA", "Académica"),
                            ("FEDERAL", "Gubernamental federal"),
                            ("ESTATAL", "Gubernamental estatal"),
                            ("MUNICIPAL", "Gubernamental municipal"),
                            ("PRIVADA", "Sector privado"),
                            ("NO_LUCRATIVA", "Sector privado no lucrativo"),
                        ],
                        max_length=20,
                        verbose_name="clasificación",
                    ),
                ),
                (
                    "pertenece_unam",
                    models.BooleanField(
                        default=False, verbose_name="pertenece a la UNAM"
                    ),
                ),
                (
                    "subsistema_unam",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIFUSION_CULTURAL", "Subsistema de Difusión Cultural"),
                            ("ESTUDIOS_POSGRADO", "Subsistema de Estudios de Posgrado"),
                            ("HUMANIDADES", "Subsistema de Humanidades"),
                            (
                                "INVESTIGACION_CIENTIFICA",
                                "Subsistema de Investigación Científica",
                            ),
                            ("ESCUELAS", "Facultades y Escuelas"),
                            ("DESARROLLO_INSTITUCIONAL", "Desarrollo Institucional"),
                        ],
                        max_length=30,
                        verbose_name="subsistema UNAM",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical institución",
                "verbose_name_plural": "historical instituciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLibro",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("actualizado", models.DateTimeField(blank=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENVIADO", "Enviado"),
                            ("ACEPTADO", "Aceptado"),
                            ("EN_PRENSA", "En prensa"),
                            ("PUBLICADO", "Publicado"),
                        ],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("fecha_enviado", models.DateField(blank=True, null=True)),
                ("fecha_aceptado", models.DateField(blank=True, null=True)),
                (
                    "fecha_enprensa",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha en prensa"
                    ),
                ),
                ("fecha_publicado", models.DateField(blank=True, null=True)),
                (
                    "titulo",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="título"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INVESTIGACION", "Investigación"),
                            ("DIVULGACION", "Divulgación"),
                            ("DOCENCIA", "Docencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("editorial", models.CharField(blank=True, max_length=255)),
                ("ciudad", models.CharField(blank=True, max_length=255)),
                (
                    "coleccion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="colección"
                    ),
                ),
                ("volumen", models.CharField(blank=True, max_length=255)),
                (
                    "numero_edicion",
                    models.PositiveIntegerField(
                        default=1, verbose_name="número de edición"
                    ),
                ),
                (
                    "numero_paginas",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="número de páginas"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=30, verbose_name="ISBN"),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "arbitrado_pares",
                    models.BooleanField(
                        default=False,
                        help_text="El libro pasó por dictamen de pares académicos antes de publicarse.",
                        verbose_name="arbitrado por pares",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical libro",
                "verbose_name_plural": "historical libros",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLibroParticipante",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("AUTOR", "Autor"),
                            ("EDITOR", "Editor"),
                            ("COORDINADOR", "Coordinador"),
                            ("COMPILADOR", "Compilador"),
                        ],
                        default="AUTOR",
                        max_length=20,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical participante",
                "verbose_name_plural": "historical participantes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMedioDivulgacion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("actualizado", models.DateTimeField(blank=True, editable=False)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PERIODICO", "Periódico"),
                            ("RADIO", "Radio"),
                            ("TV", "Televisión"),
                            ("INTERNET", "Internet"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("canal", models.CharField(blank=True, max_length=255)),
                ("ciudad", models.CharField(blank=True, max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical medio de divulgación",
                "verbose_name_plural": "historical medios de divulgación",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMetricaRevista",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("anio", models.PositiveSmallIntegerField(verbose_name="año")),
                (
                    "fuente",
                    models.CharField(
                        choices=[
                            ("JCR", "Journal Citation Reports (JIF)"),
                            ("SJR", "Scimago Journal Rank"),
                            ("OTRA", "Otra"),
                        ],
                        default="JCR",
                        max_length=10,
                    ),
                ),
                (
                    "factor_impacto",
                    models.DecimalField(
                        decimal_places=3, max_digits=7, verbose_name="factor de impacto"
                    ),
                ),
                (
                    "cuartil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Q1", "Q1"),
                            ("Q2", "Q2"),
                            ("Q3", "Q3"),
                            ("Q4", "Q4"),
                        ],
                        max_length=2,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical métrica de la revista",
                "verbose_name_plural": "historical métricas de la revista",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalNombramiento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("clave", models.CharField(db_index=True, max_length=20)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical nombramiento",
                "verbose_name_plural": "historical nombramientos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPais",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=60)),
                ("nombre_extendido", models.CharField(blank=True, max_length=200)),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=2, verbose_name="código ISO"
                    ),
                ),
                (
                    "zona",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AMERICA_NORTE", "América del Norte"),
                            ("AMERICA_CENTRAL", "América Central"),
                            ("AMERICA_SUR", "América del Sur"),
                            ("ANTILLAS", "Antillas"),
                            ("EUROPA", "Europa"),
                            ("ASIA", "Asia"),
                            ("EURASIA", "Europa-Asia"),
                            ("AFRICA", "África"),
                            ("OCEANIA", "Oceanía"),
                        ],
                        max_length=20,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical país",
                "verbose_name_plural": "historical países",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPeriodoInforme",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "anio",
                    models.PositiveSmallIntegerField(db_index=True, verbose_name="año"),
                ),
                (
                    "fecha_limite",
                    models.DateField(verbose_name="fecha límite de captura"),
                ),
                ("cerrado", models.BooleanField(default=False)),
                (
                    "cerrado_en",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical periodo de informe",
                "verbose_name_plural": "historical periodos de informe",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPersona",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("actualizado", models.DateTimeField(blank=True, editable=False)),
                ("nombre", models.CharField(max_length=150)),
                ("apellidos", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        help_text="Formato 0000-0002-1825-0097.",
                        max_length=19,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$",
                                "El ORCID debe tener el formato 0000-0000-0000-000X.",
                            )
                        ],
                        verbose_name="ORCID",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical persona",
                "verbose_name_plural": "historical personas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProgramaAcademico",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("actualizado", models.DateTimeField(blank=True, editable=False)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("LICENCIATURA", "Licenciatura"),
                            ("MAESTRIA", "Maestría"),
                            ("DOCTORADO", "Doctorado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical programa académico",
                "verbose_name_plural": "historical programas académicos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRevista",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("actualizado", models.DateTimeField(blank=True, editable=False)),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                (
                    "nombre_abreviado",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="nombre abreviado (WoS)",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CIENTIFICA", "Científica"),
                            ("DIVULGACION", "Divulgación"),
                        ],
                        default="CIENTIFICA",
                        max_length=20,
                    ),
                ),
                (
                    "issn_impreso",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}-\\d{3}[\\dX]$",
                                "El ISSN debe tener el formato 1234-567X.",
                            )
                        ],
                        verbose_name="ISSN impreso",
                    ),
                ),
                (
                    "issn_electronico",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}-\\d{3}[\\dX]$",
                                "El ISSN debe tener el formato 1234-567X.",
                            )
                        ],
                        verbose_name="ISSN electrónico",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical revista",
                "verbose_name_plural": "historical revistas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTipoEvento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tipo de evento",
                "verbose_name_plural": "historical tipos de evento",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MetricaRevista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveSmallIntegerField(verbose_name="año")),
                (
                    "fuente",
                    models.CharField(
                        choices=[
                            ("JCR", "Journal Citation Reports (JIF)"),
                            ("SJR", "Scimago Journal Rank"),
                            ("OTRA", "Otra"),
                        ],
                        default="JCR",
                        max_length=10,
                    ),
                ),
                (
                    "factor_impacto",
                    models.DecimalField(
                        decimal_places=3, max_digits=7, verbose_name="factor de impacto"
                    ),
                ),
                (
                    "cuartil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Q1", "Q1"),
                            ("Q2", "Q2"),
                            ("Q3", "Q3"),
                            ("Q4", "Q4"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "métrica de la revista",
                "verbose_name_plural": "métricas de la revista",
                "ordering": ["-anio"],
            },
        ),
        migrations.CreateModel(
            name="PeriodoInforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anio",
                    models.PositiveSmallIntegerField(unique=True, verbose_name="año"),
                ),
                (
                    "fecha_limite",
                    models.DateField(verbose_name="fecha límite de captura"),
                ),
                ("cerrado", models.BooleanField(default=False)),
                (
                    "cerrado_en",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "verbose_name": "periodo de informe",
                "verbose_name_plural": "periodos de informe",
                "ordering": ["-anio"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="institucion",
            name="institucion_unica",
        ),
        migrations.AddField(
            model_name="institucion",
            name="padre",
            field=models.ForeignKey(
                blank=True,
                help_text="Institución de la que depende (p. ej. una facultad pertenece a su universidad).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dependencias",
                to="nucleo.institucion",
                verbose_name="pertenece a",
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="orcid",
            field=models.CharField(
                blank=True,
                help_text="Formato 0000-0002-1825-0097.",
                max_length=19,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$",
                        "El ORCID debe tener el formato 0000-0000-0000-000X.",
                    )
                ],
                verbose_name="ORCID",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="ambito",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOCAL", "Local"),
                    ("INSTITUCIONAL", "Institucional"),
                    ("REGIONAL", "Regional"),
                    ("NACIONAL", "Nacional"),
                    ("INTERNACIONAL", "Internacional"),
                ],
                editable=False,
                help_text="Se calcula a partir del país.",
                max_length=20,
                verbose_name="ámbito",
            ),
        ),
        migrations.AlterField(
            model_name="libro",
            name="arbitrado_pares",
            field=models.BooleanField(
                default=False,
                help_text="El libro pasó por dictamen de pares académicos antes de publicarse.",
                verbose_name="arbitrado por pares",
            ),
        ),
        migrations.AlterField(
            model_name="revista",
            name="issn_electronico",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{4}-\\d{3}[\\dX]$",
                        "El ISSN debe tener el formato 1234-567X.",
                    )
                ],
                verbose_name="ISSN electrónico",
            ),
        ),
        migrations.AlterField(
            model_name="revista",
            name="issn_impreso",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{4}-\\d{3}[\\dX]$",
                        "El ISSN debe tener el formato 1234-567X.",
                    )
                ],
                verbose_name="ISSN impreso",
            ),
        ),
        migrations.AddConstraint(
            model_name="institucion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("padre__isnull", True)),
                fields=("nombre", "pais", "ciudad"),
                name="institucion_unica",
            ),
        ),
        migrations.AddConstraint(
            model_name="institucion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("padre__isnull", False)),
                fields=("nombre", "padre", "pais", "ciudad"),
                name="dependencia_unica",
            ),
        ),
        migrations.AddField(
            model_name="confirmacioninforme",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirmaciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evidencia",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="evidencia",
            name="subido_por",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalareaconocimiento",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalasignatura",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalasignatura",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbeca",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbeca",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcargo",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcargo",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalconfirmacioninforme",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalconfirmacioninforme",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldistincion",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldistincion",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldistincion",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nucleo.institucion",
                verbose_name="institución que la otorga",
            ),
        ),
        migrations.AddField(
            model_name="historicalevento",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalevento",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalevento",
            name="pais",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nucleo.pais",
                verbose_name="país",
            ),
        ),
        migrations.AddField(
            model_name="historicalevento",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nucleo.tipoevento",
            ),
        ),
        migrations.AddField(
            model_name="historicalevidencia",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="historicalevidencia",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalevidencia",
            name="subido_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalindice",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalinstitucion",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalinstitucion",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalinstitucion",
            name="padre",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Institución de la que depende (p. ej. una facultad pertenece a su universidad).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nucleo.institucion",
                verbose_name="pertenece a",
            ),
        ),
        migrations.AddField(
            model_name="historicalinstitucion",
            name="pais",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nucleo.pais",
                verbose_name="país",
            ),
        ),
        migrations.AddField(
            model_name="historicallibro",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicallibro",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicallibro",
            name="pais",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nucleo.pais",
                verbose_name="país",
            ),
        ),
        migrations.AddField(
            model_name="historicallibroparticipante",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicallibroparticipante",
            name="libro",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nucleo.libro",
            ),
        ),
        migrations.AddField(
            model_name="historicallibroparticipante",
            name="persona",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="historicalmediodivulgacion",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalmediodivulgacion",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalmediodivulgacion",
            name="pais",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nucleo.pais",
                verbose_name="país",
            ),
        ),
        migrations.AddField(
            model_name="historicalmetricarevista",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalmetricarevista",
            name="revista",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nucleo.revista",
            ),
        ),
        migrations.AddField(
            model_name="historicalnombramiento",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpais",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalperiodoinforme",
            name="cerrado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalperiodoinforme",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpersona",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpersona",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpersona",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Cuenta del sistema asociada, si la persona es académica de la entidad.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalprogramaacademico",
            name="area_conocimiento",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nucleo.areaconocimiento",
                verbose_name="área de conocimiento",
            ),
        ),
        migrations.AddField(
            model_name="historicalprogramaacademico",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalprogramaacademico",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalrevista",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalrevista",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalrevista",
            name="pais",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nucleo.pais",
                verbose_name="país",
            ),
        ),
        migrations.AddField(
            model_name="historicaltipoevento",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="metricarevista",
            name="revista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metricas",
                to="nucleo.revista",
            ),
        ),
        migrations.AddField(
            model_name="periodoinforme",
            name="cerrado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalconfirmacioninforme",
            name="periodo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="nucleo.periodoinforme",
            ),
        ),
        migrations.AddField(
            model_name="confirmacioninforme",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirmaciones",
                to="nucleo.periodoinforme",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencia",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="nucleo_evid_content_f182fb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricarevista",
            constraint=models.UniqueConstraint(
                fields=("revista", "anio", "fuente"), name="metrica_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="confirmacioninforme",
            constraint=models.UniqueConstraint(
                fields=("periodo", "usuario"), name="confirmacion_unica"
            ),
        ),
    ]
