# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revista',
            name='nombre_abreviado_wos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
