# Generated by Django 2.0.6 on 2018-12-14 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='fecha_creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciudad',
            name='validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='fecha_actualizado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='fecha_creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependencia',
            name='usuario_creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependencia',
            name='validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institucion',
            name='fecha_actualizado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='fecha_creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucion',
            name='usuario_creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucion',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
