# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='titulo',
            field=models.CharField(choices=[('', '-------'), ('Dr', 'Doctor'), ('Dra', 'Doctora')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
