# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependencia',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucion',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucion',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Estado'),
            preserve_default=False,
        ),
    ]
