# Generated by Django 2.0.5 on 2018-05-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20180529_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revista',
            name='factor_impacto',
        ),
        migrations.AddField(
            model_name='revista',
            name='indices',
            field=models.ManyToManyField(blank=True, related_name='articulo_cientifico_indices', to='nucleo.Indice'),
        ),
    ]
