# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20170925_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='es_libro_completo',
            field=models.BooleanField(default=False),
        ),
    ]
