# Generated by Django 2.0.2 on 2018-02-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20180203_2045'),
        ('nucleo', '0002_auto_20180203_1148'),
    ]

    operations = [
    ]
