# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20170323_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='slug',
        ),
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('INVESTIGACION', 'Investigación'), ('DIVULGACION', 'Divulgaciòn')], max_length=50),
        ),
    ]
