# Generated by Django 2.1.7 on 2019-02-16 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20181213_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionSimple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_nombre', models.CharField(max_length=255, unique=True)),
                ('institucion_ciudad', models.CharField(max_length=255)),
                ('institucion_clasificacion', models.CharField(choices=[('', '-------'), ('ACADEMICA', 'Académica'), ('FEDERAL', 'Gubernamental federal'), ('ESTATAL', 'Gubernamental estatal'), ('MUNICIPAL', 'Gubernamental municipal'), ('PRIVADA', 'Sector privado'), ('NO_LUCRATIVA', 'Sector privado no lucrativo')], max_length=20)),
                ('institucion_perteneceunam', models.BooleanField(default=False)),
                ('institucion_subsistemaunam', models.CharField(blank=True, choices=[('', 'Seleccionar Subsistema UNAM'), ('DIFUSION_CULTURAL', 'Subsistema de Difusión Cultural'), ('ESTUDIOS_POSGRADO', 'Subsistema de Estudios de Posgrado'), ('HUMANIDADES', 'Subsistema de Humanidades'), ('INVESTIGACION_CIENTIFICA', 'Subsistema de Investigación Científica'), ('ESCUELAS', 'Facultades y Escuelas'), ('DESARROLLO_INSTITUCIONAL', 'Desarrollo Institucional')], max_length=50, null=True, verbose_name='Subsistema UNAM')),
                ('institucion_regverificado', models.BooleanField(default=False)),
                ('institucion_regfechacreado', models.DateField(auto_now_add=True)),
                ('institucion_regfechaactualizado', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['institucion_nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='investigadorconacyt',
            name='investigador',
        ),
        migrations.RemoveField(
            model_name='investigadorinvitado',
            name='investigador',
        ),
        migrations.RemoveField(
            model_name='investigadorunam',
            name='investigador',
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['pais_nombre'], 'verbose_name': 'País', 'verbose_name_plural': 'Paises'},
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='codigo',
            new_name='pais_codigo',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='nombre',
            new_name='pais_nombre',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='nombre_extendido',
            new_name='pais_nombre_extendido',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='zona',
            new_name='pais_zona',
        ),
        migrations.DeleteModel(
            name='InvestigadorConacyt',
        ),
        migrations.DeleteModel(
            name='InvestigadorInvitado',
        ),
        migrations.DeleteModel(
            name='InvestigadorUnam',
        ),
        migrations.AddField(
            model_name='institucionsimple',
            name='institucion_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.Pais'),
        ),
        migrations.AddField(
            model_name='institucionsimple',
            name='institucion_regusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
