# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20171020_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ultimo_contrato',
            field=models.DateField(blank=True, null=True),
        ),
    ]
