# Generated by Django 2.0.5 on 2018-05-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20180529_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sic',
            field=models.BooleanField(default=False),
        ),
    ]
