# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_libro_es_libro_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='egreso_entidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
