# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20171103_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curp',
            field=models.SlugField(blank=True, max_length=20),
        ),
    ]
