# Generated by Django 6.1.1 on 2026-09-26 19:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleo", "0003_normalizar_datos"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionEntidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="nombre de la entidad"
                    ),
                ),
                ("siglas", models.CharField(blank=True, max_length=30)),
                (
                    "institucion_madre",
                    models.CharField(
                        blank=True,
                        default="Universidad Nacional Autónoma de México",
                        max_length=255,
                        verbose_name="institución a la que pertenece",
                    ),
                ),
                (
                    "institucion_madre_siglas",
                    models.CharField(
                        blank=True,
                        default="UNAM",
                        max_length=30,
                        verbose_name="siglas de la institución",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Aparece en el CV y en los formatos impresos.",
                        null=True,
                        upload_to="configuracion",
                    ),
                ),
                (
                    "titular",
                    models.CharField(
                        blank=True,
                        help_text="Firma el visto bueno de los formatos.",
                        max_length=255,
                        verbose_name="nombre de quien dirige",
                    ),
                ),
                (
                    "cargo_titular",
                    models.CharField(
                        default="Director(a)",
                        max_length=100,
                        verbose_name="cargo de quien dirige",
                    ),
                ),
                ("ciudad", models.CharField(blank=True, max_length=255)),
                ("direccion", models.TextField(blank=True, verbose_name="dirección")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="teléfono"
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo de contacto"
                    ),
                ),
                ("sitio_web", models.URLField(blank=True, verbose_name="sitio web")),
                (
                    "consejo_tecnico",
                    models.CharField(
                        blank=True,
                        default="Consejo Técnico de la Investigación Científica",
                        help_text="Órgano ante el que se tramitan las licencias con goce de sueldo.",
                        max_length=255,
                        verbose_name="consejo técnico",
                    ),
                ),
                (
                    "remitente",
                    models.EmailField(
                        blank=True,
                        help_text="Si se deja vacío se usa el configurado en el servidor.",
                        max_length=254,
                        verbose_name="remitente de los correos",
                    ),
                ),
                (
                    "anios_tablero",
                    models.PositiveSmallIntegerField(
                        default=6, verbose_name="años en el tablero"
                    ),
                ),
                (
                    "meses_publicacion_pendiente",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="Una publicación no publicada que no cambia de estado en este tiempo aparece en los pendientes.",
                        verbose_name="meses para marcar una publicación como pendiente",
                    ),
                ),
                (
                    "pais_sede",
                    models.ForeignKey(
                        blank=True,
                        help_text="Define si un evento o participación es nacional o internacional.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nucleo.pais",
                        verbose_name="país sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuración de la entidad",
                "verbose_name_plural": "configuración de la entidad",
            },
        ),
        migrations.CreateModel(
            name="HistoricalConfiguracionEntidad",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="nombre de la entidad"
                    ),
                ),
                ("siglas", models.CharField(blank=True, max_length=30)),
                (
                    "institucion_madre",
                    models.CharField(
                        blank=True,
                        default="Universidad Nacional Autónoma de México",
                        max_length=255,
                        verbose_name="institución a la que pertenece",
                    ),
                ),
                (
                    "institucion_madre_siglas",
                    models.CharField(
                        blank=True,
                        default="UNAM",
                        max_length=30,
                        verbose_name="siglas de la institución",
                    ),
                ),
                (
                    "logo",
                    models.TextField(
                        blank=True,
                        help_text="Aparece en el CV y en los formatos impresos.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "titular",
                    models.CharField(
                        blank=True,
                        help_text="Firma el visto bueno de los formatos.",
                        max_length=255,
                        verbose_name="nombre de quien dirige",
                    ),
                ),
                (
                    "cargo_titular",
                    models.CharField(
                        default="Director(a)",
                        max_length=100,
                        verbose_name="cargo de quien dirige",
                    ),
                ),
                ("ciudad", models.CharField(blank=True, max_length=255)),
                ("direccion", models.TextField(blank=True, verbose_name="dirección")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="teléfono"
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo de contacto"
                    ),
                ),
                ("sitio_web", models.URLField(blank=True, verbose_name="sitio web")),
                (
                    "consejo_tecnico",
                    models.CharField(
                        blank=True,
                        default="Consejo Técnico de la Investigación Científica",
                        help_text="Órgano ante el que se tramitan las licencias con goce de sueldo.",
                        max_length=255,
                        verbose_name="consejo técnico",
                    ),
                ),
                (
                    "remitente",
                    models.EmailField(
                        blank=True,
                        help_text="Si se deja vacío se usa el configurado en el servidor.",
                        max_length=254,
                        verbose_name="remitente de los correos",
                    ),
                ),
                (
                    "anios_tablero",
                    models.PositiveSmallIntegerField(
                        default=6, verbose_name="años en el tablero"
                    ),
                ),
                (
                    "meses_publicacion_pendiente",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="Una publicación no publicada que no cambia de estado en este tiempo aparece en los pendientes.",
                        verbose_name="meses para marcar una publicación como pendiente",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pais_sede",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Define si un evento o participación es nacional o internacional.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.pais",
                        verbose_name="país sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical configuración de la entidad",
                "verbose_name_plural": "historical configuración de la entidad",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
