# Generated by Django 2.1.7 on 2019-02-16 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20190216_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucionsimple',
            name='institucion_ciudad',
            field=models.CharField(max_length=255, verbose_name='Ciudad donde se encuentra la institución'),
        ),
        migrations.AlterField(
            model_name='institucionsimple',
            name='institucion_clasificacion',
            field=models.CharField(choices=[('', '-------'), ('ACADEMICA', 'Académica'), ('FEDERAL', 'Gubernamental federal'), ('ESTATAL', 'Gubernamental estatal'), ('MUNICIPAL', 'Gubernamental municipal'), ('PRIVADA', 'Sector privado'), ('NO_LUCRATIVA', 'Sector privado no lucrativo')], max_length=20, verbose_name='Clasificación de la institución'),
        ),
        migrations.AlterField(
            model_name='institucionsimple',
            name='institucion_nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre de la institución'),
        ),
        migrations.AlterField(
            model_name='institucionsimple',
            name='institucion_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.Pais', verbose_name='País donde se encuentra la institución'),
        ),
        migrations.AlterField(
            model_name='institucionsimple',
            name='institucion_perteneceunam',
            field=models.BooleanField(default=False, verbose_name='Pertenece a la UNAM'),
        ),
        migrations.AlterField(
            model_name='institucionsimple',
            name='institucion_regusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro de esta entrada'),
        ),
        migrations.AlterField(
            model_name='institucionsimple',
            name='institucion_regverificado',
            field=models.BooleanField(default=False, verbose_name='Este registro se encuentra validado y verificado. Cuando un registro está marcado como verificado ya no es posible editar ni eliminar por otros usuarios'),
        ),
        migrations.AlterField(
            model_name='institucionsimple',
            name='institucion_subsistemaunam',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar Subsistema UNAM'), ('DIFUSION_CULTURAL', 'Subsistema de Difusión Cultural'), ('ESTUDIOS_POSGRADO', 'Subsistema de Estudios de Posgrado'), ('HUMANIDADES', 'Subsistema de Humanidades'), ('INVESTIGACION_CIENTIFICA', 'Subsistema de Investigación Científica'), ('ESCUELAS', 'Facultades y Escuelas'), ('DESARROLLO_INSTITUCIONAL', 'Desarrollo Institucional')], max_length=50, null=True, verbose_name='Subsistema UNAM (sólo si la institución pertenece a la UNAM)'),
        ),
    ]
