# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20170327_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='coleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Coleccion'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('INVESTIGACION', 'Investigación'), ('DIVULGACION', 'Divulgación')], max_length=50),
        ),
    ]
