# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_user_egreso_entidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='tiene_participacion_prologo',
            field=models.BooleanField(default=False),
        ),
    ]
