# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_user_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='tipo_cargo',
            field=models.CharField(choices=[('ACADEMICO', 'Académico'), ('ADMINISTRATIVO', 'Administrativo'), ('DIRECTIVO', 'Directivo'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
