# Generated by Django 2.1.7 on 2019-02-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20190216_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucionsimple',
            name='institucion_nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre de la institución'),
        ),
        migrations.AlterField(
            model_name='institucionsimple',
            name='institucion_subsistemaunam',
            field=models.CharField(blank=True, choices=[('', '-------'), ('DIFUSION_CULTURAL', 'Subsistema de Difusión Cultural'), ('ESTUDIOS_POSGRADO', 'Subsistema de Estudios de Posgrado'), ('HUMANIDADES', 'Subsistema de Humanidades'), ('INVESTIGACION_CIENTIFICA', 'Subsistema de Investigación Científica'), ('ESCUELAS', 'Facultades y Escuelas'), ('DESARROLLO_INSTITUCIONAL', 'Desarrollo Institucional')], max_length=50, null=True, verbose_name='Subsistema UNAM (sólo si la institución pertenece a la UNAM)'),
        ),
        migrations.AlterUniqueTogether(
            name='institucionsimple',
            unique_together={('institucion_nombre', 'institucion_pais')},
        ),
    ]
