# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20170327_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autores',
        ),
        migrations.AddField(
            model_name='libro',
            name='usuarios',
            field=models.ManyToManyField(related_name='libro_autores', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
    ]
