# Generated by Django 6.1.1 on 2026-09-27 00:54

import re
import unicodedata

import nucleo.models
from django.db import migrations, models


def correos_unicos(apps, schema_editor):
    """El correo pasa a ser el identificador: a las cuentas sin correo (o repetido) se les da uno provisional."""
    User = apps.get_model('nucleo', 'User')
    usados = set()
    for user in User.objects.order_by('-last_login', 'pk'):
        correo = user.email.strip().lower()
        if not correo or correo in usados:
            local = re.sub(r'[^a-z0-9._-]+', '', unicodedata.normalize('NFKD', user.username)
                           .encode('ascii', 'ignore').decode().lower()) or f'cuenta{user.pk}'
            correo = f'{local}@sin-correo.invalid'
        usados.add(correo)
        if correo != user.email:
            User.objects.filter(pk=user.pk).update(email=correo)


class Migration(migrations.Migration):

    dependencies = [
        ("nucleo", "0005_configuracion_inicial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", nucleo.models.UsuarioManager()),
            ],
        ),
        migrations.RunPython(correos_unicos, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="correo electrónico"
            ),
        ),
    ]
