# Generated by Django 2.1.7 on 2019-02-23 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20190218_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programadoctorado',
            options={'ordering': ['programadoctorado_nombre'], 'verbose_name': 'Programa de doctorado', 'verbose_name_plural': 'Programas de doctorado'},
        ),
        migrations.AlterModelOptions(
            name='programalicenciatura',
            options={'ordering': ['programalicenciatura_nombre'], 'verbose_name': 'Programa de licenciatura', 'verbose_name_plural': 'Programas de licenciatura'},
        ),
        migrations.AlterModelOptions(
            name='programamaestria',
            options={'ordering': ['programamaestria_nombre'], 'verbose_name': 'Programa de maestria', 'verbose_name_plural': 'Programas de maestria'},
        ),
        migrations.RenameField(
            model_name='programadoctorado',
            old_name='area_conocimiento',
            new_name='programadoctorado_areaconocimiento',
        ),
        migrations.RenameField(
            model_name='programadoctorado',
            old_name='nombre',
            new_name='programadoctorado_nombre',
        ),
        migrations.RenameField(
            model_name='programalicenciatura',
            old_name='area_conocimiento',
            new_name='programalicenciatura_areaconocimiento',
        ),
        migrations.RenameField(
            model_name='programalicenciatura',
            old_name='nombre',
            new_name='programalicenciatura_nombre',
        ),
        migrations.RenameField(
            model_name='programamaestria',
            old_name='area_conocimiento',
            new_name='programamaestria_areaconocimiento',
        ),
        migrations.RenameField(
            model_name='programamaestria',
            old_name='nombre',
            new_name='programamaestria_nombre',
        ),
        migrations.RemoveField(
            model_name='programadoctorado',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='programalicenciatura',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='programamaestria',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='programadoctorado',
            name='programadoctorado_regfechaactualizado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='programadoctorado',
            name='programadoctorado_regfechacreado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programadoctorado',
            name='programadoctorado_regusuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro de esta entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programadoctorado',
            name='programadoctorado_regverificado',
            field=models.BooleanField(default=False, verbose_name='Este registro se encuentra validado y verificado. Cuando un registro está marcado como verificado ya no es posible editar ni eliminar por otros usuarios'),
        ),
        migrations.AddField(
            model_name='programalicenciatura',
            name='programalicenciatura_regfechaactualizado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='programalicenciatura',
            name='programalicenciatura_regfechacreado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programalicenciatura',
            name='programalicenciatura_regusuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro de esta entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programalicenciatura',
            name='programalicenciatura_regverificado',
            field=models.BooleanField(default=False, verbose_name='Este registro se encuentra validado y verificado. Cuando un registro está marcado como verificado ya no es posible editar ni eliminar por otros usuarios'),
        ),
        migrations.AddField(
            model_name='programamaestria',
            name='programamaestria_regfechaactualizado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='programamaestria',
            name='programamaestria_regfechacreado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programamaestria',
            name='programamaestria_regusuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el registro de esta entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programamaestria',
            name='programamaestria_regverificado',
            field=models.BooleanField(default=False, verbose_name='Este registro se encuentra validado y verificado. Cuando un registro está marcado como verificado ya no es posible editar ni eliminar por otros usuarios'),
        ),
    ]
