# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20171112_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('INVESTIGACION', 'Investigación'), ('DIVULGACION', 'Divulgación'), ('DOCENCIA', 'Docencia')], max_length=50),
        ),
    ]
