# Generated by Django 6.1.1 on 2026-09-27 01:27

from django.db import migrations, models


GENERO = {'F': 'FEMENINO', 'M': 'MASCULINO', 'O': 'OTRO'}
SNI = {'1': 'I', '2': 'II', '3': 'III'}


def convertir(apps, schema_editor, genero, sni):
    User = apps.get_model('nucleo', 'User')
    for anterior, nuevo in genero.items():
        User.objects.filter(genero=anterior).update(genero=nuevo)
    for anterior, nuevo in sni.items():
        User.objects.filter(sni=anterior).update(sni=nuevo)


def adelante(apps, schema_editor):
    convertir(apps, schema_editor, GENERO, SNI)


def atras(apps, schema_editor):
    convertir(apps, schema_editor, {v: k for k, v in GENERO.items()}, {v: k for k, v in SNI.items()})


class Migration(migrations.Migration):

    dependencies = [
        ("nucleo", "0007_domicilio_sin_celular"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEMENINO", "Femenino"),
                    ("MASCULINO", "Masculino"),
                    ("OTRO", "Otro"),
                ],
                max_length=10,
                verbose_name="género",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sni",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Candidato"),
                    ("I", "Nivel I"),
                    ("II", "Nivel II"),
                    ("III", "Nivel III"),
                    ("E", "Emérito"),
                ],
                max_length=3,
                verbose_name="nivel SNII",
            ),
        ),
        migrations.RunPython(adelante, atras),
    ]
