# Generated by Django 2.0.6 on 2018-11-07 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_remove_dependencia_clasificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nucleo.Ciudad'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='subsistema_unam',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar Subsistema UNAM (sólo si se trata de una dependencia perteneciente a la UNAM)'), ('DIFUSION_CULTURAL', 'Subsistema de Difusión Cultural'), ('ESTUDIOS_POSGRADO', 'Subsistema de Estudios de Posgrado'), ('HUMANIDADES', 'Subsistema de Humanidades'), ('INVESTIGACION_CIENTIFICA', 'Subsistema de Investigación Científica'), ('ESCUELAS', 'Facultades y Escuelas'), ('DESARROLLO_INSTITUCIONAL', 'Desarrollo Institucional'), ('NINGUNO', 'Ninguno')], max_length=50, null=True, verbose_name='Subsistema UNAM'),
        ),
    ]
