# Generated by Django 2.0.6 on 2018-11-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_auto_20181107_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependencia',
            options={'ordering': ['nombre_dependencia']},
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='ciudad_text',
            new_name='ciudad_text_dependencia',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='descripcion',
            new_name='descripcion_dependencia',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='institucion',
            new_name='institucion_dependencia',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='nombre',
            new_name='nombre_dependencia',
        ),
        migrations.AddField(
            model_name='dependencia',
            name='subsistema_unam_dependencia',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar Subsistema UNAM'), ('DIFUSION_CULTURAL', 'Subsistema de Difusión Cultural'), ('ESTUDIOS_POSGRADO', 'Subsistema de Estudios de Posgrado'), ('HUMANIDADES', 'Subsistema de Humanidades'), ('INVESTIGACION_CIENTIFICA', 'Subsistema de Investigación Científica'), ('ESCUELAS', 'Facultades y Escuelas'), ('DESARROLLO_INSTITUCIONAL', 'Desarrollo Institucional')], max_length=50, null=True, verbose_name='Subsistema UNAM'),
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='subsistema_unam',
        ),
        migrations.AlterUniqueTogether(
            name='dependencia',
            unique_together={('nombre_dependencia', 'institucion_dependencia')},
        ),
    ]
