# Generated by Django 2.0.6 on 2018-11-08 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_auto_20181107_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['nombre_institucion'], 'verbose_name': 'Institución', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.RenameField(
            model_name='institucion',
            old_name='clasificacion',
            new_name='clasificacion_institucion',
        ),
        migrations.RenameField(
            model_name='institucion',
            old_name='descripcion',
            new_name='descripcion_institucion',
        ),
        migrations.RenameField(
            model_name='institucion',
            old_name='nombre',
            new_name='nombre_institucion',
        ),
        migrations.RenameField(
            model_name='institucion',
            old_name='pais',
            new_name='pais_institucion',
        ),
    ]
