# Generated by Django 6.1.1 on 2026-09-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0010_grupo_academicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ambito',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('INSTITUCIONAL', 'Institucional'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional')], max_length=20, verbose_name='ámbito'),
        ),
        migrations.AlterField(
            model_name='historicalevento',
            name='ambito',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('INSTITUCIONAL', 'Institucional'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional')], max_length=20, verbose_name='ámbito'),
        ),
    ]
