# Generated by Django 2.0.6 on 2018-12-05 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0010_auto_20181108_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependencia',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['nombre'], 'verbose_name': 'Institución', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='descripcion_dependencia',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='institucion_dependencia',
            new_name='institucion',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='nombre_dependencia',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='institucion',
            old_name='clasificacion_institucion',
            new_name='clasificacion',
        ),
        migrations.RenameField(
            model_name='institucion',
            old_name='descripcion_institucion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='institucion',
            old_name='nombre_institucion',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='institucion',
            old_name='pais_institucion',
            new_name='pais',
        ),
        migrations.AddField(
            model_name='dependencia',
            name='clasificacion',
            field=models.CharField(choices=[('', '-------'), ('ACADEMICA', 'Académica'), ('FEDERAL', 'Gubernamental federal'), ('ESTATAL', 'Gubernamental estatal'), ('MUNICIPAL', 'Gubernamental municipal'), ('PRIVADA', 'Sector privado'), ('NO_LUCRATIVA', 'Sector privado no lucrativo')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependencia',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nucleo.Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependencia',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nucleo.Pais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependencia',
            name='subsistema_unam',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar Subsistema UNAM (sólo si se trata de una dependencia perteneciente a la UNAM)'), ('DIFUSION_CULTURAL', 'Subsistema de Difusión Cultural'), ('ESTUDIOS_POSGRADO', 'Subsistema de Estudios de Posgrado'), ('HUMANIDADES', 'Subsistema de Humanidades'), ('INVESTIGACION_CIENTIFICA', 'Subsistema de Investigación Científica'), ('ESCUELAS', 'Facultades y Escuelas'), ('DESARROLLO_INSTITUCIONAL', 'Desarrollo Institucional'), ('NO', 'No')], max_length=50, null=True, verbose_name='Subsistema UNAM'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nucleo.Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucion',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nucleo.Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nucleo.Ciudad'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='ciudad_text_dependencia',
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='subsistema_unam_dependencia',
        ),
        migrations.AlterUniqueTogether(
            name='dependencia',
            unique_together={('nombre', 'institucion')},
        ),
    ]
