# Generated by Django 6.1.1 on 2026-09-29 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0014_pais_de_la_entidad'),
        ('nucleo', '0017_pais_de_la_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionentidad',
            name='pais_sede',
            field=models.ForeignKey(blank=True, help_text='País donde se ubica la entidad.', null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.country', verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracionentidad',
            name='pais_sede',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='País donde se ubica la entidad.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cities_light.country', verbose_name='país'),
        ),
    ]
