# Generated by Django 6.1.1 on 2026-09-29 15:30

import nucleo.identificadores
from django.db import migrations, models


def limpiar(apps, schema_editor):
    """Vacía los RFC y CURP que no son válidos (los heredados eran texto al azar) y normaliza los teléfonos."""
    from django.core.exceptions import ValidationError

    from nucleo.identificadores import normalizar_telefono, validar_curp, validar_rfc

    User = apps.get_model('nucleo', 'User')
    for user in User.objects.all():
        cambios = {}
        for campo, validar in (('rfc', validar_rfc), ('curp', validar_curp)):
            valor = getattr(user, campo).strip().upper()
            try:
                if valor:
                    validar(valor)
            except ValidationError:
                valor = ''
            if valor != getattr(user, campo):
                cambios[campo] = valor
        telefono = normalizar_telefono(user.telefono)
        if telefono != user.telefono:
            cambios['telefono'] = telefono
        if cambios:
            User.objects.filter(pk=user.pk).update(**cambios)


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0020_pais_sede_sin_ayuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curp',
            field=models.CharField(blank=True, max_length=18, validators=[nucleo.identificadores.validar_curp], verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rfc',
            field=models.CharField(blank=True, help_text='13 caracteres, con homoclave.', max_length=13, validators=[nucleo.identificadores.validar_rfc], verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, help_text='Si no es de México, con + y código de país. Puede llevar extensión (ext. 123).', max_length=30, validators=[nucleo.identificadores.validar_telefono], verbose_name='teléfono'),
        ),
        migrations.RunPython(limpiar, migrations.RunPython.noop),
    ]
