# Generated by Django 6.1.1 on 2026-09-29 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0021_rfc_curp_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersona',
            name='orcid',
            field=models.CharField(blank=True, help_text='Formato 0000-0002-1825-0097. "Buscar en ORCID" llena el nombre y el correo; el correo solo se obtiene si la persona lo hizo público en ORCID.', max_length=19, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$', 'El ORCID debe tener el formato 0000-0000-0000-000X.')], verbose_name='ORCID'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='orcid',
            field=models.CharField(blank=True, help_text='Formato 0000-0002-1825-0097. "Buscar en ORCID" llena el nombre y el correo; el correo solo se obtiene si la persona lo hizo público en ORCID.', max_length=19, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$', 'El ORCID debe tener el formato 0000-0000-0000-000X.')], verbose_name='ORCID'),
        ),
    ]
