# Generated by Django 6.1.1 on 2026-09-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0022_ayuda_orcid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grado',
            field=models.CharField(blank=True, choices=[('Lic.', 'Lic. (licenciatura)'), ('Ing.', 'Ing. (ingeniería)'), ('Arq.', 'Arq. (arquitectura)'), ('Biól.', 'Biól. (biología)'), ('Geóg.', 'Geóg. (geografía)'), ('Mtro.', 'Mtro. (maestro)'), ('Mtra.', 'Mtra. (maestra)'), ('M. en C.', 'M. en C. (maestría en ciencias)'), ('Dr.', 'Dr. (doctor)'), ('Dra.', 'Dra. (doctora)')], max_length=20, verbose_name='grado académico'),
        ),
    ]
