# Generated by Django 6.1.1 on 2026-09-29 16:03

from django.db import migrations, models


EQUIVALENCIAS = {'Ing.': 'Lic.', 'Arq.': 'Lic.', 'Biól.': 'Lic.', 'Geóg.': 'Lic.', 'M. en C.': 'Mtro.'}


def convertir(apps, schema_editor):
    User = apps.get_model('nucleo', 'User')
    for anterior, nuevo in EQUIVALENCIAS.items():
        User.objects.filter(grado=anterior).update(grado=nuevo)


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0023_grado_opciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grado',
            field=models.CharField(blank=True, choices=[('Lic.', 'Lic. (licenciatura)'), ('Mtro.', 'Mtro. (maestro)'), ('Mtra.', 'Mtra. (maestra)'), ('Dr.', 'Dr. (doctor)'), ('Dra.', 'Dra. (doctora)')], max_length=20, verbose_name='grado académico'),
        ),
        migrations.RunPython(convertir, migrations.RunPython.noop),
    ]
