# Generated by Django 6.1.1 on 2026-09-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nucleo", "0024_grado_simplificado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalnombramiento",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Nombramiento",
                "verbose_name_plural": "historical Nombramientos",
            },
        ),
        migrations.AlterModelOptions(
            name="nombramiento",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Nombramiento",
                "verbose_name_plural": "Nombramientos",
            },
        ),
        migrations.RemoveField(
            model_name="historicalnombramiento",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="nombramiento",
            name="descripcion",
        ),
    ]
