# Generated by Django 6.1.1 on 2026-09-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0025_alter_historicalnombramiento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='beca',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='distincion',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='historicalasignatura',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='historicalbeca',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='historicalcargo',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='historicaldistincion',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='historicalevento',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='historicalinstitucion',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='historicallibro',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='historicalmediodivulgacion',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='historicalpersona',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='historicalprogramaacademico',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='historicalrevista',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='mediodivulgacion',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='programaacademico',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='revista',
            name='verificado',
        ),
    ]
