# Generated by Django 6.1.1 on 2026-09-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0026_sin_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(null=True, verbose_name='fecha de término'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalevento',
            name='fecha_fin',
            field=models.DateField(null=True, verbose_name='fecha de término'),
        ),
        migrations.AlterField(
            model_name='historicalevento',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
    ]
