# Generated by Django 6.1.1 on 2026-10-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0028_fechas_vacias_a_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(verbose_name='fecha de término'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalevento',
            name='fecha_fin',
            field=models.DateField(verbose_name='fecha de término'),
        ),
        migrations.AlterField(
            model_name='historicalevento',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
    ]
