# Generated by Django 6.1.1 on 2026-10-01 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0029_fechas_obligatorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca',
            name='ayuda',
            field=models.CharField(blank=True, help_text='Indicación que se muestra al capturar (p. ej. qué escribir en el detalle). No sale en los reportes.', max_length=255),
        ),
        migrations.AddField(
            model_name='beca',
            name='clase',
            field=models.CharField(blank=True, choices=[('SECIHTI', 'SECIHTI'), ('PAPIIT', 'PAPIIT'), ('PAPIME', 'PAPIME'), ('UNAM', 'Otros programas UNAM'), ('IE_NACIONAL', 'Ingresos extraordinarios nacionales'), ('IE_INTERNACIONAL', 'Ingresos extraordinarios internacionales')], help_text='Clasificación para las gráficas del informe.', max_length=20),
        ),
        migrations.AddField(
            model_name='beca',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nucleo.institucion', verbose_name='institución que la otorga'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='ayuda',
            field=models.CharField(blank=True, help_text='Indicación que se muestra al capturar (p. ej. qué escribir en el detalle). No sale en los reportes.', max_length=255),
        ),
        migrations.AddField(
            model_name='distincion',
            name='ayuda',
            field=models.CharField(blank=True, help_text='Indicación que se muestra al capturar (p. ej. qué escribir en el detalle). No sale en los reportes.', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalbeca',
            name='ayuda',
            field=models.CharField(blank=True, help_text='Indicación que se muestra al capturar (p. ej. qué escribir en el detalle). No sale en los reportes.', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalbeca',
            name='clase',
            field=models.CharField(blank=True, choices=[('SECIHTI', 'SECIHTI'), ('PAPIIT', 'PAPIIT'), ('PAPIME', 'PAPIME'), ('UNAM', 'Otros programas UNAM'), ('IE_NACIONAL', 'Ingresos extraordinarios nacionales'), ('IE_INTERNACIONAL', 'Ingresos extraordinarios internacionales')], help_text='Clasificación para las gráficas del informe.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalbeca',
            name='institucion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.institucion', verbose_name='institución que la otorga'),
        ),
        migrations.AddField(
            model_name='historicalcargo',
            name='ayuda',
            field=models.CharField(blank=True, help_text='Indicación que se muestra al capturar (p. ej. qué escribir en el detalle). No sale en los reportes.', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaldistincion',
            name='ayuda',
            field=models.CharField(blank=True, help_text='Indicación que se muestra al capturar (p. ej. qué escribir en el detalle). No sale en los reportes.', max_length=255),
        ),
        migrations.AlterField(
            model_name='beca',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='distincion',
            name='tipo',
            field=models.CharField(choices=[('PREMIO', 'Premio'), ('DISTINCION', 'Distinción'), ('RECONOCIMIENTO', 'Reconocimiento'), ('MEDALLA', 'Medalla'), ('DIPLOMA', 'Diploma'), ('ESTIMULO', 'Programa de estímulos'), ('BECA', 'Beca'), ('HONORIS_CAUSA', 'Doctorado Honoris Causa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalbeca',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaldistincion',
            name='tipo',
            field=models.CharField(choices=[('PREMIO', 'Premio'), ('DISTINCION', 'Distinción'), ('RECONOCIMIENTO', 'Reconocimiento'), ('MEDALLA', 'Medalla'), ('DIPLOMA', 'Diploma'), ('ESTIMULO', 'Programa de estímulos'), ('BECA', 'Beca'), ('HONORIS_CAUSA', 'Doctorado Honoris Causa')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='beca',
            constraint=models.UniqueConstraint(fields=('nombre', 'institucion'), name='beca_unica'),
        ),
    ]
