# Generated by Django 6.1.1 on 2026-10-01 18:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0030_beca_ayuda_beca_clase_beca_institucion_cargo_ayuda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numero_trabajador',
            field=models.CharField(blank=True, help_text='Clave del académico en la UNAM.', max_length=20, verbose_name='número de trabajador'),
        ),
        migrations.CreateModel(
            name='HistoricalSituacionAcademica',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('pride', models.CharField(blank=True, choices=[('A', 'PRIDE A'), ('B', 'PRIDE B'), ('C', 'PRIDE C'), ('D', 'PRIDE D'), ('EQUIVALENCIA', 'Equivalencia')], max_length=20, verbose_name='PRIDE')),
                ('sni', models.CharField(blank=True, choices=[('C', 'Candidato'), ('I', 'Nivel I'), ('II', 'Nivel II'), ('III', 'Nivel III'), ('E', 'Emérito')], max_length=3, verbose_name='SNII')),
                ('area_sni', models.CharField(blank=True, max_length=30, verbose_name='área SNII')),
                ('contrato', models.CharField(blank=True, choices=[('DEFINITIVO', 'Definitivo'), ('INTERINO', 'Interino'), ('OBRA_DETERMINADA', 'Obra determinada'), ('IXM', 'Investigadoras e Investigadores por México')], max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nombramiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.nombramiento')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical situación académica anual',
                'verbose_name_plural': 'historical situación académica por año',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SituacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('pride', models.CharField(blank=True, choices=[('A', 'PRIDE A'), ('B', 'PRIDE B'), ('C', 'PRIDE C'), ('D', 'PRIDE D'), ('EQUIVALENCIA', 'Equivalencia')], max_length=20, verbose_name='PRIDE')),
                ('sni', models.CharField(blank=True, choices=[('C', 'Candidato'), ('I', 'Nivel I'), ('II', 'Nivel II'), ('III', 'Nivel III'), ('E', 'Emérito')], max_length=3, verbose_name='SNII')),
                ('area_sni', models.CharField(blank=True, max_length=30, verbose_name='área SNII')),
                ('contrato', models.CharField(blank=True, choices=[('DEFINITIVO', 'Definitivo'), ('INTERINO', 'Interino'), ('OBRA_DETERMINADA', 'Obra determinada'), ('IXM', 'Investigadoras e Investigadores por México')], max_length=20)),
                ('nombramiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nucleo.nombramiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'situación académica anual',
                'verbose_name_plural': 'situación académica por año',
                'ordering': ['-anio'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'anio'), name='situacion_unica')],
            },
        ),
    ]
