# Generated by Django 6.1.1 on 2026-10-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0031_situacion_academica'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='numero_vistas',
            field=models.PositiveIntegerField(blank=True, help_text='Reproducciones de la transmisión o del video del evento.', null=True, verbose_name='vistas en línea'),
        ),
        migrations.AddField(
            model_name='historicalevento',
            name='numero_vistas',
            field=models.PositiveIntegerField(blank=True, help_text='Reproducciones de la transmisión o del video del evento.', null=True, verbose_name='vistas en línea'),
        ),
    ]
