# Generated by Django 6.1.1 on 2026-10-01 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0014_pais_de_la_entidad'),
        ('nucleo', '0032_evento_numero_vistas_historicalevento_numero_vistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersona',
            name='genero',
            field=models.CharField(blank=True, choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino'), ('OTRO', 'Otro')], help_text='Para las estadísticas de estudiantes y colaboradores.', max_length=10, verbose_name='género'),
        ),
        migrations.AddField(
            model_name='historicalpersona',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(blank=True, choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino'), ('OTRO', 'Otro')], help_text='Para las estadísticas de estudiantes y colaboradores.', max_length=10, verbose_name='género'),
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cities_light.country'),
        ),
    ]
