# Generated by Django 6.1.1 on 2026-10-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0033_historicalpersona_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstitucion',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('ACADEMICA', 'Académica'), ('FEDERAL', 'Gubernamental federal'), ('ESTATAL', 'Gubernamental estatal'), ('MUNICIPAL', 'Gubernamental municipal'), ('PRIVADA', 'Sector privado'), ('NO_LUCRATIVA', 'Sector privado no lucrativo'), ('COMUNIDAD', 'Comunidad')], max_length=20, verbose_name='clasificación'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('ACADEMICA', 'Académica'), ('FEDERAL', 'Gubernamental federal'), ('ESTATAL', 'Gubernamental estatal'), ('MUNICIPAL', 'Gubernamental municipal'), ('PRIVADA', 'Sector privado'), ('NO_LUCRATIVA', 'Sector privado no lucrativo'), ('COMUNIDAD', 'Comunidad')], max_length=20, verbose_name='clasificación'),
        ),
    ]
