# Generated by Django 6.1.1 on 2026-10-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0014_pais_de_la_entidad"),
        ("nucleo", "0034_alter_historicalinstitucion_clasificacion_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="libro",
            options={"ordering": ["titulo", "numero_edicion"]},
        ),
        migrations.AlterField(
            model_name="historicallibro",
            name="titulo",
            field=models.CharField(max_length=255, verbose_name="título"),
        ),
        migrations.AlterField(
            model_name="libro",
            name="titulo",
            field=models.CharField(max_length=255, verbose_name="título"),
        ),
        migrations.AddConstraint(
            model_name="libro",
            constraint=models.UniqueConstraint(
                fields=("titulo", "numero_edicion"), name="libro_edicion_unica"
            ),
        ),
    ]
