# Generated by Django 6.1.1 on 2026-10-02 20:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleo", "0035_libro_ediciones"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicallibroparticipante",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical autor o coordinador",
                "verbose_name_plural": "historical autores y coordinadores del libro",
            },
        ),
        migrations.AlterModelOptions(
            name="libroparticipante",
            options={
                "ordering": ["orden", "pk"],
                "verbose_name": "autor o coordinador",
                "verbose_name_plural": "autores y coordinadores del libro",
            },
        ),
        migrations.AlterField(
            model_name="historicallibroparticipante",
            name="rol",
            field=models.CharField(
                choices=[
                    ("AUTOR", "Autor del libro completo"),
                    ("EDITOR", "Editor"),
                    ("COORDINADOR", "Coordinador"),
                    ("COMPILADOR", "Compilador"),
                ],
                default="AUTOR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="libroparticipante",
            name="rol",
            field=models.CharField(
                choices=[
                    ("AUTOR", "Autor del libro completo"),
                    ("EDITOR", "Editor"),
                    ("COORDINADOR", "Coordinador"),
                    ("COMPILADOR", "Compilador"),
                ],
                default="AUTOR",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CapituloLibro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=255, verbose_name="título del capítulo"
                    ),
                ),
                (
                    "pagina_inicio",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página inicial"
                    ),
                ),
                (
                    "pagina_fin",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página final"
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capitulos",
                        to="nucleo.libro",
                    ),
                ),
            ],
            options={
                "verbose_name": "capítulo de libro",
                "verbose_name_plural": "capítulos de libros",
                "ordering": ["libro", "pagina_inicio", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="CapituloLibroAutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "capitulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo.capitulolibro",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="nucleo.persona"
                    ),
                ),
            ],
            options={
                "verbose_name": "autor del capítulo",
                "verbose_name_plural": "autores del capítulo",
                "ordering": ["orden", "pk"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="capitulolibro",
            name="autores",
            field=models.ManyToManyField(
                related_name="capitulos",
                through="nucleo.CapituloLibroAutor",
                to="nucleo.persona",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalCapituloLibro",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=255, verbose_name="título del capítulo"
                    ),
                ),
                (
                    "pagina_inicio",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página inicial"
                    ),
                ),
                (
                    "pagina_fin",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página final"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.libro",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical capítulo de libro",
                "verbose_name_plural": "historical capítulos de libros",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCapituloLibroAutor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "capitulo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.capitulolibro",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical autor del capítulo",
                "verbose_name_plural": "historical autores del capítulo",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="capitulolibroautor",
            constraint=models.UniqueConstraint(
                fields=("capitulo", "persona"), name="capitulo_libro_autor_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="capitulolibro",
            constraint=models.UniqueConstraint(
                fields=("titulo", "libro"), name="capitulo_libro_unico"
            ),
        ),
    ]
