# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiencia_laboral', '0001_initial'),
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lineainvestigacion',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='lineainvestigacion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='linea_investigacion_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='lineainvestigacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Cargo'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='nombramiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Nombramiento'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='experiencia_laboral_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacidadpotencialidad',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='capacidad_potencialidad_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='capacidadpotencialidad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lineainvestigacion',
            unique_together=set([('linea_investigacion', 'fecha_inicio', 'usuario')]),
        ),
        migrations.AlterUniqueTogether(
            name='experiencialaboral',
            unique_together=set([('dependencia', 'cargo', 'fecha_fin', 'usuario')]),
        ),
        migrations.AlterUniqueTogether(
            name='capacidadpotencialidad',
            unique_together=set([('competencia', 'usuario')]),
        ),
    ]
