# Generated by Django 2.0.1 on 2018-01-08 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experiencia_laboral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineainvestigacion',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='lineainvestigacion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='lineainvestigacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Cargo'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='nombramiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Nombramiento'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacidadpotencialidad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lineainvestigacion',
            unique_together={('linea_investigacion', 'fecha_inicio', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='experiencialaboral',
            unique_together={('dependencia', 'cargo', 'fecha_fin', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='capacidadpotencialidad',
            unique_together={('nombre', 'usuario')},
        ),
    ]
