# Generated by Django 2.0.5 on 2018-05-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_laboral', '0002_auto_20180503_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='es_nombramiento_definitivo',
        ),
    ]
