# Generated by Django 2.0.6 on 2018-11-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_laboral', '0002_auto_20180803_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='lineainvestigacion',
            name='institucion',
        ),
    ]
