# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 01:24
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='actividad', unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='ApoyoOtraActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('apoyo_inicio', models.DateField()),
                ('apoyo_fin', models.DateField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='apoyo_otra_actividad_tags', unique=True)),
                ('apoyo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyo_institucional.Actividad')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia')),
                ('tags', models.ManyToManyField(blank=True, related_name='apoyo_otra_actividad_tags', to='nucleo.Tag')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ubicacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['user', 'apoyo_actividad'],
                'verbose_name_plural': 'Apoyos en Otras Actividades',
                'ordering': ['-apoyo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ApoyoTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('apoyo_inicio', models.DateField()),
                ('apoyo_fin', models.DateField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='apoyo_tecnico', unique=True)),
                ('apoyo_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyo_institucional.Actividad')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia')),
                ('tags', models.ManyToManyField(blank=True, related_name='apoyo_tecnico_tags', to='nucleo.Tag')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ubicacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['user', 'apoyo_tecnico'],
                'verbose_name_plural': 'Apoyos de Técnicos',
                'ordering': ['-apoyo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CargoAcademicoAdministrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('cargo_inicio', models.DateField()),
                ('cargo_fin', models.DateField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='cargo', unique=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Cargo')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia')),
                ('tags', models.ManyToManyField(blank=True, related_name='cargo_academico_administrativo_tags', to='nucleo.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['user', 'cargo'],
                'verbose_name_plural': 'Cargos Académico-Administrativos',
                'ordering': ['-cargo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='comision', unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Comisiones',
            },
        ),
        migrations.CreateModel(
            name='ComisionAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='comision_academica', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('es_evaluacion', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('comision_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyo_institucional.Comision')),
                ('dependencias', models.ManyToManyField(to='nucleo.Dependencia')),
                ('tags', models.ManyToManyField(blank=True, related_name='comision_academica_tags', to='nucleo.Tag')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ubicacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['user', 'comision_academica'],
                'verbose_name_plural': 'Comisiones Académicas',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Representacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representacion', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='representacion', unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Representación',
                'ordering': ['representacion'],
                'verbose_name_plural': 'Representaciones',
            },
        ),
        migrations.CreateModel(
            name='RepresentanteAnteOrganoColegiado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('cargo_inicio', models.DateField()),
                ('cargo_fin', models.DateField()),
                ('ante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Departamento')),
                ('representacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyo_institucional.Representacion')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='representante_ante_organo_colegiado_tags', to='nucleo.Tag')),
            ],
            options={
                'ordering': ['-cargo_inicio'],
                'verbose_name_plural': 'Representantes Ante Organos Colegiados',
            },
        ),
        migrations.AlterUniqueTogether(
            name='representanteanteorganocolegiado',
            unique_together=set([('representante', 'representacion', 'cargo_inicio')]),
        ),
        migrations.AlterUniqueTogether(
            name='comisionacademica',
            unique_together=set([('comision_academica', 'user', 'fecha_inicio')]),
        ),
        migrations.AlterUniqueTogether(
            name='cargoacademicoadministrativo',
            unique_together=set([('cargo', 'user', 'dependencia', 'cargo_inicio')]),
        ),
        migrations.AlterUniqueTogether(
            name='apoyotecnico',
            unique_together=set([('apoyo_tecnico', 'user', 'dependencia', 'apoyo_inicio')]),
        ),
        migrations.AlterUniqueTogether(
            name='apoyootraactividad',
            unique_together=set([('apoyo_actividad', 'user', 'dependencia', 'apoyo_inicio')]),
        ),
    ]
