# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 19:32
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='actividad', unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='ApoyoOtraActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('apoyo_inicio', models.DateField()),
                ('apoyo_fin', models.DateField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='apoyo_otra_actividad_tags', unique=True)),
            ],
            options={
                'get_latest_by': ['user', 'apoyo_actividad'],
                'verbose_name_plural': 'Apoyos en Otras Actividades',
                'ordering': ['-apoyo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ApoyoTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('apoyo_inicio', models.DateField()),
                ('apoyo_fin', models.DateField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='apoyo_tecnico', unique=True)),
            ],
            options={
                'get_latest_by': ['user', 'apoyo_tecnico'],
                'verbose_name_plural': 'Apoyos de Técnicos',
                'ordering': ['-apoyo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CargoAcademicoAdministrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('cargo_inicio', models.DateField()),
                ('cargo_fin', models.DateField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='cargo', unique=True)),
            ],
            options={
                'get_latest_by': ['user', 'cargo'],
                'verbose_name_plural': 'Cargos Académico-Administrativos',
                'ordering': ['-cargo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='comision', unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Comisiones',
            },
        ),
        migrations.CreateModel(
            name='ComisionAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='comision_academica', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('es_evaluacion', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'get_latest_by': ['user', 'comision_academica'],
                'verbose_name_plural': 'Comisiones Académicas',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Representacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representacion', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='representacion', unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Representación',
                'verbose_name_plural': 'Representaciones',
                'ordering': ['representacion'],
            },
        ),
        migrations.CreateModel(
            name='RepresentanteAnteOrganoColegiado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('cargo_inicio', models.DateField()),
                ('cargo_fin', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Representantes Ante Organos Colegiados',
                'ordering': ['-cargo_inicio'],
            },
        ),
    ]
