# Generated by Django 2.0.1 on 2018-01-29 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
        ('apoyo_institucional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representacionorganocolegiado',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='representacionorganocolegiado',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='representacionorganocolegiado',
            name='representacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apoyo_institucional.Representacion'),
        ),
        migrations.AddField(
            model_name='representacionorganocolegiado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comisionacademica',
            name='comision_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apoyo_institucional.Comision'),
        ),
        migrations.AddField(
            model_name='comisionacademica',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='comisionacademica',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='comisionacademica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargoacademicoadministrativo',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Cargo'),
        ),
        migrations.AddField(
            model_name='cargoacademicoadministrativo',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='cargoacademicoadministrativo',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='cargoacademicoadministrativo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apoyotecnico',
            name='actividad_apoyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apoyo_institucional.ActividadApoyo'),
        ),
        migrations.AddField(
            model_name='apoyotecnico',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='apoyotecnico',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='apoyotecnico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apoyootraactividad',
            name='actividad_apoyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apoyo_institucional.ActividadApoyo'),
        ),
        migrations.AddField(
            model_name='apoyootraactividad',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='apoyootraactividad',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='apoyootraactividad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='representacionorganocolegiado',
            unique_together={('usuario', 'representacion', 'fecha_inicio')},
        ),
        migrations.AlterUniqueTogether(
            name='comisionacademica',
            unique_together={('comision_academica', 'usuario', 'fecha_inicio')},
        ),
        migrations.AlterUniqueTogether(
            name='cargoacademicoadministrativo',
            unique_together={('cargo', 'usuario', 'dependencia', 'fecha_inicio')},
        ),
        migrations.AlterUniqueTogether(
            name='apoyotecnico',
            unique_together={('actividad_apoyo', 'usuario', 'dependencia', 'fecha_inicio')},
        ),
        migrations.AlterUniqueTogether(
            name='apoyootraactividad',
            unique_together={('actividad_apoyo', 'usuario', 'dependencia', 'fecha_inicio')},
        ),
    ]
