# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 01:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apoyo_institucional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representacionorganocolegiado',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='representacionorganocolegiado',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='representacionorganocolegiado',
            name='representacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyo_institucional.Representacion'),
        ),
        migrations.AddField(
            model_name='representacionorganocolegiado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comisionacademica',
            name='comision_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyo_institucional.Comision'),
        ),
        migrations.AddField(
            model_name='comisionacademica',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='comisionacademica',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='comisionacademica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargoacademicoadministrativo',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Cargo'),
        ),
        migrations.AddField(
            model_name='cargoacademicoadministrativo',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='cargoacademicoadministrativo',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='cargoacademicoadministrativo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apoyotecnico',
            name='actividad_apoyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyo_institucional.ActividadApoyo'),
        ),
        migrations.AddField(
            model_name='apoyotecnico',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='apoyotecnico',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='apoyotecnico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apoyootraactividad',
            name='actividad_apoyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyo_institucional.ActividadApoyo'),
        ),
        migrations.AddField(
            model_name='apoyootraactividad',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='apoyootraactividad',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='apoyootraactividad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='representacionorganocolegiado',
            unique_together=set([('usuario', 'representacion', 'fecha_inicio')]),
        ),
        migrations.AlterUniqueTogether(
            name='comisionacademica',
            unique_together=set([('comision_academica', 'usuario', 'fecha_inicio')]),
        ),
        migrations.AlterUniqueTogether(
            name='cargoacademicoadministrativo',
            unique_together=set([('cargo', 'usuario', 'dependencia', 'fecha_inicio')]),
        ),
        migrations.AlterUniqueTogether(
            name='apoyotecnico',
            unique_together=set([('actividad_apoyo', 'usuario', 'dependencia', 'fecha_inicio')]),
        ),
        migrations.AlterUniqueTogether(
            name='apoyootraactividad',
            unique_together=set([('actividad_apoyo', 'usuario', 'dependencia', 'fecha_inicio')]),
        ),
    ]
