# Generated by Django 2.0.6 on 2018-11-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apoyo_institucional', '0002_auto_20180803_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoyootraactividad',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='apoyotecnico',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='cargoacademicoadministrativo',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='comisionacademica',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='representacionorganocolegiado',
            name='institucion',
        ),
    ]
