# Generated by Django 2.0.6 on 2018-12-05 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0011_auto_20181205_1300'),
        ('apoyo_institucional', '0003_auto_20181112_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoyootraactividad',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apoyotecnico',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargoacademicoadministrativo',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comisionacademica',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='representacionorganocolegiado',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
            preserve_default=False,
        ),
    ]
