# Generated by Django 6.1.1 on 2026-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticuloDocencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENVIADO", "Enviado"),
                            ("ACEPTADO", "Aceptado"),
                            ("EN_PRENSA", "En prensa"),
                            ("PUBLICADO", "Publicado"),
                        ],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("fecha_enviado", models.DateField(blank=True, null=True)),
                ("fecha_aceptado", models.DateField(blank=True, null=True)),
                (
                    "fecha_enprensa",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha en prensa"
                    ),
                ),
                ("fecha_publicado", models.DateField(blank=True, null=True)),
                (
                    "titulo",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="título"
                    ),
                ),
                (
                    "pagina_inicio",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página inicial"
                    ),
                ),
                (
                    "pagina_fin",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página final"
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "solo_electronico",
                    models.BooleanField(default=False, verbose_name="solo electrónico"),
                ),
            ],
            options={
                "verbose_name": "artículo para docencia",
                "verbose_name_plural": "artículos para docencia",
                "ordering": [
                    "-fecha_publicado",
                    "-fecha_enprensa",
                    "-fecha_aceptado",
                    "-fecha_enviado",
                    "titulo",
                ],
            },
        ),
        migrations.CreateModel(
            name="ArticuloDocenciaAutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "autor",
                "verbose_name_plural": "autores",
                "ordering": ["orden", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CursoEscolarizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("LICENCIATURA", "Licenciatura"),
                            ("MAESTRIA", "Maestría"),
                            ("DOCTORADO", "Doctorado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("PRESENCIAL", "Presencial"),
                            ("EN_LINEA", "En línea"),
                            ("MIXTO", "Mixto"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nombramiento",
                    models.CharField(
                        choices=[
                            ("TITULAR", "Titular o coordinador"),
                            ("COLABORADOR", "Colaborador o invitado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "periodo_academico",
                    models.CharField(max_length=20, verbose_name="periodo académico"),
                ),
                (
                    "total_horas",
                    models.PositiveIntegerField(verbose_name="total de horas"),
                ),
            ],
            options={
                "verbose_name": "curso escolarizado",
                "verbose_name_plural": "cursos escolarizados",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="CursoExtracurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CURSO", "Curso"),
                            ("DIPLOMADO", "Diplomado"),
                            ("TALLER", "Taller"),
                            ("SEMINARIO", "Seminario"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_otro",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="otro tipo"
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APOYO_POSGRADO", "En apoyo al posgrado"),
                            ("CAPACITACION", "Curso de capacitación"),
                        ],
                        max_length=20,
                        verbose_name="clasificación",
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("PRESENCIAL", "Presencial"),
                            ("EN_LINEA", "En línea"),
                            ("MIXTO", "Mixto"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "periodo_academico",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="periodo académico"
                    ),
                ),
                (
                    "total_horas",
                    models.PositiveIntegerField(verbose_name="total de horas"),
                ),
            ],
            options={
                "verbose_name": "curso extracurricular",
                "verbose_name_plural": "cursos extracurriculares",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ProgramaEstudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=254)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("LICENCIATURA", "Licenciatura"),
                            ("MAESTRIA", "Maestría"),
                            ("DOCTORADO", "Doctorado"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField()),
            ],
            options={
                "verbose_name": "programa de estudio",
                "verbose_name_plural": "programas de estudio",
                "ordering": ["-fecha", "nombre"],
            },
        ),
    ]
