# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
        ('investigacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaestudio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cursodocenciaextracurricular',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Asignatura'),
        ),
        migrations.AddField(
            model_name='cursodocenciaextracurricular',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='cursodocenciaextracurricular',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='cursodocenciaextracurricular',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_docencia_extracurricular_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cursodocenciaescolarizado',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Asignatura'),
        ),
        migrations.AddField(
            model_name='cursodocenciaescolarizado',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='cursodocenciaescolarizado',
            name='doctorado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaDoctorado'),
        ),
        migrations.AddField(
            model_name='cursodocenciaescolarizado',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='cursodocenciaescolarizado',
            name='licenciatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaLicenciatura'),
        ),
        migrations.AddField(
            model_name='cursodocenciaescolarizado',
            name='maestria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaMaestria'),
        ),
        migrations.AddField(
            model_name='cursodocenciaescolarizado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_docencia_escolarizado_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulodocencia',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='articulo_docencia_alumnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulodocencia',
            name='indices',
            field=models.ManyToManyField(blank=True, related_name='articulo_docencia_indices', to='nucleo.Indice'),
        ),
        migrations.AddField(
            model_name='articulodocencia',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.ProyectoInvestigacion'),
        ),
        migrations.AddField(
            model_name='articulodocencia',
            name='revista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Revista'),
        ),
        migrations.AddField(
            model_name='articulodocencia',
            name='usuarios',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='articulo_docencia_autores', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
    ]
