# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 00:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docencia', '0001_initial'),
        ('formacion_academica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_escolarizado_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='doctorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion_academica.Doctorado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='licenciatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion_academica.Licenciatura'),
        ),
        migrations.AddField(
            model_name='curso',
            name='maestria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion_academica.Maestria'),
        ),
        migrations.AddField(
            model_name='curso',
            name='otras_dependencias_participantes',
            field=models.ManyToManyField(blank=True, related_name='curso_escolarizado_otras_dependencias_participantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='otros_academicos',
            field=models.ManyToManyField(blank=True, related_name='curso_escolarizado_otros_academicos', to=settings.AUTH_USER_MODEL),
        ),
    ]
