# Generated by Django 6.1.1 on 2026-09-26 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("docencia", "0001_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="articulodocencia",
            name="agradecimientos",
            field=models.ManyToManyField(
                blank=True,
                related_name="articulos_docencia_agradecimiento",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="articulodocencia",
            name="alumnos",
            field=models.ManyToManyField(
                blank=True,
                related_name="articulos_docencia_alumno",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="articulodocenciaautor",
            name="articulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="docencia.articulodocencia",
            ),
        ),
        migrations.AddField(
            model_name="articulodocenciaautor",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="articulodocencia",
            name="autores",
            field=models.ManyToManyField(
                related_name="articulos_docencia",
                through="docencia.ArticuloDocenciaAutor",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="cursoescolarizado",
            name="asignatura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.asignatura"
            ),
        ),
        migrations.AddField(
            model_name="cursoescolarizado",
            name="institucion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="cursoescolarizado",
            name="programa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.programaacademico",
            ),
        ),
        migrations.AddField(
            model_name="cursoescolarizado",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cursos_escolarizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cursoextracurricular",
            name="asignatura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.asignatura",
                verbose_name="nombre del curso",
            ),
        ),
        migrations.AddField(
            model_name="cursoextracurricular",
            name="institucion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="cursoextracurricular",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cursos_extracurriculares",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="programaestudio",
            name="institucion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="programaestudio",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programas_estudio",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="articulodocenciaautor",
            constraint=models.UniqueConstraint(
                fields=("articulo", "persona"), name="articulo_docencia_autor_unico"
            ),
        ),
    ]
