# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docencia', '0002_auto_20171004_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursodocencia',
            name='academicos_participantes',
            field=models.ManyToManyField(blank=True, related_name='cursodocencia_academicos_participantes', to=settings.AUTH_USER_MODEL, verbose_name='Académicos participantes'),
        ),
        migrations.AlterField(
            model_name='cursodocencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursodocencia_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
