# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0003_remove_capitulolibroinvestigacion_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0006_auto_20171117_0923'),
        ('docencia', '0002_auto_20171102_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloDocencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('volumen', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('issn_impreso', models.CharField(blank=True, max_length=40, verbose_name='ISSN Impreso')),
                ('issn_online', models.CharField(blank=True, max_length=40, verbose_name='ISSN Online')),
                ('status', models.CharField(choices=[('', '-------'), ('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('EN_PRENSA', 'En prensa'), ('PUBLICADO', 'Publicado'), ('OTRO', 'Otro')], max_length=20)),
                ('solo_electronico', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
                ('id_doi', models.CharField(blank=True, max_length=100, null=True)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='articulo_docencia_alumnos', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.ProyectoInvestigacion')),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Revista')),
                ('usuarios', sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='articulo_dcencia_autores', to=settings.AUTH_USER_MODEL, verbose_name='Autores')),
            ],
            options={
                'verbose_name': 'Artículo para docencia',
                'verbose_name_plural': 'Artículos para docencia',
                'ordering': ['fecha', 'titulo'],
            },
        ),
    ]
