# Generated by Django 6.1.1 on 2026-09-26 18:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docencia", "0002_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalArticuloDocencia",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENVIADO", "Enviado"),
                            ("ACEPTADO", "Aceptado"),
                            ("EN_PRENSA", "En prensa"),
                            ("PUBLICADO", "Publicado"),
                        ],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("fecha_enviado", models.DateField(blank=True, null=True)),
                ("fecha_aceptado", models.DateField(blank=True, null=True)),
                (
                    "fecha_enprensa",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha en prensa"
                    ),
                ),
                ("fecha_publicado", models.DateField(blank=True, null=True)),
                (
                    "titulo",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="título"
                    ),
                ),
                (
                    "pagina_inicio",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página inicial"
                    ),
                ),
                (
                    "pagina_fin",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página final"
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "solo_electronico",
                    models.BooleanField(default=False, verbose_name="solo electrónico"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical artículo para docencia",
                "verbose_name_plural": "historical artículos para docencia",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalArticuloDocenciaAutor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="docencia.articulodocencia",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical autor",
                "verbose_name_plural": "historical autores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCursoEscolarizado",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("LICENCIATURA", "Licenciatura"),
                            ("MAESTRIA", "Maestría"),
                            ("DOCTORADO", "Doctorado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("PRESENCIAL", "Presencial"),
                            ("EN_LINEA", "En línea"),
                            ("MIXTO", "Mixto"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nombramiento",
                    models.CharField(
                        choices=[
                            ("TITULAR", "Titular o coordinador"),
                            ("COLABORADOR", "Colaborador o invitado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "periodo_academico",
                    models.CharField(max_length=20, verbose_name="periodo académico"),
                ),
                (
                    "total_horas",
                    models.PositiveIntegerField(verbose_name="total de horas"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.asignatura",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.programaacademico",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical curso escolarizado",
                "verbose_name_plural": "historical cursos escolarizados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCursoExtracurricular",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CURSO", "Curso"),
                            ("DIPLOMADO", "Diplomado"),
                            ("TALLER", "Taller"),
                            ("SEMINARIO", "Seminario"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_otro",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="otro tipo"
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APOYO_POSGRADO", "En apoyo al posgrado"),
                            ("CAPACITACION", "Curso de capacitación"),
                        ],
                        max_length=20,
                        verbose_name="clasificación",
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("PRESENCIAL", "Presencial"),
                            ("EN_LINEA", "En línea"),
                            ("MIXTO", "Mixto"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "periodo_academico",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="periodo académico"
                    ),
                ),
                (
                    "total_horas",
                    models.PositiveIntegerField(verbose_name="total de horas"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.asignatura",
                        verbose_name="nombre del curso",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical curso extracurricular",
                "verbose_name_plural": "historical cursos extracurriculares",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProgramaEstudio",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=254)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("LICENCIATURA", "Licenciatura"),
                            ("MAESTRIA", "Maestría"),
                            ("DOCTORADO", "Doctorado"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical programa de estudio",
                "verbose_name_plural": "historical programas de estudio",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
