# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docencia', '0003_articulodocencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.CharField(choices=[('', '-------'), ('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado'), ('OTRO', 'Otro')], max_length=20)),
                ('fecha', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programa de estudio',
                'verbose_name_plural': 'Programas de estudio',
                'ordering': ['-fecha', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='articulodocencia',
            options={'ordering': ['-fecha', 'titulo'], 'verbose_name': 'Artículo para docencia', 'verbose_name_plural': 'Artículos para docencia'},
        ),
    ]
