# Generated by Django 2.0.6 on 2018-11-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docencia', '0004_auto_20181031_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursodocenciaescolarizado',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='cursodocenciaextracurricular',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='programaestudio',
            name='institucion',
        ),
    ]
