# Generated by Django 6.1.1 on 2026-10-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docencia', '0005_fechas_vacias_a_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoescolarizado',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='cursoextracurricular',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalcursoescolarizado',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalcursoextracurricular',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
    ]
