# Generated by Django 6.1.1 on 2026-10-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docencia', '0006_fechas_obligatorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoextracurricular',
            name='numero_asistentes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='asistentes'),
        ),
        migrations.AddField(
            model_name='historicalcursoextracurricular',
            name='numero_asistentes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='asistentes'),
        ),
    ]
