# Generated by Django 6.1.1 on 2026-10-03 01:33

import django.db.models.deletion
import informes.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Informe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "periodo",
                    models.CharField(
                        help_text="De julio a junio, p. ej. «2025-2026».",
                        max_length=9,
                        validators=[informes.models.validar_periodo],
                    ),
                ),
                (
                    "es_plantilla",
                    models.BooleanField(
                        default=False,
                        help_text="Aparece como punto de partida para informes nuevos.",
                        verbose_name="es plantilla",
                    ),
                ),
                (
                    "pie",
                    models.CharField(
                        blank=True,
                        default="{entidad} · {institucion} — Informe Anual {periodo}",
                        help_text="Se puede usar {entidad}, {institucion}, {periodo}, {anio}, {inicio} y {fin}.",
                        max_length=255,
                        verbose_name="pie de las gráficas",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "basado_en",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derivados",
                        to="informes.informe",
                        verbose_name="basado en",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-es_plantilla", "-periodo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalInforme",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "periodo",
                    models.CharField(
                        help_text="De julio a junio, p. ej. «2025-2026».",
                        max_length=9,
                        validators=[informes.models.validar_periodo],
                    ),
                ),
                (
                    "es_plantilla",
                    models.BooleanField(
                        default=False,
                        help_text="Aparece como punto de partida para informes nuevos.",
                        verbose_name="es plantilla",
                    ),
                ),
                (
                    "pie",
                    models.CharField(
                        blank=True,
                        default="{entidad} · {institucion} — Informe Anual {periodo}",
                        help_text="Se puede usar {entidad}, {institucion}, {periodo}, {anio}, {inicio} y {fin}.",
                        max_length=255,
                        verbose_name="pie de las gráficas",
                    ),
                ),
                ("creado", models.DateTimeField(blank=True, editable=False)),
                ("actualizado", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "basado_en",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="informes.informe",
                        verbose_name="basado en",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical informe",
                "verbose_name_plural": "historical informes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalGrafica",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "seccion",
                    models.CharField(
                        blank=True,
                        help_text="Encabezado bajo el que va la gráfica, p. ej. «Eje 2 · Investigación».",
                        max_length=255,
                        verbose_name="sección",
                    ),
                ),
                (
                    "indicador",
                    models.CharField(
                        choices=[
                            (
                                "planta",
                                "Planta académica por categoría, nivel y género",
                            ),
                            ("antiguedad", "Antigüedad por categoría y nivel"),
                            ("contratos", "Personal por tipo de contrato (histórico)"),
                            (
                                "proyectos_financiamiento",
                                "Proyectos por instancia financiadora (histórico)",
                            ),
                            ("tipos_proyectos", "Tipos de proyectos"),
                            ("ods", "Proyectos por Objetivo de Desarrollo Sostenible"),
                            ("prioridades", "Problemas nacionales prioritarios"),
                            ("publicaciones", "Productos publicados por tipo y origen"),
                            (
                                "cuartiles",
                                "Cuartil y factor de impacto de las revistas",
                            ),
                            ("pride", "Planta por nivel del PRIDE (histórico)"),
                            ("snii", "Académicos por nivel del SNII (histórico)"),
                            ("vinculacion", "Acciones de vinculación académica"),
                            (
                                "cursos_posgrado",
                                "Cursos de posgrado por programa, categoría y participación",
                            ),
                            ("tesis", "Tesis concluidas y en proceso"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("columnas", "Columnas"),
                            ("barras", "Barras horizontales"),
                            ("rango", "Rango y promedio"),
                            ("pastillas", "Comparación por periodos"),
                            ("dona", "Dona"),
                            ("anillos", "Anillos (jerarquía)"),
                            ("rosa", "Rosa polar"),
                            ("semicirculo", "Semicírculo por grupos"),
                            ("tabla", "Tabla"),
                        ],
                        max_length=20,
                        verbose_name="tipo de gráfica",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Se puede usar {entidad}, {periodo}, {anio}, {inicio} y {fin}.",
                        max_length=255,
                        verbose_name="título",
                    ),
                ),
                (
                    "subtitulo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="subtítulo"
                    ),
                ),
                (
                    "nota",
                    models.TextField(
                        blank=True,
                        help_text="Texto que acompaña a la gráfica en el documento.",
                    ),
                ),
                (
                    "periodos",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Para las gráficas históricas: cuántos periodos, hasta el del informe.",
                        verbose_name="periodos a mostrar",
                    ),
                ),
                (
                    "colores",
                    models.CharField(
                        blank=True,
                        help_text="Opcional: colores de las series, p. ej. «#7A8B3A, #4A7C8C».",
                        max_length=255,
                        validators=[informes.models.validar_colores],
                    ),
                ),
                (
                    "mostrar_total",
                    models.BooleanField(default=True, verbose_name="mostrar el total"),
                ),
                (
                    "mostrar_valores",
                    models.BooleanField(
                        default=True, verbose_name="mostrar los valores"
                    ),
                ),
                (
                    "apilado",
                    models.BooleanField(default=True, verbose_name="series apiladas"),
                ),
                ("visible", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "informe",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="informes.informe",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical gráfica",
                "verbose_name_plural": "historical gráficas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Grafica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "seccion",
                    models.CharField(
                        blank=True,
                        help_text="Encabezado bajo el que va la gráfica, p. ej. «Eje 2 · Investigación».",
                        max_length=255,
                        verbose_name="sección",
                    ),
                ),
                (
                    "indicador",
                    models.CharField(
                        choices=[
                            (
                                "planta",
                                "Planta académica por categoría, nivel y género",
                            ),
                            ("antiguedad", "Antigüedad por categoría y nivel"),
                            ("contratos", "Personal por tipo de contrato (histórico)"),
                            (
                                "proyectos_financiamiento",
                                "Proyectos por instancia financiadora (histórico)",
                            ),
                            ("tipos_proyectos", "Tipos de proyectos"),
                            ("ods", "Proyectos por Objetivo de Desarrollo Sostenible"),
                            ("prioridades", "Problemas nacionales prioritarios"),
                            ("publicaciones", "Productos publicados por tipo y origen"),
                            (
                                "cuartiles",
                                "Cuartil y factor de impacto de las revistas",
                            ),
                            ("pride", "Planta por nivel del PRIDE (histórico)"),
                            ("snii", "Académicos por nivel del SNII (histórico)"),
                            ("vinculacion", "Acciones de vinculación académica"),
                            (
                                "cursos_posgrado",
                                "Cursos de posgrado por programa, categoría y participación",
                            ),
                            ("tesis", "Tesis concluidas y en proceso"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("columnas", "Columnas"),
                            ("barras", "Barras horizontales"),
                            ("rango", "Rango y promedio"),
                            ("pastillas", "Comparación por periodos"),
                            ("dona", "Dona"),
                            ("anillos", "Anillos (jerarquía)"),
                            ("rosa", "Rosa polar"),
                            ("semicirculo", "Semicírculo por grupos"),
                            ("tabla", "Tabla"),
                        ],
                        max_length=20,
                        verbose_name="tipo de gráfica",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Se puede usar {entidad}, {periodo}, {anio}, {inicio} y {fin}.",
                        max_length=255,
                        verbose_name="título",
                    ),
                ),
                (
                    "subtitulo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="subtítulo"
                    ),
                ),
                (
                    "nota",
                    models.TextField(
                        blank=True,
                        help_text="Texto que acompaña a la gráfica en el documento.",
                    ),
                ),
                (
                    "periodos",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Para las gráficas históricas: cuántos periodos, hasta el del informe.",
                        verbose_name="periodos a mostrar",
                    ),
                ),
                (
                    "colores",
                    models.CharField(
                        blank=True,
                        help_text="Opcional: colores de las series, p. ej. «#7A8B3A, #4A7C8C».",
                        max_length=255,
                        validators=[informes.models.validar_colores],
                    ),
                ),
                (
                    "mostrar_total",
                    models.BooleanField(default=True, verbose_name="mostrar el total"),
                ),
                (
                    "mostrar_valores",
                    models.BooleanField(
                        default=True, verbose_name="mostrar los valores"
                    ),
                ),
                (
                    "apilado",
                    models.BooleanField(default=True, verbose_name="series apiladas"),
                ),
                ("visible", models.BooleanField(default=True)),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graficas",
                        to="informes.informe",
                    ),
                ),
            ],
            options={
                "verbose_name": "gráfica",
                "verbose_name_plural": "gráficas",
                "ordering": ["informe", "orden", "pk"],
            },
        ),
    ]
