# Generated by Django 6.1.1 on 2026-10-03 02:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0002_plantilla_informe_anual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalEmision",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(verbose_name="versión")),
                ("periodo", models.CharField(max_length=9)),
                (
                    "emitido_en",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="emitido el"
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        blank=True,
                        help_text="Obligatorio desde la segunda versión: qué cambió y por qué.",
                    ),
                ),
                ("datos", models.JSONField(editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "emitido_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="emitido por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "informe",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="informes.informe",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical emisión",
                "verbose_name_plural": "historical emisiones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Emision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(verbose_name="versión")),
                ("periodo", models.CharField(max_length=9)),
                (
                    "emitido_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="emitido el"),
                ),
                (
                    "motivo",
                    models.TextField(
                        blank=True,
                        help_text="Obligatorio desde la segunda versión: qué cambió y por qué.",
                    ),
                ),
                ("datos", models.JSONField(editable=False)),
                (
                    "emitido_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="emitido por",
                    ),
                ),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emisiones",
                        to="informes.informe",
                    ),
                ),
            ],
            options={
                "verbose_name": "emisión",
                "verbose_name_plural": "emisiones",
                "ordering": ["informe", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("informe", "version"), name="emision_version_unica"
                    )
                ],
            },
        ),
    ]
