# Generated by Django 6.1.1 on 2026-10-03 03:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0003_emisiones"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CifraHistorica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indicador", models.CharField(max_length=40)),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        help_text="Año de corte (agosto); el periodo 2020-2021 es 2021.",
                        verbose_name="año",
                    ),
                ),
                (
                    "panel",
                    models.CharField(
                        blank=True,
                        help_text="P. ej. «Investigadores»; vacío si no aplica.",
                        max_length=100,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(max_length=100, verbose_name="categoría"),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fuente", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "cifra histórica",
                "verbose_name_plural": "cifras históricas",
                "ordering": ["indicador", "anio", "panel", "categoria"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("indicador", "anio", "panel", "categoria"),
                        name="cifra_historica_unica",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCifraHistorica",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("indicador", models.CharField(max_length=40)),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        help_text="Año de corte (agosto); el periodo 2020-2021 es 2021.",
                        verbose_name="año",
                    ),
                ),
                (
                    "panel",
                    models.CharField(
                        blank=True,
                        help_text="P. ej. «Investigadores»; vacío si no aplica.",
                        max_length=100,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(max_length=100, verbose_name="categoría"),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fuente", models.CharField(blank=True, max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cifra histórica",
                "verbose_name_plural": "historical cifras históricas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
