# Generated by Django 2.0.2 on 2018-02-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsesoriaEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('', 'Seleccionar tipo de Asesoría'), ('RESIDENCIA', 'Residencia'), ('PRACTICA', 'Prácticas profesionales'), ('ESTANCIA', 'Estancia de investigación'), ('BECARIO', 'Becario de proyecto de investigación'), ('SERVICIO_SOCIAL', 'Servicio Social')], max_length=30)),
                ('nivel_academico', models.CharField(choices=[('', '-------'), ('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=20)),
                ('periodo_academico', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Asesoría en residencias / prácticas / estancias / servicio social',
                'verbose_name_plural': 'Asesorías en residencias / prácticas / estancias / servicio social',
                'ordering': ['-fecha_inicio', '-fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='ComiteCandidaturaDoctoral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_defensa', models.DateField()),
            ],
            options={
                'verbose_name': 'Comité de examen de candidatura doctoral',
                'verbose_name_plural': 'Comités de exámenes de candidatura doctoral',
                'ordering': ['-fecha_defensa'],
            },
        ),
        migrations.CreateModel(
            name='ComiteTutoral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_academico', models.CharField(choices=[('', '-------'), ('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_examen', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comité tutoral',
                'verbose_name_plural': 'Comités tutorales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DesarrolloGrupoInvestigacionInterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('grado_consolidacion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Área o grupo de investigación interno',
                'verbose_name_plural': 'Áreas o grupos de investigación internos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DireccionTesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('especialidad', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('grado_academico', models.CharField(choices=[('', '-------'), ('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=20)),
                ('documento_tesis', models.FileField(blank=True, null=True, upload_to='')),
                ('fecha_examen', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dirección de tesis',
                'verbose_name_plural': 'Direcciones de tesis',
                'ordering': ['-fecha_examen'],
            },
        ),
        migrations.CreateModel(
            name='SupervisionInvestigadorPostDoctoral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Supervisión de investigador postdoctoral',
                'verbose_name_plural': 'Supervisiones de investigadores postdoctorales',
                'ordering': ['-fecha_inicio', '-fecha_fin'],
            },
        ),
    ]
