# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formacion_recursos_humanos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
        ('investigacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciontesis',
            name='asesorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_tesis_asesorado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='beca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Beca'),
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='usuarios',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='direccion_tesis_usuarios', to=settings.AUTH_USER_MODEL, verbose_name='Tutores'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='asesor_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comite_tutoral_asesor_principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='asesorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comite_tutoral_asesorado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='otros_asesores',
            field=models.ManyToManyField(blank=True, related_name='comite_tutoral_otros_asesores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='programa_doctorado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaDoctorado'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='programa_maestria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaMaestria'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.ProyectoInvestigacion'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='sinodales',
            field=models.ManyToManyField(blank=True, related_name='comite_tutoral_sinodales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='asesor_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comite_candidatura_doctoral_asesor_principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='asesorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comite_candidatura_doctoral_asesorado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='otros_asesores',
            field=models.ManyToManyField(blank=True, related_name='comite_candidatura_doctoral_otros_asesores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='programa_doctorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaDoctorado'),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.ProyectoInvestigacion'),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='sinodales',
            field=models.ManyToManyField(blank=True, related_name='comite_candidatura_doctoral_sinodales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='asesorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesoria_estudiante_asesorado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='beca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Beca'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='programa_doctorado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaDoctorado'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='programa_licenciatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaLicenciatura'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='programa_maestria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaMaestria'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.ProyectoInvestigacion'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesoria_estudiante_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='asesoriaestudiante',
            unique_together=set([('usuario', 'asesorado', 'nivel_academico')]),
        ),
    ]
