# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formacion_recursos_humanos', '0001_initial'),
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciontesis',
            name='asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_tesis_asesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='tesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Tesis'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comite_tutoral_alumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='asesor_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comite_tutoral_asesor_principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='otros_asesores',
            field=models.ManyToManyField(blank=True, related_name='comite_tutoral_otros_asesores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='programa_doctorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaDoctorado'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='programa_maestria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaMaestria'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Proyecto'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='sinodales',
            field=models.ManyToManyField(blank=True, related_name='comite_tutoral_sinodales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comite_candidatura_doctoral_alumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='asesor_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comite_candidatura_doctoral_asesor_principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='otros_asesores',
            field=models.ManyToManyField(blank=True, related_name='comite_candidatura_doctoral_otros_asesores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='programa_doctorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaDoctorado'),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Proyecto'),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='sinodales',
            field=models.ManyToManyField(blank=True, related_name='comite_candidatura_doctoral_sinodales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asesorestancia',
            name='asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesor_estancia_asesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asesorestancia',
            name='asesorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesor_estancia_asesorado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asesorestancia',
            name='beca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Beca'),
        ),
        migrations.AddField(
            model_name='asesorestancia',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='asesorestancia',
            name='programa_doctorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaDoctorado'),
        ),
        migrations.AddField(
            model_name='asesorestancia',
            name='programa_licenciatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaLicenciatura'),
        ),
        migrations.AddField(
            model_name='asesorestancia',
            name='programa_maestria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProgramaMaestria'),
        ),
        migrations.AddField(
            model_name='asesorestancia',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Proyecto'),
        ),
    ]
