# Generated by Django 2.0.1 on 2018-01-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigacion', '0001_initial'),
        ('formacion_recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisioninvestigadorpostdoctoral',
            name='articulos',
            field=models.ManyToManyField(blank=True, to='investigacion.ArticuloCientifico'),
        ),
    ]
