# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigacion', '0001_initial'),
        ('formacion_recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisioninvestigadorpostdoctoral',
            name='articulos',
            field=models.ManyToManyField(blank=True, to='investigacion.ArticuloCientifico'),
        ),
    ]
