# Generated by Django 2.0.5 on 2018-05-03 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formacion_recursos_humanos', '0002_supervisioninvestigadorpostdoctoral_articulos'),
        ('nucleo', '0001_initial'),
        ('investigacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisioninvestigadorpostdoctoral',
            name='beca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Beca'),
        ),
        migrations.AddField(
            model_name='supervisioninvestigadorpostdoctoral',
            name='capitulos_libros',
            field=models.ManyToManyField(blank=True, to='investigacion.CapituloLibroInvestigacion'),
        ),
        migrations.AddField(
            model_name='supervisioninvestigadorpostdoctoral',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='supervisioninvestigadorpostdoctoral',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='supervisioninvestigadorpostdoctoral',
            name='investigador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervision_investigador_postdoctoral_investigador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisioninvestigadorpostdoctoral',
            name='libros',
            field=models.ManyToManyField(blank=True, to='nucleo.Libro'),
        ),
        migrations.AddField(
            model_name='supervisioninvestigadorpostdoctoral',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investigacion.ProyectoInvestigacion'),
        ),
        migrations.AddField(
            model_name='supervisioninvestigadorpostdoctoral',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervision_investigador_postdoctoral_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='asesorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='direccion_tesis_asesorado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='beca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Beca'),
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='reconocimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Distincion'),
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='usuarios',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='direccion_tesis_usuarios', to=settings.AUTH_USER_MODEL, verbose_name='Tutores'),
        ),
        migrations.AddField(
            model_name='desarrollogrupoinvestigacioninterno',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Pais'),
        ),
        migrations.AddField(
            model_name='desarrollogrupoinvestigacioninterno',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='asesores',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='comite_tutoral_asesores', to=settings.AUTH_USER_MODEL, verbose_name='Asesores'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comite_tutoral_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='programa_doctorado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.ProgramaDoctorado'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='programa_licenciatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.ProgramaLicenciatura'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='programa_maestria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.ProgramaMaestria'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='investigacion.ProyectoInvestigacion'),
        ),
        migrations.AddField(
            model_name='comitetutoral',
            name='sinodales',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='comite_tutoral_sinodales', to=settings.AUTH_USER_MODEL, verbose_name='Sinodales'),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='asesorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comite_candidatura_doctoral_asesorado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='asesores',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='comite_candidatura_doctoral_asesores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='programa_doctorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.ProgramaDoctorado'),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='investigacion.ProyectoInvestigacion'),
        ),
        migrations.AddField(
            model_name='comitecandidaturadoctoral',
            name='sinodales',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='comite_candidatura_doctoral_sinodales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='asesorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asesoria_estudiante_asesorado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='beca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Beca'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Dependencia'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Institucion'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='programa_doctorado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.ProgramaDoctorado'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='programa_licenciatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.ProgramaLicenciatura'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='programa_maestria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.ProgramaMaestria'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='investigacion.ProyectoInvestigacion'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asesoria_estudiante_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='asesoriaestudiante',
            unique_together={('usuario', 'asesorado', 'nivel_academico')},
        ),
    ]
