# Generated by Django 2.0.6 on 2018-12-05 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formacion_recursos_humanos', '0005_auto_20181205_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciontesis',
            name='codirector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='direccion_tesis_codirector', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='direccion_tesis_director', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
