# Generated by Django 6.1.1 on 2026-09-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_recursos_humanos', '0005_paises_cities_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoriaestudiante',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='comitetutoral',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='direcciontesis',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='grupoinvestigacioninterno',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalasesoriaestudiante',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalcomitetutoral',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicaldirecciontesis',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalgrupoinvestigacioninterno',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalsupervisionpostdoctoral',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='supervisionpostdoctoral',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
    ]
