# Generated by Django 2.0.6 on 2018-12-05 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_recursos_humanos', '0006_auto_20181205_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciontesis',
            name='codirector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='direccion_tesis_codirector', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='direcciontesis',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='direccion_tesis_director', to=settings.AUTH_USER_MODEL),
        ),
    ]
