# Generated by Django 2.0.6 on 2018-12-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_recursos_humanos', '0007_auto_20181205_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='proyecto_externo',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
