# Generated by Django 6.1.1 on 2026-10-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_recursos_humanos', '0008_fechas_obligatorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='detalle_beca',
            field=models.CharField(blank=True, help_text='Clave del proyecto que paga la beca (p. ej. IN303309).', max_length=255, verbose_name='detalle de la beca'),
        ),
        migrations.AddField(
            model_name='asesoriaestudiante',
            name='modalidad_beca',
            field=models.CharField(blank=True, choices=[('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado'), ('TITULACION', 'Titulación'), ('CONCLUSION', 'Conclusión de estudios'), ('MOVILIDAD', 'Movilidad'), ('POSDOCTORAL', 'Posdoctoral'), ('SERVICIO_SOCIAL', 'Servicio social')], max_length=20, verbose_name='modalidad de la beca'),
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='detalle_beca',
            field=models.CharField(blank=True, help_text='Clave del proyecto que paga la beca (p. ej. IN303309).', max_length=255, verbose_name='detalle de la beca'),
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='detalle_reconocimiento',
            field=models.CharField(blank=True, help_text='P. ej. Mención honorífica.', max_length=255, verbose_name='detalle del reconocimiento'),
        ),
        migrations.AddField(
            model_name='direcciontesis',
            name='modalidad_beca',
            field=models.CharField(blank=True, choices=[('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado'), ('TITULACION', 'Titulación'), ('CONCLUSION', 'Conclusión de estudios'), ('MOVILIDAD', 'Movilidad'), ('POSDOCTORAL', 'Posdoctoral'), ('SERVICIO_SOCIAL', 'Servicio social')], max_length=20, verbose_name='modalidad de la beca'),
        ),
        migrations.AddField(
            model_name='historicalasesoriaestudiante',
            name='detalle_beca',
            field=models.CharField(blank=True, help_text='Clave del proyecto que paga la beca (p. ej. IN303309).', max_length=255, verbose_name='detalle de la beca'),
        ),
        migrations.AddField(
            model_name='historicalasesoriaestudiante',
            name='modalidad_beca',
            field=models.CharField(blank=True, choices=[('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado'), ('TITULACION', 'Titulación'), ('CONCLUSION', 'Conclusión de estudios'), ('MOVILIDAD', 'Movilidad'), ('POSDOCTORAL', 'Posdoctoral'), ('SERVICIO_SOCIAL', 'Servicio social')], max_length=20, verbose_name='modalidad de la beca'),
        ),
        migrations.AddField(
            model_name='historicaldirecciontesis',
            name='detalle_beca',
            field=models.CharField(blank=True, help_text='Clave del proyecto que paga la beca (p. ej. IN303309).', max_length=255, verbose_name='detalle de la beca'),
        ),
        migrations.AddField(
            model_name='historicaldirecciontesis',
            name='detalle_reconocimiento',
            field=models.CharField(blank=True, help_text='P. ej. Mención honorífica.', max_length=255, verbose_name='detalle del reconocimiento'),
        ),
        migrations.AddField(
            model_name='historicaldirecciontesis',
            name='modalidad_beca',
            field=models.CharField(blank=True, choices=[('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado'), ('TITULACION', 'Titulación'), ('CONCLUSION', 'Conclusión de estudios'), ('MOVILIDAD', 'Movilidad'), ('POSDOCTORAL', 'Posdoctoral'), ('SERVICIO_SOCIAL', 'Servicio social')], max_length=20, verbose_name='modalidad de la beca'),
        ),
        migrations.AddField(
            model_name='historicalsupervisionpostdoctoral',
            name='detalle_beca',
            field=models.CharField(blank=True, help_text='Clave del proyecto que paga la beca (p. ej. IN303309).', max_length=255, verbose_name='detalle de la beca'),
        ),
        migrations.AddField(
            model_name='historicalsupervisionpostdoctoral',
            name='modalidad_beca',
            field=models.CharField(blank=True, choices=[('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado'), ('TITULACION', 'Titulación'), ('CONCLUSION', 'Conclusión de estudios'), ('MOVILIDAD', 'Movilidad'), ('POSDOCTORAL', 'Posdoctoral'), ('SERVICIO_SOCIAL', 'Servicio social')], max_length=20, verbose_name='modalidad de la beca'),
        ),
        migrations.AddField(
            model_name='supervisionpostdoctoral',
            name='detalle_beca',
            field=models.CharField(blank=True, help_text='Clave del proyecto que paga la beca (p. ej. IN303309).', max_length=255, verbose_name='detalle de la beca'),
        ),
        migrations.AddField(
            model_name='supervisionpostdoctoral',
            name='modalidad_beca',
            field=models.CharField(blank=True, choices=[('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado'), ('TITULACION', 'Titulación'), ('CONCLUSION', 'Conclusión de estudios'), ('MOVILIDAD', 'Movilidad'), ('POSDOCTORAL', 'Posdoctoral'), ('SERVICIO_SOCIAL', 'Servicio social')], max_length=20, verbose_name='modalidad de la beca'),
        ),
    ]
