# Generated by Django 6.1.1 on 2026-10-01 19:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_recursos_humanos', '0009_asesoriaestudiante_detalle_beca_and_more'),
        ('nucleo', '0032_evento_numero_vistas_historicalevento_numero_vistas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoriaestudiante',
            name='tipo',
            field=models.CharField(choices=[('RESIDENCIA', 'Residencia'), ('PRACTICA', 'Prácticas profesionales'), ('ESTANCIA', 'Estancia de investigación'), ('ASESORIA_TECNICA', 'Asesoría técnica'), ('SERVICIO_SOCIAL', 'Servicio social'), ('BECARIO', 'Becario de proyecto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalasesoriaestudiante',
            name='tipo',
            field=models.CharField(choices=[('RESIDENCIA', 'Residencia'), ('PRACTICA', 'Prácticas profesionales'), ('ESTANCIA', 'Estancia de investigación'), ('ASESORIA_TECNICA', 'Asesoría técnica'), ('SERVICIO_SOCIAL', 'Servicio social'), ('BECARIO', 'Becario de proyecto')], max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalJuradoExamen',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=20)),
                ('titulo_tesis', models.CharField(blank=True, max_length=255, verbose_name='título de la tesis')),
                ('fecha_examen', models.DateField(verbose_name='fecha del examen')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estudiante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.persona')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.institucion', verbose_name='institución')),
                ('programa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.programaacademico')),
                ('tutor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.persona', verbose_name='tutor principal')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sinodal de examen de grado',
                'verbose_name_plural': 'historical sinodalías de exámenes de grado',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMovilidadEstudiante',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Déjala vacía si sigue vigente.', null=True, verbose_name='fecha de término')),
                ('nivel', models.CharField(choices=[('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=20)),
                ('detalle_beca', models.CharField(blank=True, max_length=255, verbose_name='detalle de la beca')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('beca', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.beca')),
                ('estudiante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.persona')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institucion_receptora', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.institucion', verbose_name='institución receptora')),
                ('programa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.programaacademico')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='tutor')),
            ],
            options={
                'verbose_name': 'historical movilidad estudiantil',
                'verbose_name_plural': 'historical movilidad estudiantil',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='JuradoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=20)),
                ('titulo_tesis', models.CharField(blank=True, max_length=255, verbose_name='título de la tesis')),
                ('fecha_examen', models.DateField(verbose_name='fecha del examen')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examenes_jurado', to='nucleo.persona')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.institucion', verbose_name='institución')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nucleo.programaacademico')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nucleo.persona', verbose_name='tutor principal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurados_examen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sinodal de examen de grado',
                'verbose_name_plural': 'sinodalías de exámenes de grado',
                'ordering': ['-fecha_examen'],
            },
        ),
        migrations.CreateModel(
            name='MovilidadEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Déjala vacía si sigue vigente.', null=True, verbose_name='fecha de término')),
                ('nivel', models.CharField(choices=[('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=20)),
                ('detalle_beca', models.CharField(blank=True, max_length=255, verbose_name='detalle de la beca')),
                ('beca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nucleo.beca')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movilidades_estudiante', to='nucleo.persona')),
                ('institucion_receptora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.institucion', verbose_name='institución receptora')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nucleo.programaacademico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movilidades_tutorados', to=settings.AUTH_USER_MODEL, verbose_name='tutor')),
            ],
            options={
                'verbose_name': 'movilidad estudiantil',
                'verbose_name_plural': 'movilidad estudiantil',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
