# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 19:32
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigacion', '0001_initial'),
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrajeOtrasActividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='actividad', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia')),
                ('participantes', models.ManyToManyField(blank=True, related_name='arbitraje_otras_actividades_participantes', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='arbitraje_otras_actividades_tags', to='nucleo.Tag')),
            ],
            options={
                'verbose_name': 'Arbitraje en otras actividades',
                'verbose_name_plural': 'Arbitraje en otras actividades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ArbitrajeProyectoInvestigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('participantes', models.ManyToManyField(blank=True, related_name='arbitraje_proyecto_investigacion_participantes', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Proyecto')),
                ('tags', models.ManyToManyField(blank=True, related_name='arbitraje_proyecto_investigacion_tags', to='nucleo.Tag')),
            ],
            options={
                'verbose_name': 'Arbitraje de proyectos de investigación',
                'verbose_name_plural': 'Arbitrajes de proyectos de investigación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ArbitrajePublicacionAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_publicacion', models.CharField(choices=[('REVISTA', 'Revista'), ('LIBRO', 'Libro'), ('CAPITULO_LIBRO', 'Capitulo en libro')], max_length=20)),
                ('fecha_dictamen', models.DateField()),
                ('capitulo_libro', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.CapituloLibroInvestigacion')),
                ('indices', models.ManyToManyField(blank=True, related_name='arbitraje_publicacion_indices', to='nucleo.Indice')),
                ('libro', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Libro')),
                ('participantes', models.ManyToManyField(blank=True, related_name='arbitraje_publicacion_participantes', to=settings.AUTH_USER_MODEL)),
                ('revista', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Revista')),
                ('tags', models.ManyToManyField(blank=True, related_name='arbitraje_publicacion_academica_tags', to='nucleo.Tag')),
            ],
            options={
                'verbose_name': 'Arbitraje en publicaciones académicas',
                'verbose_name_plural': 'Arbitrajes en publicaciones académicas',
                'ordering': ['-fecha_dictamen'],
            },
        ),
        migrations.CreateModel(
            name='ClasificacionServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre', unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Clasificación de servicio',
                'verbose_name_plural': 'Clasificaciones de servicios',
            },
        ),
        migrations.CreateModel(
            name='ConvenioEntidadNoAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('es_agradecimiento', models.BooleanField()),
                ('clasificacion_entidad', models.CharField(choices=[('FEDERAL', 'Gubernamental federal'), ('ESTATAL', 'Gubernamental estatal'), ('PRIVADO', 'Sector privado'), ('NO_LUCRATIVO', 'Sector privado no lucrativo'), ('EXTRANJERO', 'Extranjero'), ('OTRO', 'Otro')], max_length=20)),
                ('objetivos', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('es_renovacion', models.BooleanField(default=False)),
                ('incluye_financiamiento', models.BooleanField(default=False)),
                ('dependencias', models.ManyToManyField(related_name='convenio_entidad_no_academica_dependencias', to='nucleo.Dependencia')),
                ('tags', models.ManyToManyField(blank=True, related_name='convenio_entidad_academica_tags', to='nucleo.Tag')),
            ],
            options={
                'verbose_name': 'Convenio con entidades no académicas',
                'verbose_name_plural': 'Convenios con entidades no académicas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='OtroProgramaVinculacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre_servicio', unique=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('VINCULLACION', 'Vinculación'), ('COLABORACION', 'Colaboración'), ('COOPERACION', 'Cooperación'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('resultados', models.TextField(blank=True)),
                ('dependencias', models.ManyToManyField(to='nucleo.Dependencia')),
                ('tags', models.ManyToManyField(blank=True, related_name='otro_programa_vinculacion_tags', to='nucleo.Tag')),
            ],
            options={
                'verbose_name': 'Otro programa o acción de vinculación, colaboración y/o cooperación',
                'verbose_name_plural': 'Otros programas o acciones de vinculación, colaboración y/o cooperación',
                'ordering': ['-fecha', 'nombre_servicio'],
            },
        ),
        migrations.CreateModel(
            name='RedAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('clasificacion', models.CharField(choices=[('LOCAL', 'Local'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional'), ('OTRO', 'Otro')], max_length=20)),
                ('objetivos', models.TextField()),
                ('fecha_constitucion', models.DateField()),
                ('vigente', models.BooleanField(default=False)),
                ('academicos', models.ManyToManyField(related_name='red_academica_academicos', to=settings.AUTH_USER_MODEL)),
                ('paises', models.ManyToManyField(blank=True, related_name='red_academica_paises', to='nucleo.Pais')),
                ('proyectos', models.ManyToManyField(blank=True, related_name='red_academica_proyectos', to='nucleo.Proyecto')),
                ('regiones', models.ManyToManyField(blank=True, related_name='red_academica_regiones', to='nucleo.Region')),
                ('tags', models.ManyToManyField(blank=True, related_name='red_academica_tags', to='nucleo.Tag')),
            ],
            options={
                'verbose_name': 'Red académica',
                'verbose_name_plural': 'Redes académicas',
                'ordering': ['-fecha_constitucion'],
            },
        ),
        migrations.CreateModel(
            name='ServicioExternoEntidadNoAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre_servicio', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('clasificacion_entidad', models.CharField(choices=[('FEDERAL', 'Gubernamental federal'), ('ESTATAL', 'Gubernamental estatal'), ('PRIVADO', 'Sector privado'), ('NO_LUCRATIVO', 'Sector privado no lucrativo'), ('EXTRANJERO', 'Extranjero'), ('OTRO', 'Otro')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('incluye_financiamiento', models.BooleanField(default=False)),
                ('clasificacion_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinculacion.ClasificacionServicio')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia')),
                ('tags', models.ManyToManyField(blank=True, related_name='servicio_externo_entidad_academica_tags', to='nucleo.Tag')),
            ],
            options={
                'verbose_name': 'Servicio o asesoria externa a entidades no académicas',
                'verbose_name_plural': 'Servicios o asesorias externas a entidades no académicas',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
