# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20171127_1606'),
        ('vinculacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redacademica',
            old_name='clasificacion',
            new_name='ambito',
        ),
        migrations.RemoveField(
            model_name='redacademica',
            name='paises',
        ),
        migrations.AddField(
            model_name='redacademica',
            name='instituciones',
            field=models.ManyToManyField(related_name='red_academica_instituciones', to='nucleo.Institucion'),
        ),
    ]
