# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0002_arbitrajepublicacionacademica_articulo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arbitrajepublicacionacademica',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='arbitrajepublicacionacademica',
            name='revista',
        ),
    ]
