# Generated by Django 2.0.6 on 2018-11-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0003_auto_20181105_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitrajeotraactividad',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='arbitrajeproyectoinvestigacion',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='otroprogramavinculacion',
            name='institucion',
        ),
    ]
