# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0003_auto_20171122_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitrajepublicacionacademica',
            name='capitulo_libro',
        ),
    ]
