# Generated by Django 6.1.1 on 2026-10-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0004_fechas_vacias_a_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalconvenio',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalotracomision',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalredacademica',
            name='fecha_constitucion',
            field=models.DateField(verbose_name='fecha de constitución'),
        ),
        migrations.AlterField(
            model_name='historicalservicioasesoriaexterna',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='otracomision',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='redacademica',
            name='fecha_constitucion',
            field=models.DateField(verbose_name='fecha de constitución'),
        ),
        migrations.AlterField(
            model_name='servicioasesoriaexterna',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
    ]
