# Generated by Django 6.1.1 on 2026-10-01 19:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0032_evento_numero_vistas_historicalevento_numero_vistas'),
        ('vinculacion', '0005_fechas_obligatorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalotracomision',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de proyectos, trabajos o expedientes evaluados.', verbose_name='evaluaciones'),
        ),
        migrations.AddField(
            model_name='otracomision',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de proyectos, trabajos o expedientes evaluados.', verbose_name='evaluaciones'),
        ),
        migrations.CreateModel(
            name='ConsejoEditorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Déjala vacía si sigue vigente.', null=True, verbose_name='fecha de término')),
                ('tipo', models.CharField(choices=[('COMITE_EDITORIAL', 'Comité editorial'), ('CONSEJO_EDITORIAL', 'Consejo editorial'), ('CONSEJO_CIENTIFICO', 'Consejo científico')], max_length=20)),
                ('publicacion', models.CharField(blank=True, max_length=255, verbose_name='colección o serie')),
                ('origen', models.CharField(choices=[('NACIONAL', 'Nacional'), ('EXTRANJERA', 'Extranjera')], max_length=20)),
                ('revista', models.ForeignKey(blank=True, help_text='Si es una revista; para una colección o serie de libros, escribe su nombre.', null=True, on_delete=django.db.models.deletion.PROTECT, to='nucleo.revista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consejos_editoriales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comité o consejo editorial',
                'verbose_name_plural': 'comités y consejos editoriales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalConsejoEditorial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Déjala vacía si sigue vigente.', null=True, verbose_name='fecha de término')),
                ('tipo', models.CharField(choices=[('COMITE_EDITORIAL', 'Comité editorial'), ('CONSEJO_EDITORIAL', 'Consejo editorial'), ('CONSEJO_CIENTIFICO', 'Consejo científico')], max_length=20)),
                ('publicacion', models.CharField(blank=True, max_length=255, verbose_name='colección o serie')),
                ('origen', models.CharField(choices=[('NACIONAL', 'Nacional'), ('EXTRANJERA', 'Extranjera')], max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revista', models.ForeignKey(blank=True, db_constraint=False, help_text='Si es una revista; para una colección o serie de libros, escribe su nombre.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.revista')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical comité o consejo editorial',
                'verbose_name_plural': 'historical comités y consejos editoriales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
