# Generated by Django 6.1.1 on 2026-10-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0006_historicalotracomision_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservicioasesoriaexterna',
            name='tipo',
            field=models.CharField(choices=[('ASESORIA', 'Asesoría'), ('INCIDENCIA', 'Actividad de incidencia'), ('LABORATORIO', 'Servicio de laboratorio'), ('EVALUACION', 'Evaluación o arbitraje'), ('OTRO', 'Otro servicio')], default='ASESORIA', max_length=20),
        ),
        migrations.AddField(
            model_name='servicioasesoriaexterna',
            name='tipo',
            field=models.CharField(choices=[('ASESORIA', 'Asesoría'), ('INCIDENCIA', 'Actividad de incidencia'), ('LABORATORIO', 'Servicio de laboratorio'), ('EVALUACION', 'Evaluación o arbitraje'), ('OTRO', 'Otro servicio')], default='ASESORIA', max_length=20),
        ),
    ]
