# Generated by Django 6.1.1 on 2026-10-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0007_historicalservicioasesoriaexterna_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='monto del financiamiento'),
        ),
        migrations.AddField(
            model_name='historicalconvenio',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='monto del financiamiento'),
        ),
    ]
