# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 02:23
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaInExtenso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True)),
                ('descipcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
                ('issn', models.SlugField(blank=True, max_length=20)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Memorias in extenso',
                'verbose_name': 'Memoria in extenso',
            },
        ),
        migrations.CreateModel(
            name='OrganizacionEventoAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descipcion', models.TextField(blank=True)),
                ('responsabilidad', models.CharField(choices=[('COORDINADOR', 'Coordinador general'), ('COMITE', 'Comité organizador'), ('AYUDANTE', 'Ayudante'), ('TECNICO', 'Apoyo técnico'), ('OTRO', 'Otro')], max_length=30)),
                ('numero_ponentes', models.PositiveIntegerField()),
                ('numero_asistentes', models.PositiveIntegerField()),
                ('ambito', models.CharField(choices=[('INSTITUCIONAL', 'Institucional'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional'), ('OTRO', 'Otro')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Organización de eventos académicos',
                'verbose_name': 'Organización de evento académico',
            },
        ),
        migrations.CreateModel(
            name='ParticipacionEventoAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True)),
                ('descipcion', models.TextField(blank=True)),
                ('resumen_publicado', models.BooleanField(default=False)),
                ('ambito', models.CharField(choices=[('INSTITUCIONAL', 'Institucional'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional'), ('OTRO', 'Otro')], max_length=20)),
                ('por_invitacion', models.BooleanField(default=False)),
                ('ponencia_magistral', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Participación en eventos académicos',
                'verbose_name': 'Participación en evento académico',
            },
        ),
        migrations.CreateModel(
            name='PrologoLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descipcion', models.TextField(blank=True)),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Prólogos de libros',
                'verbose_name': 'Prólogo de libro',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_resena', models.CharField(max_length=255, unique=True)),
                ('tipo_publicacion', models.CharField(choices=[('LIBRO', 'Libro'), ('REVISTA', 'Revista'), ('OTRO', 'Otro')], max_length=20)),
                ('volumen', models.CharField(blank=True, max_length=10)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo_resena', unique=True)),
                ('descipcion', models.TextField(blank=True)),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Reseñas de libros',
                'verbose_name': 'Reseña de libro',
            },
        ),
    ]
