# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigacion', '0001_initial'),
        ('difusion_cientifica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traduccion',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.ArticuloCientifico'),
        ),
    ]
