# Generated by Django 6.1.1 on 2026-09-26 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("difusion_cientifica", "0001_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="memoriainextenso",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución organizadora",
            ),
        ),
        migrations.AddField(
            model_name="memoriainextenso",
            name="pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.pais",
                verbose_name="país",
            ),
        ),
        migrations.AddField(
            model_name="memoriainextensoautor",
            name="memoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="difusion_cientifica.memoriainextenso",
            ),
        ),
        migrations.AddField(
            model_name="memoriainextensoautor",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="memoriainextenso",
            name="autores",
            field=models.ManyToManyField(
                related_name="memorias_in_extenso",
                through="difusion_cientifica.MemoriaInExtensoAutor",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="organizacioneventoacademico",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.evento"
            ),
        ),
        migrations.AddField(
            model_name="organizacioneventoacademico",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organizaciones_eventos_academicos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participacioneventoacademico",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución organizadora",
            ),
        ),
        migrations.AddField(
            model_name="participacioneventoacademico",
            name="pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.pais",
                verbose_name="país",
            ),
        ),
        migrations.AddField(
            model_name="participacioneventoacademicoautor",
            name="participacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="difusion_cientifica.participacioneventoacademico",
            ),
        ),
        migrations.AddField(
            model_name="participacioneventoacademicoautor",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="participacioneventoacademico",
            name="autores",
            field=models.ManyToManyField(
                related_name="participaciones_eventos_academicos",
                through="difusion_cientifica.ParticipacionEventoAcademicoAutor",
                to="nucleo.persona",
            ),
        ),
        migrations.AddConstraint(
            model_name="memoriainextensoautor",
            constraint=models.UniqueConstraint(
                fields=("memoria", "persona"), name="memoria_autor_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="participacioneventoacademicoautor",
            constraint=models.UniqueConstraint(
                fields=("participacion", "persona"),
                name="participacion_academica_autor_unico",
            ),
        ),
    ]
