# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 00:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('difusion_cientifica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='libro_publica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resena_libro_publica', to='nucleo.Libro'),
        ),
        migrations.AddField(
            model_name='resena',
            name='libro_resenado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resena_libro_resenado', to='nucleo.Libro'),
        ),
        migrations.AddField(
            model_name='resena',
            name='revista_publica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resena_revista_publica', to='nucleo.Revista'),
        ),
        migrations.AddField(
            model_name='resena',
            name='revista_resenada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resena_revista_resenada', to='nucleo.Revista'),
        ),
        migrations.AddField(
            model_name='resena',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='resena_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='resena',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prologolibro',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prologo_libro_libro', to='nucleo.Libro'),
        ),
        migrations.AddField(
            model_name='prologolibro',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='prologo_libro_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='prologolibro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participacioneventoacademico',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Evento'),
        ),
        migrations.AddField(
            model_name='participacioneventoacademico',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='participacion_evento_academico_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='participacioneventoacademico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizacioneventoacademico',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Evento'),
        ),
        migrations.AddField(
            model_name='organizacioneventoacademico',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='organizacion_evento_academico_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='organizacioneventoacademico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='agradecimientos',
            field=models.ManyToManyField(blank=True, related_name='memoria_in_extenso_agradecimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ciudad'),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='editores',
            field=models.ManyToManyField(blank=True, related_name='memoria_in_extenso_editores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Evento'),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='indices',
            field=models.ManyToManyField(blank=True, related_name='memoria_in_extenso_indices', to='nucleo.Indice'),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='pais_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pais'),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='proyectos',
            field=models.ManyToManyField(to='nucleo.Proyecto'),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='usuarios',
            field=models.ManyToManyField(related_name='memoria_in_extenso_autores_externos', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
        migrations.AlterUniqueTogether(
            name='prologolibro',
            unique_together=set([('usuario', 'libro')]),
        ),
    ]
