# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_initial'),
        ('investigacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('difusion_cientifica', '0002_traduccion_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='traduccion',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Libro'),
        ),
        migrations.AddField(
            model_name='traduccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resena',
            name='articulo_resenado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resena_revista_resenada', to='investigacion.ArticuloCientifico'),
        ),
        migrations.AddField(
            model_name='resena',
            name='libro_resenado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resena_libro_resenado', to='nucleo.Libro'),
        ),
        migrations.AddField(
            model_name='resena',
            name='revista_publica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resena_revista_publica', to='nucleo.Revista'),
        ),
        migrations.AddField(
            model_name='resena',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resena_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prologolibro',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prologo_libro_libro', to='nucleo.Libro'),
        ),
        migrations.AddField(
            model_name='prologolibro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prologo_libro_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participacioneventoacademico',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Evento'),
        ),
        migrations.AddField(
            model_name='participacioneventoacademico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizacioneventoacademico',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Evento'),
        ),
        migrations.AddField(
            model_name='organizacioneventoacademico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='agradecimientos',
            field=models.ManyToManyField(blank=True, related_name='memoria_in_extenso_agradecimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ciudad'),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='editores',
            field=models.ManyToManyField(blank=True, related_name='memoria_in_extenso_editores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Estado'),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Evento'),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='indices',
            field=models.ManyToManyField(blank=True, related_name='memoria_in_extenso_indices', to='nucleo.Indice'),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pais'),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.ProyectoInvestigacion'),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='revista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Revista'),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='usuarios',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='memoria_in_extenso_autores', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
        migrations.AlterUniqueTogether(
            name='prologolibro',
            unique_together=set([('usuario', 'libro')]),
        ),
    ]
