# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('difusion_cientifica', '0002_auto_20171004_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resena_autor', to=settings.AUTH_USER_MODEL),
        ),
    ]
