# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_user_curp'),
        ('difusion_cientifica', '0002_auto_20171102_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoriainextenso',
            name='revista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Revista'),
            preserve_default=False,
        ),
    ]
