# Generated by Django 6.1.1 on 2026-09-26 18:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("difusion_cientifica", "0002_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="participacioneventoacademico",
            name="ambito",
            field=models.CharField(
                choices=[
                    ("LOCAL", "Local"),
                    ("INSTITUCIONAL", "Institucional"),
                    ("REGIONAL", "Regional"),
                    ("NACIONAL", "Nacional"),
                    ("INTERNACIONAL", "Internacional"),
                ],
                editable=False,
                help_text="Se calcula a partir del país.",
                max_length=20,
                verbose_name="ámbito",
            ),
        ),
        migrations.AlterField(
            model_name="participacioneventoacademico",
            name="ponencia_magistral",
            field=models.BooleanField(
                default=False,
                help_text="Conferencia magistral o plenaria.",
                verbose_name="conferencia magistral",
            ),
        ),
        migrations.AlterField(
            model_name="participacioneventoacademico",
            name="por_invitacion",
            field=models.BooleanField(
                default=False,
                help_text="La ponencia fue por invitación expresa de los organizadores.",
                verbose_name="por invitación",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalMemoriaInExtenso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("titulo", models.CharField(max_length=254, verbose_name="título")),
                (
                    "evento",
                    models.CharField(max_length=254, verbose_name="nombre del evento"),
                ),
                (
                    "lugar",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="lugar del evento"
                    ),
                ),
                ("fecha", models.DateField()),
                ("ciudad", models.CharField(blank=True, max_length=254)),
                (
                    "pagina_inicio",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página inicial"
                    ),
                ),
                (
                    "pagina_fin",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página final"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=30, verbose_name="ISBN"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.institucion",
                        verbose_name="institución organizadora",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.pais",
                        verbose_name="país",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical memoria in extenso",
                "verbose_name_plural": "historical memorias in extenso",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMemoriaInExtensoAutor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "memoria",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="difusion_cientifica.memoriainextenso",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical autor",
                "verbose_name_plural": "historical autores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOrganizacionEventoAcademico",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tipo_participacion",
                    models.CharField(
                        choices=[
                            ("COORDINADOR", "Coordinador general"),
                            ("COMITE_ORGANIZADOR", "Comité organizador"),
                            ("APOYO_TECNICO", "Apoyo técnico"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="tipo de participación",
                    ),
                ),
                (
                    "tipo_participacion_otro",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        verbose_name="otro tipo de participación",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.evento",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical organización de evento académico",
                "verbose_name_plural": "historical organización de eventos académicos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalParticipacionEventoAcademico",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PONENCIA", "Ponencia"), ("POSTER", "Póster")],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="título")),
                (
                    "evento",
                    models.CharField(max_length=254, verbose_name="nombre del evento"),
                ),
                (
                    "lugar",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="lugar del evento"
                    ),
                ),
                ("ciudad", models.CharField(blank=True, max_length=255)),
                ("fecha", models.DateField()),
                (
                    "ambito",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local"),
                            ("INSTITUCIONAL", "Institucional"),
                            ("REGIONAL", "Regional"),
                            ("NACIONAL", "Nacional"),
                            ("INTERNACIONAL", "Internacional"),
                        ],
                        editable=False,
                        help_text="Se calcula a partir del país.",
                        max_length=20,
                        verbose_name="ámbito",
                    ),
                ),
                (
                    "por_invitacion",
                    models.BooleanField(
                        default=False,
                        help_text="La ponencia fue por invitación expresa de los organizadores.",
                        verbose_name="por invitación",
                    ),
                ),
                (
                    "ponencia_magistral",
                    models.BooleanField(
                        default=False,
                        help_text="Conferencia magistral o plenaria.",
                        verbose_name="conferencia magistral",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.institucion",
                        verbose_name="institución organizadora",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.pais",
                        verbose_name="país",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical participación en evento académico",
                "verbose_name_plural": "historical participación en eventos académicos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalParticipacionEventoAcademicoAutor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="difusion_cientifica.participacioneventoacademico",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical autor",
                "verbose_name_plural": "historical autores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
