# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0003_remove_capitulolibroinvestigacion_proyecto'),
        ('difusion_cientifica', '0003_memoriainextenso_revista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resena',
            name='revista_resenada',
        ),
        migrations.AddField(
            model_name='resena',
            name='articulo_resenado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resena_revista_resenada', to='investigacion.ArticuloCientifico'),
        ),
    ]
