# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 23:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0005_auto_20171112_2111'),
        ('investigacion', '0003_remove_capitulolibroinvestigacion_proyecto'),
        ('difusion_cientifica', '0004_auto_20171112_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('titulo_original', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('', '-------'), ('LIBRO', 'Libro'), ('REVISTA', 'Revista')], max_length=10)),
                ('fecha', models.DateField()),
                ('url', models.URLField(blank=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.ArticuloCientifico')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña de libro',
                'verbose_name_plural': 'Reseñas de libros',
            },
        ),
    ]
