# Generated by Django 2.0.2 on 2018-02-08 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0002_auto_20180207_2151'),
        ('difusion_cientifica', '0004_remove_traduccion_titulo_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoriainextenso',
            name='agradecimientos',
        ),
        migrations.RemoveField(
            model_name='memoriainextenso',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='memoriainextenso',
            name='editores',
        ),
        migrations.RemoveField(
            model_name='memoriainextenso',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='memoriainextenso',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='memoriainextenso',
            name='pagina_fin',
        ),
        migrations.RemoveField(
            model_name='memoriainextenso',
            name='pagina_inicio',
        ),
        migrations.RemoveField(
            model_name='memoriainextenso',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='memoriainextenso',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='memoriainextenso',
            name='revista',
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='articulos',
            field=models.ManyToManyField(related_name='memoria_in_extenso_articulos', to='investigacion.ArticuloCientifico'),
        ),
        migrations.AddField(
            model_name='memoriainextenso',
            name='proyectos',
            field=models.ManyToManyField(blank=True, related_name='memoria_in_extenso_proyectos', to='investigacion.ProyectoInvestigacion'),
        ),
        migrations.AlterField(
            model_name='memoriainextenso',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre de memoria in extenso'),
        ),
        migrations.AlterField(
            model_name='memoriainextenso',
            name='usuarios',
            field=models.ManyToManyField(related_name='memoria_in_extenso_autores', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
    ]
