# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difusion_cientifica', '0005_traduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='tipo',
            field=models.CharField(choices=[('', '-------'), ('LIBRO', 'Libro'), ('ARTICULO', 'Artículo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='traduccion',
            name='tipo',
            field=models.CharField(choices=[('', '-------'), ('LIBRO', 'Libro'), ('ARTICULO', 'Artículo')], max_length=10),
        ),
    ]
