# Generated by Django 2.0.2 on 2018-02-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difusion_cientifica', '0005_auto_20180208_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoriainextenso',
            name='articulos',
            field=models.ManyToManyField(blank=True, related_name='memoria_in_extenso_articulos', to='investigacion.ArticuloCientifico'),
        ),
    ]
