# Generated by Django 2.0.2 on 2018-02-09 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
        ('difusion_cientifica', '0006_auto_20180208_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoriainextenso',
            name='editorial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Editorial'),
            preserve_default=False,
        ),
    ]
