# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('difusion_cientifica', '0006_auto_20171118_0945'),
        ('difusion_cientifica', '0006_auto_20171114_0918'),
    ]

    operations = [
    ]
