# Generated by Django 6.1.1 on 2026-09-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difusion_cientifica', '0006_paises_cities_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparticipacioneventoacademico',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='participacioneventoacademico',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
