# Generated by Django 6.1.1 on 2026-10-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difusion_cientifica', '0008_fechas_vacias_a_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparticipacioneventoacademico',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='participacioneventoacademico',
            name='fecha',
            field=models.DateField(),
        ),
    ]
