# Generated by Django 2.0.6 on 2018-12-05 19:00

from django.conf import settings
from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('difusion_cientifica', '0011_auto_20181106_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacioneventoacademico',
            name='participantes',
        ),
        migrations.AlterField(
            model_name='organizacioneventoacademico',
            name='apoyo_tecnico',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='organizacion_evento_academico_apoyo_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Apoyo técnico'),
        ),
        migrations.AlterField(
            model_name='organizacioneventoacademico',
            name='ayudantes',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='organizacion_evento_academico_ayudantes', to=settings.AUTH_USER_MODEL, verbose_name='Ayudantes'),
        ),
        migrations.AlterField(
            model_name='organizacioneventoacademico',
            name='comite_organizador',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='organizacion_evento_academico_comite_organizador', to=settings.AUTH_USER_MODEL, verbose_name='Comite organizador'),
        ),
    ]
