# Generated by Django 6.1.1 on 2026-09-26 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActividadApoyo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "actividad de apoyo",
                "verbose_name_plural": "actividades de apoyo",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Comision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Los registros verificados solo pueden modificarlos los administradores.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "comisión (catálogo)",
                "verbose_name_plural": "comisiones (catálogo)",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ComisionInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                (
                    "ambito",
                    models.CharField(
                        choices=[
                            ("INTERIOR", "Al interior de la entidad"),
                            ("EXTERIOR", "Al exterior de la entidad"),
                        ],
                        max_length=20,
                        verbose_name="ámbito",
                    ),
                ),
            ],
            options={
                "verbose_name": "comisión institucional",
                "verbose_name_plural": "comisiones institucionales",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="LaborDirectivaCoordinacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
            ],
            options={
                "verbose_name": "labor directiva o de coordinación",
                "verbose_name_plural": "labores directivas y de coordinación",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="RepresentacionOrganoColegiado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DENTRO", "Dentro de la UNAM"),
                            (
                                "REPRESENTACION",
                                "Con representación UNAM (solo por designación)",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "organo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRIDE", "PRIDE"),
                            ("CAACS", "CAACS"),
                            ("CONSEJO_INTERNO", "Consejo interno"),
                            ("COMISION_DICTAMINADORA", "Comisión dictaminadora"),
                            ("COMISION_EVALUADORA", "Comisión evaluadora"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=30,
                        verbose_name="órgano colegiado",
                    ),
                ),
                (
                    "organo_descripcion",
                    models.CharField(
                        blank=True,
                        help_text='Obligatoria si el órgano es "Otra" o está fuera de la UNAM.',
                        max_length=250,
                        verbose_name="descripción del órgano",
                    ),
                ),
            ],
            options={
                "verbose_name": "representación ante órgano colegiado",
                "verbose_name_plural": "representaciones ante órganos colegiados",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ApoyoInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TECNICO", "Apoyo técnico"),
                            ("OTRA", "Apoyo en otras actividades"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compromiso_institucional.actividadapoyo",
                    ),
                ),
            ],
            options={
                "verbose_name": "apoyo institucional",
                "verbose_name_plural": "apoyos institucionales",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
