# Generated by Django 6.1.1 on 2026-09-26 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compromiso_institucional", "0001_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apoyoinstitucional",
            name="institucion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="apoyoinstitucional",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apoyos_institucionales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comision",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comisioninstitucional",
            name="comision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="compromiso_institucional.comision",
                verbose_name="comisión",
            ),
        ),
        migrations.AddField(
            model_name="comisioninstitucional",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="comisioninstitucional",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comisiones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labordirectivacoordinacion",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.cargo"
            ),
        ),
        migrations.AddField(
            model_name="labordirectivacoordinacion",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="labordirectivacoordinacion",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="labores_directivas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="representacionorganocolegiado",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="representacionorganocolegiado",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="representaciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
