# Generated by Django 6.1.1 on 2026-09-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compromiso_institucional', '0003_historicalactividadapoyo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='historicalcomision',
            name='verificado',
        ),
    ]
