# Generated by Django 6.1.1 on 2026-10-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compromiso_institucional', '0006_fechas_vacias_a_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyoinstitucional',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='comisioninstitucional',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalapoyoinstitucional',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalcomisioninstitucional',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicallabordirectivacoordinacion',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalrepresentacionorganocolegiado',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='labordirectivacoordinacion',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='representacionorganocolegiado',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
    ]
