# Generated by Django 6.1.1 on 2026-10-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compromiso_institucional', '0007_fechas_obligatorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='ayuda',
            field=models.CharField(blank=True, help_text='Indicación que se muestra al capturar (p. ej. qué escribir en el detalle). No sale en los reportes.', max_length=255),
        ),
        migrations.AddField(
            model_name='comision',
            name='seccion',
            field=models.CharField(choices=[('UNAM', 'Comisiones UNAM'), ('ENTIDAD', 'Comisiones de la entidad'), ('COLEGIADO', 'Cuerpos colegiados UNAM'), ('REPRESENTACION', 'Representaciones UNAM'), ('EXTERNA', 'Comisiones de evaluación académica externas'), ('DOCENCIA', 'Comités de planeación y evaluación docente'), ('ARBITRAJE', 'Otras actividades de arbitraje'), ('NO_ACADEMICA', 'Vinculación con entidades no académicas')], default='EXTERNA', max_length=20, verbose_name='sección del informe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comisioninstitucional',
            name='detalle',
            field=models.CharField(blank=True, help_text='Programa, convocatoria o nombre específico (según indique la comisión).', max_length=255),
        ),
        migrations.AddField(
            model_name='comisioninstitucional',
            name='funcion',
            field=models.CharField(choices=[('PRESIDENTE', 'Presidente(a)'), ('COORDINADOR', 'Coordinador(a)'), ('SECRETARIO', 'Secretario(a)'), ('SECRETARIO_TECNICO', 'Secretario(a) técnico(a)'), ('VOCAL', 'Vocal'), ('INTEGRANTE', 'Integrante'), ('TITULAR', 'Representante propietario(a) / titular'), ('SUPLENTE', 'Representante suplente'), ('EVALUADOR', 'Evaluador(a) / dictaminador(a)'), ('JURADO', 'Jurado'), ('COMENTARISTA', 'Comentarista / moderador(a)'), ('ENLACE', 'Enlace institucional'), ('ASESOR', 'Asesor(a)')], default='INTEGRANTE', max_length=20, verbose_name='función'),
        ),
        migrations.AddField(
            model_name='historicalcomision',
            name='ayuda',
            field=models.CharField(blank=True, help_text='Indicación que se muestra al capturar (p. ej. qué escribir en el detalle). No sale en los reportes.', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcomision',
            name='seccion',
            field=models.CharField(choices=[('UNAM', 'Comisiones UNAM'), ('ENTIDAD', 'Comisiones de la entidad'), ('COLEGIADO', 'Cuerpos colegiados UNAM'), ('REPRESENTACION', 'Representaciones UNAM'), ('EXTERNA', 'Comisiones de evaluación académica externas'), ('DOCENCIA', 'Comités de planeación y evaluación docente'), ('ARBITRAJE', 'Otras actividades de arbitraje'), ('NO_ACADEMICA', 'Vinculación con entidades no académicas')], default='EXTERNA', max_length=20, verbose_name='sección del informe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcomisioninstitucional',
            name='detalle',
            field=models.CharField(blank=True, help_text='Programa, convocatoria o nombre específico (según indique la comisión).', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcomisioninstitucional',
            name='funcion',
            field=models.CharField(choices=[('PRESIDENTE', 'Presidente(a)'), ('COORDINADOR', 'Coordinador(a)'), ('SECRETARIO', 'Secretario(a)'), ('SECRETARIO_TECNICO', 'Secretario(a) técnico(a)'), ('VOCAL', 'Vocal'), ('INTEGRANTE', 'Integrante'), ('TITULAR', 'Representante propietario(a) / titular'), ('SUPLENTE', 'Representante suplente'), ('EVALUADOR', 'Evaluador(a) / dictaminador(a)'), ('JURADO', 'Jurado'), ('COMENTARISTA', 'Comentarista / moderador(a)'), ('ENLACE', 'Enlace institucional'), ('ASESOR', 'Asesor(a)')], default='INTEGRANTE', max_length=20, verbose_name='función'),
        ),
        migrations.AddField(
            model_name='historicallabordirectivacoordinacion',
            name='detalle',
            field=models.CharField(blank=True, help_text='Laboratorio, unidad, programa o departamento (p. ej. Laboratorio de Drones).', max_length=255),
        ),
        migrations.AddField(
            model_name='labordirectivacoordinacion',
            name='detalle',
            field=models.CharField(blank=True, help_text='Laboratorio, unidad, programa o departamento (p. ej. Laboratorio de Drones).', max_length=255),
        ),
    ]
