# Generated by Django 6.1.1 on 2026-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticuloDivulgacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENVIADO", "Enviado"),
                            ("ACEPTADO", "Aceptado"),
                            ("EN_PRENSA", "En prensa"),
                            ("PUBLICADO", "Publicado"),
                        ],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("fecha_enviado", models.DateField(blank=True, null=True)),
                ("fecha_aceptado", models.DateField(blank=True, null=True)),
                (
                    "fecha_enprensa",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha en prensa"
                    ),
                ),
                ("fecha_publicado", models.DateField(blank=True, null=True)),
                (
                    "titulo",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="título"
                    ),
                ),
                ("volumen", models.CharField(blank=True, max_length=100)),
                (
                    "numero",
                    models.CharField(blank=True, max_length=100, verbose_name="número"),
                ),
                (
                    "pagina_inicio",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página inicial"
                    ),
                ),
                (
                    "pagina_fin",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página final"
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "solo_electronico",
                    models.BooleanField(default=False, verbose_name="solo electrónico"),
                ),
            ],
            options={
                "verbose_name": "artículo de divulgación",
                "verbose_name_plural": "artículos de divulgación",
                "ordering": [
                    "-fecha_publicado",
                    "-fecha_enprensa",
                    "-fecha_aceptado",
                    "-fecha_enviado",
                    "titulo",
                ],
            },
        ),
        migrations.CreateModel(
            name="ArticuloDivulgacionAutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "autor",
                "verbose_name_plural": "autores",
                "ordering": ["orden", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CapituloLibroDivulgacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="título")),
                (
                    "pagina_inicio",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página inicial"
                    ),
                ),
                (
                    "pagina_fin",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="página final"
                    ),
                ),
            ],
            options={
                "verbose_name": "capítulo en libro de divulgación",
                "verbose_name_plural": "capítulos en libros de divulgación",
                "ordering": ["titulo"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CapituloLibroDivulgacionAutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "autor",
                "verbose_name_plural": "autores",
                "ordering": ["orden", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizacionEventoDivulgacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_participacion",
                    models.CharField(
                        choices=[
                            ("COORDINADOR", "Coordinador general"),
                            ("COMITE_ORGANIZADOR", "Comité organizador"),
                            ("APOYO_TECNICO", "Apoyo técnico"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="tipo de participación",
                    ),
                ),
                (
                    "tipo_participacion_otro",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        verbose_name="otro tipo de participación",
                    ),
                ),
            ],
            options={
                "verbose_name": "organización de evento de divulgación",
                "verbose_name_plural": "organización de eventos de divulgación",
                "ordering": ["-evento__fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ParticipacionEventoDivulgacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PONENCIA", "Ponencia"), ("POSTER", "Póster")],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="título")),
                ("fecha", models.DateField()),
                (
                    "ambito",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local"),
                            ("INSTITUCIONAL", "Institucional"),
                            ("REGIONAL", "Regional"),
                            ("NACIONAL", "Nacional"),
                            ("INTERNACIONAL", "Internacional"),
                        ],
                        max_length=20,
                        verbose_name="ámbito",
                    ),
                ),
                (
                    "por_invitacion",
                    models.BooleanField(default=False, verbose_name="por invitación"),
                ),
                ("ponencia_magistral", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "participación en evento de divulgación",
                "verbose_name_plural": "participación en eventos de divulgación",
                "ordering": ["-fecha", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="ParticipacionEventoDivulgacionAutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "autor",
                "verbose_name_plural": "autores",
                "ordering": ["orden", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramaMedio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tema", models.CharField(max_length=254)),
                ("fecha", models.DateField()),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "actividad",
                    models.CharField(
                        choices=[
                            ("PRODUCCION", "Producción"),
                            ("PARTICIPACION", "Participación"),
                            ("ENTREVISTA", "Entrevista"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "programa en medios de comunicación",
                "verbose_name_plural": "programas en medios de comunicación",
                "ordering": ["-fecha", "tema"],
            },
        ),
    ]
