# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 01:24
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloDivulgacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('documento_articulo', models.FileField(upload_to='')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('ARTICULO', 'Artículo'), ('ACTA', 'Acta'), ('CARTA', 'Carta'), ('RESENA', 'Reseña'), ('OTRO', 'Otro')], max_length=16)),
                ('status', models.CharField(choices=[('PUBLICADO', 'Publicado'), ('EN_PRENSA', 'En prensa'), ('ACEPTADO', 'Aceptado'), ('ENVIADO', 'Enviado'), ('OTRO', 'Otro')], max_length=20)),
                ('indizado', models.BooleanField(default=False)),
                ('solo_electronico', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('fecha', models.DateField()),
                ('volumen', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('issn', models.CharField(blank=True, max_length=30)),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
                ('id_doi', models.CharField(blank=True, max_length=100)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='articulo_divulgracion_alumnos', to=settings.AUTH_USER_MODEL)),
                ('autores', models.ManyToManyField(related_name='articulo_divulgracion_autores', to=settings.AUTH_USER_MODEL)),
                ('indices', models.ManyToManyField(blank=True, related_name='articulo_divulgracion_indices', to='nucleo.Indice')),
                ('proyectos', models.ManyToManyField(blank=True, related_name='articulo_divulgracion_proyectos', to='nucleo.Proyecto')),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Revista')),
                ('tags', models.ManyToManyField(blank=True, related_name='articulo_divulgacion_tags', to='nucleo.Tag')),
            ],
            options={
                'verbose_name': 'Artículo de divulgación',
                'ordering': ['fecha', 'titulo'],
                'verbose_name_plural': 'Artículos de divulgación',
            },
        ),
        migrations.CreateModel(
            name='CapituloLibroDivulgacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Libro')),
                ('proyectos', models.ManyToManyField(blank=True, related_name='capitulo_libro_divulgracion_proyectos', to='nucleo.Proyecto')),
                ('tags', models.ManyToManyField(blank=True, related_name='capitulo_libro_divulgacion_tags', to='nucleo.Tag')),
            ],
            options={
                'verbose_name': 'Capítulo en libro de divulgación',
                'ordering': ['titulo'],
                'verbose_name_plural': 'Capítulos en libros de divulgración',
            },
        ),
        migrations.CreateModel(
            name='LibroDivulgacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='libro', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Libro')),
                ('proyectos', models.ManyToManyField(blank=True, related_name='libro_divulgracion_proyectos', to='nucleo.Proyecto')),
                ('tags', models.ManyToManyField(blank=True, related_name='libro_divulgacion_tags', to='nucleo.Tag')),
            ],
            options={
                'verbose_name': 'Libro de divulgación',
                'ordering': ['libro'],
                'verbose_name_plural': 'Libro de divulgación',
            },
        ),
        migrations.CreateModel(
            name='MedioDivulgacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medio', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre_medio', unique=True)),
                ('canal', models.CharField(max_length=255)),
                ('tags', models.ManyToManyField(blank=True, related_name='medio_divulgacion_tags', to='nucleo.Tag')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ubicacion')),
            ],
            options={
                'verbose_name': 'Medio de difusión para divulgación',
                'ordering': ['nombre_medio'],
                'verbose_name_plural': 'Medios de difusión para divulgación',
            },
        ),
        migrations.CreateModel(
            name='OrganizacionEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('responsabilidad', models.CharField(choices=[('COORDINADOR', 'Coordinador general'), ('COMITE', 'Comité organizador'), ('AYUDANTE', 'Ayudante'), ('TECNICO', 'Apoyo técnico'), ('OTRO', 'Otro')], max_length=30)),
                ('numero_ponentes', models.PositiveIntegerField()),
                ('numero_asistentes', models.PositiveIntegerField()),
                ('ambito', models.CharField(choices=[('INSTITUCIONAL', 'Institucional'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional'), ('OTRO', 'Otro')], max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Evento')),
                ('tags', models.ManyToManyField(blank=True, related_name='organizacion_evento_tags', to='nucleo.Tag')),
            ],
            options={
                'verbose_name': 'Organización de evento académico',
                'verbose_name_plural': 'Organización de eventos académicos',
            },
        ),
        migrations.CreateModel(
            name='ParticipacionEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('resumen_publicado', models.BooleanField(default=False)),
                ('ambito', models.CharField(choices=[('INSTITUCIONAL', 'Institucional'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional'), ('OTRO', 'Otro')], max_length=20)),
                ('por_invitacion', models.BooleanField(default=False)),
                ('ponencia_magistral', models.BooleanField(default=False)),
                ('autores', models.ManyToManyField(related_name='participacion_evento_autores', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Evento')),
                ('tags', models.ManyToManyField(blank=True, related_name='participacion_evento_tags', to='nucleo.Tag')),
            ],
            options={
                'verbose_name': 'Participación en evento académico',
                'verbose_name_plural': 'Participación en eventos académicos',
            },
        ),
        migrations.CreateModel(
            name='ProgramaRadioTelevisionInternet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tema', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('actividad', models.CharField(choices=[('PRODUCCION', 'Producciòn'), ('PARTICIPACION', 'Participaciòn'), ('ENTREVISTA', 'Entrevista'), ('OTRA', 'Otra')], max_length=20)),
                ('medio', models.CharField(choices=[('PERIODICO', 'Periódico'), ('RADIO', 'Radio'), ('TV', 'Televisión'), ('INTERNET', 'Internet'), ('OTRO', 'Otro')], max_length=20)),
                ('nombre_medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divulgacion_cientifica.MedioDivulgacion')),
                ('partiticipantes', models.ManyToManyField(related_name='programa_radio_television_internet_participantes', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='programa_radio_television_internet_tags', to='nucleo.Tag')),
            ],
            options={
                'verbose_name': 'Programa de radio, televisión o internet',
                'ordering': ['fecha', 'tema'],
                'verbose_name_plural': 'Programas de radio, televisión o internet',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mediodivulgacion',
            unique_together=set([('canal', 'nombre_medio')]),
        ),
    ]
