# Generated by Django 6.1.1 on 2026-09-26 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("divulgacion_cientifica", "0001_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="articulodivulgacion",
            name="agradecimientos",
            field=models.ManyToManyField(
                blank=True,
                related_name="articulos_divulgacion_agradecimiento",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="articulodivulgacion",
            name="revista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.revista"
            ),
        ),
        migrations.AddField(
            model_name="articulodivulgacionautor",
            name="articulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="divulgacion_cientifica.articulodivulgacion",
            ),
        ),
        migrations.AddField(
            model_name="articulodivulgacionautor",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="articulodivulgacion",
            name="autores",
            field=models.ManyToManyField(
                related_name="articulos_divulgacion",
                through="divulgacion_cientifica.ArticuloDivulgacionAutor",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="capitulolibrodivulgacion",
            name="libro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.libro"
            ),
        ),
        migrations.AddField(
            model_name="capitulolibrodivulgacionautor",
            name="capitulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="divulgacion_cientifica.capitulolibrodivulgacion",
            ),
        ),
        migrations.AddField(
            model_name="capitulolibrodivulgacionautor",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="capitulolibrodivulgacion",
            name="autores",
            field=models.ManyToManyField(
                related_name="capitulos_divulgacion",
                through="divulgacion_cientifica.CapituloLibroDivulgacionAutor",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="organizacioneventodivulgacion",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.evento"
            ),
        ),
        migrations.AddField(
            model_name="organizacioneventodivulgacion",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organizaciones_eventos_divulgacion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participacioneventodivulgacion",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.evento"
            ),
        ),
        migrations.AddField(
            model_name="participacioneventodivulgacion",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución organizadora",
            ),
        ),
        migrations.AddField(
            model_name="participacioneventodivulgacionautor",
            name="participacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="divulgacion_cientifica.participacioneventodivulgacion",
            ),
        ),
        migrations.AddField(
            model_name="participacioneventodivulgacionautor",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="participacioneventodivulgacion",
            name="autores",
            field=models.ManyToManyField(
                related_name="participaciones_eventos_divulgacion",
                through="divulgacion_cientifica.ParticipacionEventoDivulgacionAutor",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="programamedio",
            name="medio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.mediodivulgacion",
            ),
        ),
        migrations.AddField(
            model_name="programamedio",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programas_medios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="articulodivulgacionautor",
            constraint=models.UniqueConstraint(
                fields=("articulo", "persona"), name="articulo_divulgacion_autor_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="capitulolibrodivulgacionautor",
            constraint=models.UniqueConstraint(
                fields=("capitulo", "persona"), name="capitulo_divulgacion_autor_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="capitulolibrodivulgacion",
            constraint=models.UniqueConstraint(
                fields=("titulo", "libro"), name="capitulo_divulgacion_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="participacioneventodivulgacionautor",
            constraint=models.UniqueConstraint(
                fields=("participacion", "persona"),
                name="participacion_divulgacion_autor_unico",
            ),
        ),
    ]
