# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divulgacion_cientifica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaradiotelevisioninternet',
            name='partiticipantes',
            field=models.ManyToManyField(related_name='programa_radio_television_internet_participantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programaradiotelevisioninternet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='programa_radio_television_internet_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='participacionevento',
            name='autores',
            field=models.ManyToManyField(related_name='participacion_evento_autores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participacionevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Evento'),
        ),
        migrations.AddField(
            model_name='participacionevento',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='participacion_evento_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='organizacionevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Evento'),
        ),
        migrations.AddField(
            model_name='organizacionevento',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='organizacion_evento_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='mediodivulgacion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='medio_divulgacion_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='mediodivulgacion',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ubicacion'),
        ),
        migrations.AddField(
            model_name='librodivulgacion',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Libro'),
        ),
        migrations.AddField(
            model_name='librodivulgacion',
            name='proyectos',
            field=models.ManyToManyField(blank=True, related_name='libro_divulgracion_proyectos', to='nucleo.Proyecto'),
        ),
        migrations.AddField(
            model_name='librodivulgacion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='libro_divulgacion_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='capitulolibrodivulgacion',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Libro'),
        ),
        migrations.AddField(
            model_name='capitulolibrodivulgacion',
            name='proyectos',
            field=models.ManyToManyField(blank=True, related_name='capitulo_libro_divulgracion_proyectos', to='nucleo.Proyecto'),
        ),
        migrations.AddField(
            model_name='capitulolibrodivulgacion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='capitulo_libro_divulgacion_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='articulodivulgacion',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='articulo_divulgracion_alumnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulodivulgacion',
            name='autores',
            field=models.ManyToManyField(related_name='articulo_divulgracion_autores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulodivulgacion',
            name='indices',
            field=models.ManyToManyField(blank=True, related_name='articulo_divulgracion_indices', to='nucleo.Indice'),
        ),
        migrations.AddField(
            model_name='articulodivulgacion',
            name='proyectos',
            field=models.ManyToManyField(blank=True, related_name='articulo_divulgracion_proyectos', to='nucleo.Proyecto'),
        ),
        migrations.AddField(
            model_name='articulodivulgacion',
            name='revista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Revista'),
        ),
        migrations.AddField(
            model_name='articulodivulgacion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articulo_divulgacion_tags', to='nucleo.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='mediodivulgacion',
            unique_together=set([('canal', 'nombre_medio')]),
        ),
    ]
