# Generated by Django 2.0.5 on 2018-05-03 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
        ('divulgacion_cientifica', '0001_initial'),
        ('investigacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaradiotelevisioninternet',
            name='medio_divulgacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.MedioDivulgacion'),
        ),
        migrations.AddField(
            model_name='programaradiotelevisioninternet',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participacioneventodivulgacion',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Evento'),
        ),
        migrations.AddField(
            model_name='participacioneventodivulgacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizacioneventodivulgacion',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Evento'),
        ),
        migrations.AddField(
            model_name='organizacioneventodivulgacion',
            name='financiamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Financiamiento'),
        ),
        migrations.AddField(
            model_name='organizacioneventodivulgacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitulolibrodivulgacion',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Libro'),
        ),
        migrations.AddField(
            model_name='capitulolibrodivulgacion',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='investigacion.ProyectoInvestigacion'),
        ),
        migrations.AddField(
            model_name='capitulolibrodivulgacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulodivulgacion',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='articulo_divulgacion_alumnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulodivulgacion',
            name='indices',
            field=models.ManyToManyField(blank=True, related_name='articulo_divulgacion_indices', to='nucleo.Indice'),
        ),
        migrations.AddField(
            model_name='articulodivulgacion',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='investigacion.ProyectoInvestigacion'),
        ),
        migrations.AddField(
            model_name='articulodivulgacion',
            name='revista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Revista'),
        ),
        migrations.AddField(
            model_name='articulodivulgacion',
            name='usuarios',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='articulo_divulgacion_autores', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
        migrations.AlterUniqueTogether(
            name='capitulolibrodivulgacion',
            unique_together={('titulo', 'libro', 'usuario')},
        ),
    ]
