# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 00:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divulgacion_cientifica', '0002_auto_20170403_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulolibrodivulgacion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='capitulolibrodivulgacion',
            unique_together=set([('titulo', 'libro', 'usuario')]),
        ),
    ]
