# Generated by Django 2.0.5 on 2018-05-30 13:48

from django.conf import settings
from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divulgacion_cientifica', '0002_auto_20180503_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulolibrodivulgacion',
            name='usuarios',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='capitulo_libro_divulgacion_autores', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
    ]
