# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 00:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacion_cientifica', '0002_auto_20171004_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulodivulgacion',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='articulo_divulgacion_alumnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articulodivulgacion',
            name='indices',
            field=models.ManyToManyField(blank=True, related_name='articulo_divulgacion_indices', to='nucleo.Indice'),
        ),
        migrations.AlterField(
            model_name='articulodivulgacion',
            name='usuarios',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='articulo_divulgacion_autores', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
    ]
