# Generated by Django 2.0.2 on 2018-02-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacion_cientifica', '0002_auto_20180207_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulodivulgacion',
            name='indizado',
        ),
    ]
