# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacion_cientifica', '0002_auto_20171102_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulodivulgacion',
            name='tipo',
            field=models.CharField(choices=[('', '-------'), ('ARTICULO', 'Artículo'), ('ACTA', 'Acta'), ('CARTA', 'Carta'), ('RESENA', 'Reseña'), ('OTRO', 'Otro')], max_length=16),
        ),
    ]
