# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacion_cientifica', '0003_auto_20170403_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulolibrodivulgacion',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='mediodivulgacion',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='participacioneventodivulgacion',
            name='slug',
        ),
    ]
