# Generated by Django 6.1.1 on 2026-09-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacion_cientifica', '0003_alter_participacioneventodivulgacion_ambito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparticipacioneventodivulgacion',
            name='ambito',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('INSTITUCIONAL', 'Institucional'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional')], max_length=20, verbose_name='ámbito'),
        ),
        migrations.AlterField(
            model_name='participacioneventodivulgacion',
            name='ambito',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('INSTITUCIONAL', 'Institucional'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional')], max_length=20, verbose_name='ámbito'),
        ),
    ]
