# Generated by Django 6.1.1 on 2026-09-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacion_cientifica', '0004_ambito_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogramamedio',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='programamedio',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
