# Generated by Django 6.1.1 on 2026-10-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacion_cientifica', '0006_fechas_vacias_a_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogramamedio',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='programamedio',
            name='fecha',
            field=models.DateField(),
        ),
    ]
