# Generated by Django 6.1.1 on 2026-10-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacion_cientifica', '0007_fechas_obligatorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganizacioneventodivulgacion',
            name='organizado_por',
            field=models.CharField(choices=[('UNIDAD_COMUNICACION', 'Unidad de comunicación de la entidad'), ('COMISION', 'Comisión de la entidad'), ('COPARTICIPACION', 'Coorganizado con otras dependencias del campus'), ('EXTERNA', 'Dependencia externa a la UNAM u otra institución'), ('PERSONAL_ACADEMICO', 'Personal académico')], default='PERSONAL_ACADEMICO', max_length=30, verbose_name='organizado por'),
        ),
        migrations.AddField(
            model_name='historicalparticipacioneventodivulgacion',
            name='organizado_por',
            field=models.CharField(blank=True, choices=[('UNIDAD_COMUNICACION', 'Unidad de comunicación de la entidad'), ('COMISION', 'Comisión de la entidad'), ('COPARTICIPACION', 'Coorganizado con otras dependencias del campus'), ('EXTERNA', 'Dependencia externa a la UNAM u otra institución'), ('PERSONAL_ACADEMICO', 'Personal académico')], max_length=30, verbose_name='organizado por'),
        ),
        migrations.AddField(
            model_name='organizacioneventodivulgacion',
            name='organizado_por',
            field=models.CharField(choices=[('UNIDAD_COMUNICACION', 'Unidad de comunicación de la entidad'), ('COMISION', 'Comisión de la entidad'), ('COPARTICIPACION', 'Coorganizado con otras dependencias del campus'), ('EXTERNA', 'Dependencia externa a la UNAM u otra institución'), ('PERSONAL_ACADEMICO', 'Personal académico')], default='PERSONAL_ACADEMICO', max_length=30, verbose_name='organizado por'),
        ),
        migrations.AddField(
            model_name='participacioneventodivulgacion',
            name='organizado_por',
            field=models.CharField(blank=True, choices=[('UNIDAD_COMUNICACION', 'Unidad de comunicación de la entidad'), ('COMISION', 'Comisión de la entidad'), ('COPARTICIPACION', 'Coorganizado con otras dependencias del campus'), ('EXTERNA', 'Dependencia externa a la UNAM u otra institución'), ('PERSONAL_ACADEMICO', 'Personal académico')], max_length=30, verbose_name='organizado por'),
        ),
        migrations.AlterField(
            model_name='historicalprogramamedio',
            name='actividad',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('PARTICIPACION', 'Participación'), ('ENTREVISTA', 'Entrevista'), ('TRANSMISION', 'Transmisión en línea de un evento'), ('OTRA', 'Otra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='programamedio',
            name='actividad',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('PARTICIPACION', 'Participación'), ('ENTREVISTA', 'Entrevista'), ('TRANSMISION', 'Transmisión en línea de un evento'), ('OTRA', 'Otra')], max_length=20),
        ),
    ]
