# Generated by Django 2.0.6 on 2018-12-05 19:00

from django.conf import settings
from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacion_cientifica', '0008_participacioneventodivulgacion_autores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacioneventodivulgacion',
            name='participantes',
        ),
        migrations.AlterField(
            model_name='articulodivulgacion',
            name='status',
            field=models.CharField(choices=[('', '-------'), ('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('EN_PRENSA', 'En prensa'), ('PUBLICADO', 'Publicado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organizacioneventodivulgacion',
            name='apoyo_tecnico',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='organizacion_evento_divulgacion_apoyo_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Apoyo técnico'),
        ),
        migrations.AlterField(
            model_name='organizacioneventodivulgacion',
            name='ayudantes',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='organizacion_evento_divulgacion_ayudantes', to=settings.AUTH_USER_MODEL, verbose_name='Ayudantes'),
        ),
        migrations.AlterField(
            model_name='organizacioneventodivulgacion',
            name='comite_organizador',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='organizacion_evento_divulgacion_comite_organizador', to=settings.AUTH_USER_MODEL, verbose_name='Comite organizador'),
        ),
    ]
