# Generated by Django 6.1.1 on 2026-10-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "divulgacion_cientifica",
            "0008_historicalorganizacioneventodivulgacion_organizado_por_and_more",
        ),
        ("nucleo", "0037_capitulos_traspaso"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="capitulolibrodivulgacion",
            name="capitulo_divulgacion_unico",
        ),
        migrations.RemoveField(
            model_name="historicalcapitulolibrodivulgacionautor",
            name="capitulo",
        ),
        migrations.RemoveConstraint(
            model_name="capitulolibrodivulgacionautor",
            name="capitulo_divulgacion_autor_unico",
        ),
        migrations.RemoveField(
            model_name="historicalcapitulolibrodivulgacionautor",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalcapitulolibrodivulgacionautor",
            name="persona",
        ),
        migrations.RemoveField(
            model_name="capitulolibrodivulgacion",
            name="autores",
        ),
        migrations.RemoveField(
            model_name="capitulolibrodivulgacion",
            name="libro",
        ),
        migrations.RemoveField(
            model_name="capitulolibrodivulgacionautor",
            name="capitulo",
        ),
        migrations.RemoveField(
            model_name="capitulolibrodivulgacionautor",
            name="persona",
        ),
        migrations.DeleteModel(
            name="HistoricalCapituloLibroDivulgacion",
        ),
        migrations.DeleteModel(
            name="HistoricalCapituloLibroDivulgacionAutor",
        ),
        migrations.DeleteModel(
            name="CapituloLibroDivulgacion",
        ),
        migrations.DeleteModel(
            name="CapituloLibroDivulgacionAutor",
        ),
    ]
