# Generated by Django 2.0.1 on 2018-01-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitaPublicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajo_citado', models.CharField(choices=[('', '-------'), ('ARTICULO', 'Artículo'), ('LIBRO', 'Libro'), ('CAPITULO_LIBRO', 'Capítulo de libro')], max_length=20)),
                ('citado_en_tesis', models.TextField(blank=True)),
                ('citado_en_otras_publicaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cita de publicación',
                'verbose_name_plural': 'Citas de publicaciones',
            },
        ),
        migrations.CreateModel(
            name='DistincionAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Distinción recibida por académico',
                'verbose_name_plural': 'Distinciones recibidas por académicos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DistincionAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_academico', models.CharField(choices=[('', '-------'), ('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Distinción recibida por alumno',
                'verbose_name_plural': 'Distinciones recibidas por alumnos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacionComisionExpertos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Participación en comisión de expertos',
                'verbose_name_plural': 'Participaciones en comisiones de expertos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacionSociedadCientifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('', '-------'), ('INVITACION', 'Por invitación'), ('ELECCION', 'Por elección')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Participación en sociedad científica',
                'verbose_name_plural': 'Participaciones en sociedades científicas',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
