# Generated by Django 6.1.1 on 2026-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComisionExpertos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "participación en comisión de expertos",
                "verbose_name_plural": "participaciones en comisiones de expertos",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="DistincionAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
            ],
            options={
                "verbose_name": "distinción recibida",
                "verbose_name_plural": "distinciones recibidas",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DistincionAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("LICENCIATURA", "Licenciatura"),
                            ("MAESTRIA", "Maestría"),
                            ("DOCTORADO", "Doctorado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField()),
            ],
            options={
                "verbose_name": "distinción recibida por alumno",
                "verbose_name_plural": "distinciones recibidas por alumnos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="SociedadCientifica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Déjala vacía si sigue vigente.",
                        null=True,
                        verbose_name="fecha de término",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INVITACION", "Por invitación"),
                            ("ELECCION", "Por elección"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ambito",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local"),
                            ("INSTITUCIONAL", "Institucional"),
                            ("REGIONAL", "Regional"),
                            ("NACIONAL", "Nacional"),
                            ("INTERNACIONAL", "Internacional"),
                        ],
                        max_length=20,
                        verbose_name="ámbito",
                    ),
                ),
            ],
            options={
                "verbose_name": "participación en sociedad científica",
                "verbose_name_plural": "participaciones en sociedades científicas",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
