# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistincionAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('', '-------'), ('INSTITUCIONAL', 'Institucional'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional'), ('OTRO', 'Otro')], max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Distinción recibida',
                'verbose_name_plural': 'Distinciones recibidas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DistincionAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_academico', models.CharField(choices=[('OTRO', 'Otro'), ('LICENCIATURA', 'Licenciatura'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=20)),
                ('ambito', models.CharField(choices=[('', '-------'), ('INSTITUCIONAL', 'Institucional'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional'), ('OTRO', 'Otro')], max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Distinción recibida',
                'verbose_name_plural': 'Distinciones recibidas',
                'ordering': ['-fecha'],
            },
        ),
    ]
