# Generated by Django 6.1.1 on 2026-09-26 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("distinciones", "0001_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comisionexpertos",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.institucion",
                verbose_name="institución",
            ),
        ),
        migrations.AddField(
            model_name="comisionexpertos",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comisiones_expertos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="distincionacademico",
            name="distincion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.distincion",
                verbose_name="distinción",
            ),
        ),
        migrations.AddField(
            model_name="distincionacademico",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="distinciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="distincionalumno",
            name="alumno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="distinciones_alumno",
                to="nucleo.persona",
            ),
        ),
        migrations.AddField(
            model_name="distincionalumno",
            name="distincion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo.distincion",
                verbose_name="distinción",
            ),
        ),
        migrations.AddField(
            model_name="distincionalumno",
            name="tutores",
            field=models.ManyToManyField(
                related_name="distinciones_alumnos_tutorados", to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="sociedadcientifica",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sociedades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
