# Generated by Django 2.0.6 on 2018-11-12 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0010_auto_20181108_1630'),
        ('distinciones', '0002_auto_20180803_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacioncomisionexpertos',
            name='dependencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nucleo.Dependencia'),
            preserve_default=False,
        ),
    ]
