# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0004_auto_20171031_2114'),
        ('distinciones', '0002_auto_20171018_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distincionacademico',
            name='condecorados',
        ),
        migrations.RemoveField(
            model_name='distincionacademico',
            name='dependencia',
        ),
        migrations.RemoveField(
            model_name='distincionalumno',
            name='dependencia',
        ),
        migrations.AddField(
            model_name='distincionacademico',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distincionacademico',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distincionalumno',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion'),
            preserve_default=False,
        ),
    ]
