# Generated by Django 6.1.1 on 2026-09-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distinciones', '0003_historicalcomisionexpertos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionexpertos',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='distincionacademico',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomisionexpertos',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicaldistincionacademico',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalsociedadcientifica',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='sociedadcientifica',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha de inicio'),
        ),
    ]
