# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 22:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distinciones', '0003_auto_20171102_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distincionacademico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distincion_academico_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
