# Generated by Django 2.0.6 on 2018-12-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distinciones', '0003_participacioncomisionexpertos_dependencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacioncomisionexpertos',
            name='dependencia',
        ),
    ]
