# Generated by Django 6.1.1 on 2026-10-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distinciones', '0005_fechas_vacias_a_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionexpertos',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='distincionacademico',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalcomisionexpertos',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='historicaldistincionacademico',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalsociedadcientifica',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='sociedadcientifica',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
    ]
