# Generated by Django 6.1.1 on 2026-10-01 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distinciones', '0006_fechas_obligatorias'),
        ('nucleo', '0030_beca_ayuda_beca_clase_beca_institucion_cargo_ayuda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distincionacademico',
            name='detalle',
            field=models.CharField(blank=True, help_text='Nivel, área, año o edición (p. ej. Nivel D).', max_length=255),
        ),
        migrations.AddField(
            model_name='distincionacademico',
            name='institucion',
            field=models.ForeignKey(blank=True, help_text='Solo si no es la de la distinción (mención de grado, beca de estudios…).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nucleo.institucion', verbose_name='institución que la otorga'),
        ),
        migrations.AddField(
            model_name='distincionalumno',
            name='detalle',
            field=models.CharField(blank=True, help_text='Nivel, área, año o edición (p. ej. Nivel D).', max_length=255),
        ),
        migrations.AddField(
            model_name='distincionalumno',
            name='institucion',
            field=models.ForeignKey(blank=True, help_text='Solo si no es la de la distinción (mención de grado, beca de estudios…).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nucleo.institucion', verbose_name='institución que la otorga'),
        ),
        migrations.AddField(
            model_name='historicaldistincionacademico',
            name='detalle',
            field=models.CharField(blank=True, help_text='Nivel, área, año o edición (p. ej. Nivel D).', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaldistincionacademico',
            name='institucion',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Solo si no es la de la distinción (mención de grado, beca de estudios…).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.institucion', verbose_name='institución que la otorga'),
        ),
        migrations.AddField(
            model_name='historicaldistincionalumno',
            name='detalle',
            field=models.CharField(blank=True, help_text='Nivel, área, año o edición (p. ej. Nivel D).', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaldistincionalumno',
            name='institucion',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Solo si no es la de la distinción (mención de grado, beca de estudios…).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.institucion', verbose_name='institución que la otorga'),
        ),
    ]
