# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesarrolloTecnologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('version', models.CharField(max_length=100)),
                ('patente', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Desarrollos Tecnológicos',
                'ordering': ['nombre'],
                'get_latest_by': ['fecha', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDesarrollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Tipo de desarrollo',
                'verbose_name_plural': 'Tipos de desarrollo',
                'ordering': ['nombre'],
            },
        ),
    ]
