# Generated by Django 6.1.1 on 2026-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DesarrolloTecnologico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=254, unique=True)),
                ("descripcion", models.TextField(verbose_name="descripción")),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="versión"
                    ),
                ),
                ("patente", models.CharField(blank=True, max_length=255)),
                ("licencia", models.CharField(blank=True, max_length=254)),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                ("fecha", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "desarrollo tecnológico",
                "verbose_name_plural": "desarrollos tecnológicos",
                "ordering": ["-fecha", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="DesarrolloTecnologicoAutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "autor",
                "verbose_name_plural": "autores",
                "ordering": ["orden", "pk"],
                "abstract": False,
            },
        ),
    ]
