# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desarrollo_tecnologico', '0001_initial'),
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='agradecimientos',
            field=models.ManyToManyField(related_name='desarrollo_tecnologico_agradecimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='autores',
            field=models.ManyToManyField(related_name='desarrollo_tecnologico_autores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo_tecnologico.Licencia'),
        ),
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='proyectos',
            field=models.ManyToManyField(related_name='desarrollo_tecnologico_proyectos', to='nucleo.Proyecto'),
        ),
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='tags',
            field=models.ManyToManyField(related_name='desarrollo_tecnologico_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='tipo_desarrollo_tecnologico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo_tecnologico.TipoDesarrollo'),
        ),
    ]
