# Generated by Django 6.1.1 on 2026-09-26 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("desarrollo_tecnologico", "0001_initial"),
        ("investigacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="desarrollotecnologico",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="investigacion.proyectoinvestigacion",
            ),
        ),
        migrations.AddField(
            model_name="desarrollotecnologicoautor",
            name="desarrollo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="desarrollo_tecnologico.desarrollotecnologico",
            ),
        ),
    ]
