# Generated by Django 6.1.1 on 2026-09-26 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("desarrollo_tecnologico", "0002_initial"),
        ("nucleo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="desarrollotecnologicoautor",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.persona"
            ),
        ),
        migrations.AddField(
            model_name="desarrollotecnologico",
            name="autores",
            field=models.ManyToManyField(
                related_name="desarrollos_tecnologicos",
                through="desarrollo_tecnologico.DesarrolloTecnologicoAutor",
                to="nucleo.persona",
            ),
        ),
        migrations.AddConstraint(
            model_name="desarrollotecnologicoautor",
            constraint=models.UniqueConstraint(
                fields=("desarrollo", "persona"), name="desarrollo_autor_unico"
            ),
        ),
    ]
