# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoLicenciaGoceSueldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo_participacion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('importancia', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('presupuesto_personal', models.BooleanField(default=False)),
                ('carta_invitacion', models.BooleanField(default=False)),
                ('aceptacion_ponencia', models.BooleanField(default=False)),
                ('otro_anexo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Formato de licencia con goce de sueldo',
                'verbose_name_plural': 'Formatos de licencia con goce de sueldo',
                'ordering': ['fecha', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='FormatoPagoViatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('actividades', models.TextField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=20)),
                ('num_acta', models.PositiveIntegerField()),
                ('cargo_papiit', models.BooleanField(default=False)),
                ('cargo_conacyt', models.BooleanField(default=False)),
                ('cargo_papime', models.BooleanField(default=False)),
                ('cargo_ie', models.BooleanField(default=False)),
                ('cargo_po', models.BooleanField(default=False)),
                ('cargo_paep', models.BooleanField(default=False)),
                ('cargo_otro', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Formato de pago de viaticos',
                'verbose_name_plural': 'Formatos de pago de viaticos',
                'ordering': ['fecha_salida', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='FormatoServicioTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('uso', models.CharField(choices=[('', '-------'), ('DOCENCIA', 'Docencia'), ('INVESTIGACION', 'Investigación')], max_length=20)),
                ('num_pasajeros', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('', '-------'), ('LOCAL', 'Local'), ('FORANEO', 'Foraneo')], max_length=10)),
                ('km_aprox', models.PositiveIntegerField()),
                ('gasto_casetas', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('salidas_diarias', models.PositiveIntegerField(blank=True, null=True)),
                ('tiempo_completo', models.PositiveIntegerField(blank=True, null=True)),
                ('objetivo', models.TextField()),
            ],
            options={
                'verbose_name': 'Formato de solicitud de servicio de transporte',
                'verbose_name_plural': 'Formatos de solicitud de servicio de transporte',
                'ordering': ['fecha_inicio', 'usuario'],
            },
        ),
    ]
