# Generated by Django 6.1.1 on 2026-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LicenciaGoceSueldo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        auto_now_add=True, verbose_name="fecha de solicitud"
                    ),
                ),
                (
                    "tipo_participacion",
                    models.CharField(
                        max_length=255, verbose_name="tipo de participación"
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="fecha de término")),
                (
                    "importancia",
                    models.TextField(verbose_name="importancia para la entidad"),
                ),
                (
                    "costo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="costo total (MXN)",
                    ),
                ),
                ("presupuesto_personal", models.BooleanField(default=False)),
                (
                    "carta_invitacion",
                    models.BooleanField(
                        default=False, verbose_name="anexa carta de invitación"
                    ),
                ),
                (
                    "aceptacion_ponencia",
                    models.BooleanField(
                        default=False, verbose_name="anexa aceptación de ponencia"
                    ),
                ),
                ("otro_anexo", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "solicitud de licencia con goce de sueldo",
                "verbose_name_plural": "solicitudes de licencia con goce de sueldo",
                "ordering": ["-fecha", "-pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PagoViaticos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        auto_now_add=True, verbose_name="fecha de solicitud"
                    ),
                ),
                ("fecha_salida", models.DateField()),
                ("fecha_regreso", models.DateField()),
                (
                    "actividades",
                    models.TextField(verbose_name="actividades a realizar"),
                ),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="importe solicitado (MXN)",
                    ),
                ),
                (
                    "num_acta",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="acta de consejo interno",
                    ),
                ),
                (
                    "beneficiario",
                    models.CharField(
                        help_text="Persona a cuyo nombre se expide el cheque.",
                        max_length=255,
                        verbose_name="nombre del cheque",
                    ),
                ),
                (
                    "cargo_papiit",
                    models.BooleanField(
                        default=False, verbose_name="con cargo a PAPIIT"
                    ),
                ),
                (
                    "cargo_conacyt",
                    models.BooleanField(
                        default=False, verbose_name="con cargo a CONAHCYT"
                    ),
                ),
                (
                    "cargo_papime",
                    models.BooleanField(
                        default=False, verbose_name="con cargo a PAPIME"
                    ),
                ),
                (
                    "cargo_ie",
                    models.BooleanField(
                        default=False,
                        verbose_name="con cargo a ingresos extraordinarios",
                    ),
                ),
                (
                    "cargo_po",
                    models.BooleanField(
                        default=False, verbose_name="con cargo a presupuesto operativo"
                    ),
                ),
                (
                    "cargo_paep",
                    models.BooleanField(default=False, verbose_name="con cargo a PAEP"),
                ),
                (
                    "cargo_otro",
                    models.BooleanField(default=False, verbose_name="con cargo a otro"),
                ),
            ],
            options={
                "verbose_name": "solicitud de pago de viáticos",
                "verbose_name_plural": "solicitudes de pago de viáticos",
                "ordering": ["-fecha", "-pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServicioTransporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        auto_now_add=True, verbose_name="fecha de solicitud"
                    ),
                ),
                (
                    "uso",
                    models.CharField(
                        choices=[
                            ("DOCENCIA", "Docencia"),
                            ("INVESTIGACION", "Investigación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("LOCAL", "Local"), ("FORANEO", "Foráneo")],
                        max_length=10,
                    ),
                ),
                (
                    "num_pasajeros",
                    models.PositiveIntegerField(verbose_name="número de pasajeros"),
                ),
                (
                    "km_aprox",
                    models.PositiveIntegerField(verbose_name="kilómetros aproximados"),
                ),
                (
                    "gasto_casetas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="gasto en casetas",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="fecha de término")),
                ("salidas_diarias", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tiempo_completo",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="días de tiempo completo"
                    ),
                ),
                ("objetivo", models.TextField()),
            ],
            options={
                "verbose_name": "solicitud de servicio de transporte",
                "verbose_name_plural": "solicitudes de servicio de transporte",
                "ordering": ["-fecha", "-pk"],
                "abstract": False,
            },
        ),
    ]
