# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 05:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigacion', '0002_auto_20171018_2341'),
        ('nucleo', '0004_auto_20171031_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoLicenciaGoceSueldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo_participacion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('importancia', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('presupuesto_personal', models.BooleanField(default=False)),
                ('carta_invitacion', models.BooleanField(default=False)),
                ('aceptacion_ponencia', models.BooleanField(default=False)),
                ('otro', models.CharField(blank=True, max_length=255, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Evento')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion.ProyectoInvestigacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formato de licencia con goce de sueldo',
                'verbose_name_plural': 'Formatos de licencia con goce de sueldo',
                'ordering': ['fecha', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='FormatoPagoViatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_regreso', models.DateTimeField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formato de pago de viaticos',
                'verbose_name_plural': 'Formatos de pago de viaticos',
                'ordering': ['fecha', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='FormatoServicioTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('uso', models.CharField(choices=[('', '-------'), ('DOCENCIA', 'Docencia'), ('INVESTIGACION', 'Investigación')], max_length=20)),
                ('num_pasajeros', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('', '-------'), ('LOCAL', 'Local'), ('FORANEO', 'Foraneo')], max_length=10)),
                ('km_aprox', models.PositiveIntegerField()),
                ('gasto_casetas', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('salidas_diarias', models.PositiveIntegerField(blank=True, null=True)),
                ('tiempo_completo', models.PositiveIntegerField(blank=True, null=True)),
                ('objetivo', models.TextField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ciudad')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formato de solicitud de servicio de transporte',
                'verbose_name_plural': 'Formatos de solicitud de servicio de transporte',
                'ordering': ['fecha', 'usuario'],
            },
        ),
    ]
