# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formatopagoviatico',
            options={'ordering': ['fecha_salida', 'usuario'], 'verbose_name': 'Formato de pago de viaticos', 'verbose_name_plural': 'Formatos de pago de viaticos'},
        ),
        migrations.AlterModelOptions(
            name='formatoserviciotransporte',
            options={'ordering': ['fecha_inicio', 'usuario'], 'verbose_name': 'Formato de solicitud de servicio de transporte', 'verbose_name_plural': 'Formatos de solicitud de servicio de transporte'},
        ),
    ]
