# Generated by Django 6.1.1 on 2026-09-26 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("formatos", "0001_initial"),
        ("investigacion", "0001_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="licenciagocesueldo",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.evento"
            ),
        ),
        migrations.AddField(
            model_name="licenciagocesueldo",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="investigacion.proyectoinvestigacion",
            ),
        ),
        migrations.AddField(
            model_name="licenciagocesueldo",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pagoviaticos",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nucleo.evento"
            ),
        ),
        migrations.AddField(
            model_name="pagoviaticos",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="investigacion.proyectoinvestigacion",
            ),
        ),
        migrations.AddField(
            model_name="pagoviaticos",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="serviciotransporte",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
