# Generated by Django 6.1.1 on 2026-09-26 18:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formatos", "0002_initial"),
        ("investigacion", "0002_initial"),
        ("nucleo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLicenciaGoceSueldo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        blank=True, editable=False, verbose_name="fecha de solicitud"
                    ),
                ),
                (
                    "tipo_participacion",
                    models.CharField(
                        max_length=255, verbose_name="tipo de participación"
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="fecha de término")),
                (
                    "importancia",
                    models.TextField(verbose_name="importancia para la entidad"),
                ),
                (
                    "costo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="costo total (MXN)",
                    ),
                ),
                ("presupuesto_personal", models.BooleanField(default=False)),
                (
                    "carta_invitacion",
                    models.BooleanField(
                        default=False, verbose_name="anexa carta de invitación"
                    ),
                ),
                (
                    "aceptacion_ponencia",
                    models.BooleanField(
                        default=False, verbose_name="anexa aceptación de ponencia"
                    ),
                ),
                ("otro_anexo", models.CharField(blank=True, max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.evento",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investigacion.proyectoinvestigacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical solicitud de licencia con goce de sueldo",
                "verbose_name_plural": "historical solicitudes de licencia con goce de sueldo",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPagoViaticos",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        blank=True, editable=False, verbose_name="fecha de solicitud"
                    ),
                ),
                ("fecha_salida", models.DateField()),
                ("fecha_regreso", models.DateField()),
                (
                    "actividades",
                    models.TextField(verbose_name="actividades a realizar"),
                ),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="importe solicitado (MXN)",
                    ),
                ),
                (
                    "num_acta",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="acta de consejo interno",
                    ),
                ),
                (
                    "beneficiario",
                    models.CharField(
                        help_text="Persona a cuyo nombre se expide el cheque.",
                        max_length=255,
                        verbose_name="nombre del cheque",
                    ),
                ),
                (
                    "cargo_papiit",
                    models.BooleanField(
                        default=False, verbose_name="con cargo a PAPIIT"
                    ),
                ),
                (
                    "cargo_conacyt",
                    models.BooleanField(
                        default=False, verbose_name="con cargo a CONAHCYT"
                    ),
                ),
                (
                    "cargo_papime",
                    models.BooleanField(
                        default=False, verbose_name="con cargo a PAPIME"
                    ),
                ),
                (
                    "cargo_ie",
                    models.BooleanField(
                        default=False,
                        verbose_name="con cargo a ingresos extraordinarios",
                    ),
                ),
                (
                    "cargo_po",
                    models.BooleanField(
                        default=False, verbose_name="con cargo a presupuesto operativo"
                    ),
                ),
                (
                    "cargo_paep",
                    models.BooleanField(default=False, verbose_name="con cargo a PAEP"),
                ),
                (
                    "cargo_otro",
                    models.BooleanField(default=False, verbose_name="con cargo a otro"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nucleo.evento",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investigacion.proyectoinvestigacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical solicitud de pago de viáticos",
                "verbose_name_plural": "historical solicitudes de pago de viáticos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalServicioTransporte",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        blank=True, editable=False, verbose_name="fecha de solicitud"
                    ),
                ),
                (
                    "uso",
                    models.CharField(
                        choices=[
                            ("DOCENCIA", "Docencia"),
                            ("INVESTIGACION", "Investigación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("LOCAL", "Local"), ("FORANEO", "Foráneo")],
                        max_length=10,
                    ),
                ),
                (
                    "num_pasajeros",
                    models.PositiveIntegerField(verbose_name="número de pasajeros"),
                ),
                (
                    "km_aprox",
                    models.PositiveIntegerField(verbose_name="kilómetros aproximados"),
                ),
                (
                    "gasto_casetas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="gasto en casetas",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="fecha de término")),
                ("salidas_diarias", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tiempo_completo",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="días de tiempo completo"
                    ),
                ),
                ("objetivo", models.TextField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical solicitud de servicio de transporte",
                "verbose_name_plural": "historical solicitudes de servicio de transporte",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
