# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0002_auto_20171102_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formatolicenciagocesueldo',
            old_name='otro',
            new_name='otro_anexo',
        ),
    ]
