# Generated by Django 2.1.7 on 2019-02-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formatos', '0002_auto_20181213_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formatoserviciotransporte',
            name='ciudad',
        ),
    ]
